export const ADVERSARIAL_VALIDATION_SUITE_CONTRACT = {
  id: "adversarial-validation-suite-v1",
  name: "Adversarial validation suite",
  purpose:
    "Turn hostile-input and leakage expectations into repeatable release validation across public forms, customer APIs, support flows, report surfaces, notifications, billing, and operator command interfaces.",
  operatingStandard:
    "Adversarial checks are mandatory release evidence. A test that catches prompt injection, secret leakage, cross-customer access, unsafe raw projection, or unsupported promise risk must never be bypassed to ship faster.",
  attackClasses: [
    "prompt-injection-and-system-override-attempts",
    "credential-token-and-secret-submission",
    "payment-card-and-billing-data-submission",
    "raw-evidence-dump-and-private-document-submission",
    "cross-customer-identifier-and-ownership-confusion",
    "admin-key-support-key-and-protected-header-exposure",
    "unsafe-refund-legal-security-report-or-roi-promise-demand",
    "operator-internal-note-and-risk-internal-projection",
    "browser-storage-and-public-javascript-secret-exposure",
    "notification-email-and-report-raw-content-leakage",
  ],
  protectedSurfaces: [
    "homepage-concierge-nudge",
    "free-scan-room",
    "public-signup-and-verification",
    "customer-dashboard",
    "customer-notification-center",
    "customer-support-request-api",
    "customer-support-status-api",
    "customer-support-update-api",
    "support-lifecycle-notification-runtime",
    "support-lifecycle-email-queue",
    "report-vault-and-report-rendering",
    "billing-and-plan-surfaces",
    "operator-safe-summary-api",
    "operator-assignment-and-approval-apis",
    "admin-support-console",
  ],
  requiredSafeOutcomes: [
    "sanitize or reject hostile prompt-injection content without echoing the raw attack",
    "classify secret-like content as sensitive and prevent customer-visible projection",
    "prevent payment-like content from entering support, report, notification, or email records",
    "block cross-customer access through server-side ownership checks",
    "keep protected headers, admin keys, support context keys, session tokens, and CSRF tokens out of browser code and customer copy",
    "hold or suppress communications when ownership, verified session, safe projection, or channel guards are missing",
    "render bounded customer-safe errors without account-existence leakage",
    "keep operator notes, reviewer identity, risk internals, and attacker details out of customer surfaces",
    "preserve audit proof without storing unnecessary sensitive raw content",
    "reject unsupported legal, refund, report-change, security-outcome, ROI, or business-result promises",
  ],
  repeatableValidationRequirements: [
    "each hostile-input class must have a named expected outcome",
    "each protected surface must identify whether the safe result is reject, sanitize, hold, suppress, safe-project, or audit-only",
    "validators must fail on browser storage of protected authority",
    "validators must fail on forbidden raw projection patterns",
    "validators must fail on impossible security or outcome claims",
    "validators must fail when adversarial coverage is removed without replacement",
  ],
  releaseRules: [
    "adversarial validation must run before merge through a locked gate",
    "failures must be patched directly instead of suppressing the test",
    "new public, customer, operator, report, notification, billing, or support flows must add adversarial coverage where relevant",
    "high-risk flows must remain closed-by-default until safe projection and ownership checks are validated",
  ],
  safeCustomerCommunication:
    "If hostile or unsafe content is submitted, customer-facing copy should stay calm, bounded, and useful without exposing the raw attack, private evidence, or internal detection mechanics.",
} as const;

export const ADVERSARIAL_VALIDATION_CASES = [
  { key: "prompt-injection", surface: "support request and Free Scan", expectedOutcome: "sanitize-or-reject-without-raw-echo" },
  { key: "credential-submission", surface: "support request, notifications, reports", expectedOutcome: "classify-sensitive-and-block-projection" },
  { key: "payment-data", surface: "support request and billing help", expectedOutcome: "reject-payment-like-content-from-records" },
  { key: "cross-customer-access", surface: "dashboard, support status, reports, billing", expectedOutcome: "server-side-ownership-deny" },
  { key: "browser-secret-exposure", surface: "public JS and client components", expectedOutcome: "fail-validation" },
  { key: "operator-internal-projection", surface: "support status, notifications, emails", expectedOutcome: "safe-project-only" },
  { key: "unsafe-promise-demand", surface: "support, report, plans, homepage", expectedOutcome: "reject-or-bound-copy" },
  { key: "raw-evidence-dump", surface: "support and report intake", expectedOutcome: "summarize-safely-without-customer-visible-raw" },
] as const;

export const ADVERSARIAL_VALIDATION_BLOCKED_PATTERNS = [
  "ignorePromptInjection",
  "echoRawAttack",
  "storeRawCredential",
  "storePaymentCardInSupport",
  "bypassOwnershipForTest",
  "exposeAdminKeyToBrowser",
  "exposeSupportContextKeyToBrowser",
  "customerVisibleInternalNotes",
  "customerVisibleRiskInternals",
  "customerVisibleAttackerDetails",
  "guaranteedROI",
  "guaranteedRefund",
  "guaranteedLegalOutcome",
  "impossibleToHack",
  "disableAdversarialValidation",
] as const;
