export const BILLING_CHECKOUT_CONTRACT = {
  id: "billing-checkout-contract",
  name: "Billing Checkout and Payment Link Contract",
  purpose:
    "Define how Cendorq creates checkout, accepts payment-link configuration, verifies billing events, projects entitlements, and routes billing recovery without collecting raw payment data or making unsupported promises.",
  checkoutSurfaces: [
    "plans-to-checkout",
    "dashboard-to-checkout",
    "billing-center-to-checkout",
    "report-vault-to-plan-upgrade",
    "support-to-billing-center",
    "billing-webhook-to-entitlement",
  ],
  allowedPaymentLinkInputs: [
    "deep review payment link id or URL provided by owner",
    "build fix payment link id or URL provided by owner",
    "ongoing control payment link id or URL provided by owner",
    "billing portal link id or URL provided by owner",
  ],
  requiredCheckoutFields: [
    "planKey",
    "customerIdHash",
    "businessIdHash when applicable",
    "checkoutSessionIdHash",
    "providerName",
    "safePlanLabel",
    "priceDisplaySnapshot",
    "successPath",
    "cancelPath",
    "auditId",
  ],
  checkoutRules: [
    "Checkout must be created server-side or via owner-provided payment link mapping; the browser must not create authoritative billing state.",
    "Checkout must use customer-owned session context and safe plan mapping before routing to provider checkout.",
    "Checkout copy must separate current access, pending payment action, and future entitlement.",
    "Plans and billing center may explain plan fit, but they must not promise ROI, revenue, refund, report changes, billing changes, security outcomes, or legal outcomes.",
    "Support copy may route customers to billing center or provider portal, but must never ask for card numbers, bank details, passwords, private keys, session tokens, CSRF tokens, admin keys, or support context keys.",
  ],
  webhookRules: [
    "Billing webhooks must be verified with provider signature before any entitlement change.",
    "Webhook event ids must be idempotent and stored as hashes or safe references.",
    "Entitlement updates require provider event type, customer ownership mapping, plan mapping, and audit event.",
    "Failed, disputed, refunded, canceled, incomplete, or expired checkout states must use calm recovery copy and not pressure-based urgency.",
    "Raw provider payloads, raw billing data, payment method details, card numbers, bank details, and provider internals must not be projected to customer surfaces.",
  ],
  entitlementProjectionFields: [
    "customerIdHash",
    "planKey",
    "safePlanLabel",
    "entitlementStatus",
    "currentAccess",
    "pendingAction",
    "futureEntitlement",
    "billingPortalAvailable",
    "invoiceAvailability",
    "supportPath",
    "auditId",
  ],
  blockedProjectionFields: [
    "rawProviderPayload",
    "rawBillingData",
    "cardNumber",
    "bankDetails",
    "paymentMethodFingerprint",
    "providerSecret",
    "webhookSecret",
    "checkoutSessionRaw",
    "invoiceRaw",
    "subscriptionRaw",
    "customerRaw",
    "internalNotes",
    "operatorIdentity",
    "riskScoringInternals",
    "sessionToken",
    "csrfToken",
    "adminKey",
    "supportContextKey",
  ],
  recoveryRules: [
    "Billing recovery must identify the safe next action: retry checkout, open billing portal, contact support with safe summary, or return to dashboard.",
    "Billing recovery must not shame the customer, remove the visible support route, imply fake scarcity, or threaten unsupported loss of records.",
    "Canceled checkout must return to plans or dashboard without creating entitlement.",
    "Successful checkout must route to dashboard or billing center with pending/active entitlement clearly separated.",
  ],
  releaseRules: [
    "Do not enable paid checkout until payment links or provider checkout config are owner-provided and mapped to plan keys.",
    "Do not activate entitlement from client-only success redirects; verified webhook or server-confirmed provider state is required.",
    "Do not expose paid report access until entitlement, report release approval, customer ownership, and verified access pass.",
    "Do not deploy billing copy or runtime that asks customers to submit raw payment data through support.",
  ],
} as const;

export const BILLING_CHECKOUT_BLOCKED_PATTERNS = [
  "clientAuthoritativeBillingState",
  "unverifiedWebhookEntitlement",
  "rawProviderPayloadProjection",
  "rawBillingDataProjection",
  "cardNumberCollectionInSupport",
  "bankDetailsCollectionInSupport",
  "paymentMethodFingerprintProjection",
  "providerSecretExposure",
  "webhookSecretExposure",
  "checkoutSessionRawProjection",
  "invoiceRawProjection",
  "subscriptionRawProjection",
  "guaranteedRoiCheckoutClaim",
  "guaranteedRevenueCheckoutClaim",
  "guaranteedRefundCheckoutClaim",
  "guaranteedBillingChangeClaim",
  "fakeUrgencyBillingClaim",
  "hiddenSupportPath",
  "entitlementWithoutOwnership",
  "reportAccessWithoutEntitlement",
] as const;

export function getBillingCheckoutContract() {
  return BILLING_CHECKOUT_CONTRACT;
}
