export const COMPLETE_PLAN_FULFILLMENT_MATRIX = {
  id: "complete-plan-fulfillment-matrix",
  name: "Complete Cendorq Plan Fulfillment Matrix",
  purpose:
    "Define the complete A-to-Z fulfillment system for every Cendorq plan, from trigger and intake through research, production, quality review, delivery, follow-up, escalation, retention, and upgrade paths, while preserving truthful analysis, premium experience, conversion ethics, safe automation, and release-captain approval.",
  universalStages: [
    "trigger",
    "customer confirmation",
    "safe intake",
    "evidence collection",
    "truth separation",
    "agent work assignment",
    "production work",
    "quality review",
    "release-captain approval",
    "customer delivery",
    "email notification",
    "dashboard update",
    "report vault update",
    "support path",
    "follow-up sequence",
    "upgrade or retention path",
    "audit and learning record",
  ],
  planMatrix: [
    {
      key: "free-scan",
      name: "Free Scan / Free Report",
      trigger: "Customer submits guided Free Check form.",
      completionGoal: "Deliver a useful first-read report and route the customer to the right next step without pretending the free scan is final or exhaustive.",
      stages: [
        { stage: "customer confirmation", artifact: "scan received confirmation", owner: "customer-journey-scout", gate: "safe submission accepted" },
        { stage: "safe intake", artifact: "free scan intake record", owner: "report-truth-research-scout", gate: "no secrets, no raw payload exposure" },
        { stage: "evidence collection", artifact: "initial owned-surface and safe public signal notes", owner: "report-truth-research-scout", gate: "evidence labeled by source and confidence" },
        { stage: "truth separation", artifact: "first-read facts, assumptions, limitations, and next actions", owner: "chief-report-truth-agent", gate: "customer claims not treated as verified facts" },
        { stage: "production work", artifact: "free scan report draft", owner: "report-design-quality-scout", gate: "premium but bounded report language" },
        { stage: "quality review", artifact: "safe free-report review", owner: "chief-report-truth-agent", gate: "no final-complete diagnosis claim" },
        { stage: "release-captain approval", artifact: "free report release posture", owner: "release-captain", gate: "safe customer-facing output approved" },
        { stage: "customer delivery", artifact: "free report in dashboard and report vault", owner: "customer-journey-scout", gate: "connected handoff exists" },
        { stage: "email notification", artifact: "report ready email with dashboard/report-vault path", owner: "customer-lifecycle-automation", gate: "no fake urgency" },
        { stage: "follow-up sequence", artifact: "non-pressure helpful follow-up", owner: "conversion-luxury-ui-scout", gate: "upgrade only if evidence supports next step" },
      ],
      requiredCustomerInputs: ["business name", "website", "location", "business type", "primary offer", "audience", "biggest issue"],
      optionalCustomerInputs: ["competitors", "extra context", "previous attempts"],
      deliveryArtifacts: ["free scan report", "email report-ready notice", "dashboard card", "report vault record", "safe plan-fit suggestion"],
      followUpSequences: ["report opened guidance", "clarifying question prompt", "deep-review recommendation when evidence supports it", "support/correction path"],
      conversionPath: "Deep Review / Full Scan only when the first-read evidence shows deeper diagnosis would help.",
    },
    {
      key: "deep-review",
      name: "Deep Review / Full Scan",
      trigger: "Customer purchases or upgrades from Free Scan.",
      completionGoal: "Deliver a deeper, evidence-backed diagnostic report with expanded research, conflicts, confidence, priority blockers, and plan-fit rationale.",
      stages: [
        { stage: "customer confirmation", artifact: "purchase received confirmation", owner: "customer-lifecycle-automation", gate: "payment and customer ownership verified" },
        { stage: "safe intake", artifact: "expanded diagnostic questionnaire", owner: "customer-journey-scout", gate: "no passwords, tokens, private keys, card numbers, or bank details" },
        { stage: "evidence collection", artifact: "expanded evidence packet", owner: "evidence-conflict-scout", gate: "customer input compared to owned and public evidence" },
        { stage: "truth separation", artifact: "fact, claim, inference, limitation, and conflict map", owner: "chief-report-truth-agent", gate: "conflicts disclosed rather than hidden" },
        { stage: "agent work assignment", artifact: "research and report task map", owner: "chief-report-truth-agent", gate: "each agent lane scoped" },
        { stage: "production work", artifact: "full diagnostic report", owner: "report-design-quality-scout", gate: "premium report structure and actionable priorities" },
        { stage: "quality review", artifact: "truth and usefulness review", owner: "chief-report-truth-agent", gate: "evidence supports every strong statement" },
        { stage: "release-captain approval", artifact: "full report release approval", owner: "release-captain", gate: "report release approved" },
        { stage: "customer delivery", artifact: "full report in vault and dashboard", owner: "customer-journey-scout", gate: "clear next action and support route" },
        { stage: "follow-up sequence", artifact: "report review and next-action sequence", owner: "conversion-luxury-ui-scout", gate: "no guaranteed outcome claim" },
      ],
      requiredCustomerInputs: ["business goals", "current funnel", "customer objections", "best customers", "known competitors", "previous attempts", "approved non-secret access context"],
      optionalCustomerInputs: ["analytics exports with private data removed", "brand notes", "customer reviews", "sales scripts", "ad landing pages"],
      deliveryArtifacts: ["full diagnostic report", "priority blocker map", "evidence and confidence summary", "plan-fit rationale", "report-ready email", "dashboard/report-vault update"],
      followUpSequences: ["intake reminder", "analysis in progress", "report ready", "report questions", "Build Fix or Ongoing Control recommendation only when evidence supports it"],
      conversionPath: "Build Fix / Optimization when the report identifies concrete implementation work; Ongoing Control when recurring monitoring or market change management is justified.",
    },
    {
      key: "build-fix",
      name: "Build Fix / Optimization",
      trigger: "Customer purchases implementation or optimization work after evidence supports concrete changes.",
      completionGoal: "Produce and deliver scoped, approved, evidence-backed improvements that help the business act on the diagnosis without overpromising outcomes.",
      stages: [
        { stage: "customer confirmation", artifact: "optimization purchase confirmation", owner: "customer-lifecycle-automation", gate: "payment and ownership verified" },
        { stage: "safe intake", artifact: "scope, assets, and approval checklist", owner: "customer-journey-scout", gate: "no secrets or raw credentials requested" },
        { stage: "evidence collection", artifact: "before-change evidence snapshot", owner: "security-privacy-scout", gate: "customer-safe snapshot only" },
        { stage: "truth separation", artifact: "implementation rationale map", owner: "chief-product-experience-agent", gate: "changes tied to evidence and scope" },
        { stage: "agent work assignment", artifact: "optimization work queue", owner: "chief-product-experience-agent", gate: "work items scoped and reviewable" },
        { stage: "production work", artifact: "copy, layout, funnel, trust, or action-path improvements", owner: "conversion-luxury-ui-scout", gate: "no uncontrolled production mutation" },
        { stage: "quality review", artifact: "before-after review packet", owner: "report-design-quality-scout", gate: "customer comprehension and premium quality verified" },
        { stage: "release-captain approval", artifact: "delivery approval record", owner: "release-captain", gate: "customer-facing delivery approved" },
        { stage: "customer delivery", artifact: "delivery summary and implementation guidance", owner: "customer-journey-scout", gate: "customer approval path visible" },
        { stage: "follow-up sequence", artifact: "post-delivery review and adjustment path", owner: "analytics-and-growth-scout", gate: "performance language remains non-guaranteed" },
      ],
      requiredCustomerInputs: ["scope approval", "brand context", "target page or funnel", "implementation constraints", "approval contact", "non-secret asset package"],
      optionalCustomerInputs: ["design preferences", "existing copy", "approved screenshots", "customer testimonials", "analytics summaries"],
      deliveryArtifacts: ["optimization plan", "implementation-ready task list", "copy/layout recommendations", "before-after summary", "delivery-ready email", "support/correction path"],
      followUpSequences: ["asset reminder", "approval checkpoint", "delivery ready", "post-delivery check", "ongoing-control recommendation when recurring work is justified"],
      conversionPath: "Ongoing Control when ongoing monitoring, recurring changes, or market adaptation is valuable and evidence-supported.",
    },
    {
      key: "ongoing-control",
      name: "Ongoing Control / Monthly",
      trigger: "Customer starts monthly control after evidence supports recurring command, monitoring, or updates.",
      completionGoal: "Provide recurring review, forecasting, controlled recommendations, approval-gated updates, and retention value without uncontrolled automation.",
      stages: [
        { stage: "customer confirmation", artifact: "subscription active confirmation", owner: "customer-lifecycle-automation", gate: "subscription and ownership verified" },
        { stage: "safe intake", artifact: "monitoring scope and cadence", owner: "business-change-forecasting-scout", gate: "scope and notification preferences confirmed" },
        { stage: "evidence collection", artifact: "monthly evidence and change signal packet", owner: "analytics-and-growth-scout", gate: "privacy-safe signals only" },
        { stage: "truth separation", artifact: "trend, risk, assumption, and action map", owner: "chief-growth-forecast-agent", gate: "forecast uncertainty visible" },
        { stage: "agent work assignment", artifact: "monthly command queue", owner: "chief-growth-forecast-agent", gate: "no autonomous production change" },
        { stage: "production work", artifact: "monthly command summary and recommendations", owner: "business-change-forecasting-scout", gate: "recommendations evidence-backed" },
        { stage: "quality review", artifact: "monthly review packet", owner: "chief-report-truth-agent", gate: "no fake urgent alert" },
        { stage: "release-captain approval", artifact: "monthly release posture", owner: "release-captain", gate: "customer-facing summary approved" },
        { stage: "customer delivery", artifact: "monthly dashboard/report update", owner: "customer-journey-scout", gate: "clear approval path for any change" },
        { stage: "follow-up sequence", artifact: "retention and value proof sequence", owner: "analytics-and-growth-scout", gate: "value proof without guaranteed outcome" },
      ],
      requiredCustomerInputs: ["monitoring scope", "business priorities", "report cadence", "notification preferences", "approval contact", "risk threshold"],
      optionalCustomerInputs: ["monthly notes", "campaign changes", "competitor changes", "new offers", "approved performance summaries"],
      deliveryArtifacts: ["monthly command summary", "forecast and risk map", "approved recommendation queue", "controlled update request", "monthly email", "retention/value summary"],
      followUpSequences: ["monthly check-in", "change approval request", "risk alert when evidence-backed", "implemented update summary", "renewal/value proof"],
      conversionPath: "Expansion only when usage, evidence, and customer goals support additional scope.",
    },
  ],
  universalSafetyLocks: [
    "No plan asks for passwords, private keys, raw tokens, card numbers, bank details, or raw security payloads.",
    "No plan treats customer-provided claims as verified facts without supporting evidence.",
    "No plan uses fake urgency or pressure sequences.",
    "No plan guarantees revenue, ROI, ranking, traffic, security, or business outcome.",
    "No plan exposes raw payloads, raw evidence, provider payloads, internal notes, operator identities, secrets, or cross-customer data.",
    "No agent can approve delivery, launch, report release, customer-facing claims, provider settings, or production-impacting changes.",
    "Every production-impacting or customer-facing output routes through release-captain review and the relevant approval gate.",
  ],
  qualityBar: [
    "Every deliverable should be useful enough that the customer understands what changed, why it matters, what is proven, what is not proven, and what to do next.",
    "Every plan should feel premium, clear, calm, and high-conviction without pretending certainty beyond the evidence.",
    "Every plan should reduce customer confusion and route the customer to the next safe destination.",
    "Every plan should create a support/correction path so customer concerns do not become duplicate submissions or dead ends.",
  ],
} as const;

export function getCompletePlanFulfillmentMatrix() {
  return COMPLETE_PLAN_FULFILLMENT_MATRIX;
}
