export const COMPLETE_PLAN_FULFILLMENT_MATRIX = {
  id: "complete-plan-fulfillment-matrix",
  name: "Complete Cendorq Plan Fulfillment Matrix",
  purpose:
    "Define the complete A-to-Z fulfillment system for every Cendorq plan, from trigger and intake through research, production, quality review, delivery, follow-up, escalation, retention, and upgrade paths, while preserving truthful analysis, premium experience, conversion ethics, safe automation, plan-boundary protection, value above price, customer education, and release-captain approval.",
  universalStages: [
    "trigger",
    "customer confirmation",
    "safe intake",
    "evidence collection",
    "truth separation",
    "agent work assignment",
    "production work",
    "quality review",
    "release-captain approval",
    "customer delivery",
    "email notification",
    "dashboard update",
    "report vault update",
    "support path",
    "follow-up sequence",
    "upgrade or retention path",
    "audit and learning record",
  ],
  valueArchitecture: [
    "Each plan must deliver practical value that reasonably exceeds the price through clarity, evidence, prioritization, education, implementation usefulness, safer decisions, and a clear next move.",
    "Each plan must protect Cendorq revenue streams by delivering the promised scope fully without giving away higher-tier implementation, recurring control, or expanded research that belongs in another plan.",
    "Each plan must show the customer what they received, why it matters, what is proven, what remains uncertain, what is not included, and which next step is appropriate if they want deeper help.",
    "Value must be created through truthful diagnosis, customer education, premium presentation, useful artifacts, and plan-appropriate action—not through inflated claims or pressure.",
  ],
  educationalReportStandard: [
    "Assume most customers do not know the technical or strategic meaning of what the report finds.",
    "Every report section must explain the finding in plain language, why it matters to the business, what evidence supports it, what uncertainty remains, and what the customer can do next.",
    "Reports must teach customers the difference between symptoms, root causes, assumptions, evidence, risk, opportunity, and recommended action.",
    "Reports must show what Cendorq can help with without turning education into fear, pressure, or unsupported outcome promises.",
    "Reports must use business-appropriate conversion language based on the customer category, revenue model, buyer intent, trust gap, funnel stage, and evidence quality.",
  ],
  planBoundaryRules: [
    "Free Scan may educate and point to likely next steps, but must not include the full diagnostic depth, implementation plan, or recurring control reserved for paid plans.",
    "Deep Review may provide a full evidence-backed diagnosis and priority plan, but must not include done-for-you implementation that belongs to Build Fix.",
    "Build Fix may include scoped implementation support and delivery artifacts, but must not include unlimited monitoring or recurring market adaptation that belongs to Ongoing Control.",
    "Ongoing Control may include recurring review, forecasting, and approval-gated recommendations, but must not perform unapproved production changes or out-of-scope implementation without new scope approval.",
    "Upsell paths must be evidence-led and educational, not manipulative, fake-urgent, or based on unsupported fear.",
  ],
  conversionStandards: [
    "Conversion should come from customer understanding, proof, clear gaps, practical next steps, premium trust, and appropriate plan fit.",
    "Every plan must identify the business's likely conversion constraint using evidence: trust gap, clarity gap, offer gap, proof gap, action-path gap, market-positioning gap, or recurring-control gap.",
    "Recommendations must match the customer's business model, including local service, ecommerce, SaaS, creator, platform revenue, digital product, professional service, or hybrid model.",
    "Follow-up should show the consequence of inaction only when supported by evidence and phrased as risk or opportunity, not panic or guaranteed loss.",
    "Plan-fit language must make the customer feel understood, not pushed.",
  ],
  planMatrix: [
    {
      planKey: "free-scan",
      valuePromise: "A fast first read that helps the customer understand likely friction before paying for deeper work.",
      educationDepth: "Plain-language first-read education with limits, uncertainty, and next safe action visible.",
      planBoundary: "Does not include full diagnostic depth, implementation plan, or recurring monitoring.",
      conversionMethod: "Recommend Deep Review only when evidence or uncertainty justifies deeper diagnosis.",
    },
    {
      planKey: "deep-review",
      valuePromise: "A fuller diagnosis that turns evidence into priority, confidence, and next action clarity.",
      educationDepth: "Detailed education across facts, assumptions, inferences, limitations, blocker priority, and plan fit.",
      planBoundary: "Does not include done-for-you implementation or recurring monthly control.",
      conversionMethod: "Recommend Build Fix or Ongoing Control only when the evidence supports implementation or recurring monitoring.",
    },
    {
      planKey: "build-fix",
      valuePromise: "Scoped implementation support that turns a proven blocker into customer-approved work.",
      educationDepth: "Explains what changed, why it matters, what was approved, and what remains outside scope.",
      planBoundary: "Does not include unlimited monitoring, recurring adaptation, or unrelated implementation.",
      conversionMethod: "Recommend Ongoing Control when remaining risks need monitoring and review cadence.",
    },
    {
      planKey: "ongoing-control",
      valuePromise: "Recurring command, monitoring, review, and safe next actions as the market changes.",
      educationDepth: "Monthly education on progress, regressions, changes, limitations, and next priorities.",
      planBoundary: "Does not include unapproved implementation or out-of-scope production changes.",
      conversionMethod: "Recommend scoped Build Fix or Deep Review when recurring evidence shows a gap that needs focused work.",
    },
  ],
  universalSafetyLocks: [
    "No plan asks for passwords, private keys, raw tokens, card numbers, bank details, or raw security payloads.",
    "No plan treats customer-provided claims as verified facts without supporting evidence.",
    "No plan uses fake urgency or pressure sequences.",
    "No plan promises certain revenue, ROI, ranking, traffic, security, or business outcome.",
    "No plan exposes raw payloads, raw evidence, provider payloads, internal notes, operator identities, secrets, or cross-customer data.",
    "No agent can approve delivery, launch, report release, customer-facing claims, provider settings, or production-impacting changes.",
    "Every production-impacting or customer-facing output routes through release-captain review and the relevant approval gate.",
  ],
  qualityBar: [
    "Every deliverable should be useful enough that the customer understands what changed, why it matters, what is proven, what is not proven, and what to do next.",
    "Every plan should feel premium, clear, calm, and high-conviction without pretending certainty beyond the evidence.",
    "Every plan should reduce customer confusion and route the customer to the next safe destination.",
    "Every plan should create a support/correction path so customer concerns do not become duplicate submissions or dead ends.",
    "Every plan should provide more practical clarity, educational value, and decision usefulness than the customer expects from the price paid.",
    "Every plan should protect the next appropriate revenue stream by clearly explaining what is included, what is not included, and what higher-tier help would add.",
  ],
} as const;

export function getCompletePlanFulfillmentMatrix() {
  return COMPLETE_PLAN_FULFILLMENT_MATRIX;
}
