export const CONTROLLED_CONTINUOUS_EVOLUTION_CONTRACT = {
  id: "controlled-continuous-evolution-v1",
  name: "Controlled continuous evolution standard",
  purpose:
    "Keep Cendorq improving after launch through monitored, validated, reviewable, reversible updates without uncontrolled production mutation or quality drift.",
  operatingMode:
    "Automated systems may detect, propose, test, and prepare updates. Production-impacting changes require validation gates, reviewable diffs, deploy checks, rollback readiness, and explicit promotion.",
  updateStreams: [
    "dependency-health",
    "security-scanning",
    "framework-runtime-updates",
    "accessibility-and-ux-regression",
    "performance-and-core-web-vitals",
    "conversion-copy-quality",
    "legal-liability-language",
    "report-truthfulness-and-citation-quality",
    "customer-support-lifecycle",
    "operator-command-center-safety",
    "billing-and-plan-integrity",
    "internationalization-readiness",
    "mobile-app-readiness",
  ],
  scheduledCadence: [
    "daily dependency and vulnerability detection",
    "daily build and route validation on proposed updates",
    "weekly interface quality and accessibility review",
    "weekly dashboard and conversion-path review",
    "weekly command-center safety review",
    "monthly legal/liability language review",
    "monthly report-truthfulness methodology review",
    "quarterly platform architecture and scalability review",
  ],
  allowedAutomation: [
    "open dependency update pull requests",
    "open security remediation pull requests",
    "run validation scripts",
    "run build, typecheck, lint, and route checks",
    "run smoke checks against preview deployments",
    "compare performance/accessibility budgets",
    "draft changelog entries",
    "flag drift from platform interface excellence standards",
  ],
  blockedAutomation: [
    "auto-merge production-impacting code without green gates",
    "auto-deploy unreviewed risky mutations",
    "disable validation to make updates pass",
    "weaken customer/session/support/admin guardrails",
    "rewrite legal, pricing, refund, billing, security, or report claims without approval",
    "store or expose raw payloads, internal notes, secrets, customer data, or protected context",
    "self-modify agent instructions or bypass controlled intelligence rules",
  ],
  requiredGates: [
    "pull request with reviewable diff",
    "validation scripts pass",
    "build passes",
    "typecheck passes when available",
    "lint passes when available",
    "Vercel preview or deployment check passes",
    "no blocked pattern introduced",
    "rollback path identified",
    "customer-facing copy remains truthful and non-deceptive",
    "operator/admin mutations remain gated and audited",
  ],
  releasePosture: [
    "small coherent batches",
    "preview before production",
    "canary where available",
    "monitor after merge",
    "rollback-ready before promotion",
    "document what changed and why",
    "do not hide failures or silently weaken safeguards",
  ],
  monitoringSignals: [
    "dependency advisories",
    "code scanning alerts",
    "build failures",
    "route validation failures",
    "smoke test failures",
    "accessibility regressions",
    "performance regressions",
    "conversion funnel anomalies",
    "support request spikes",
    "billing error spikes",
    "security-sensitive submission spikes",
    "customer dashboard drop-off",
    "report correction requests",
  ],
  qualityBar:
    "Continuous updates must raise or preserve Cendorq's most-pristine standard. Any update that reduces trust, clarity, protection, accessibility, performance, truthful analysis, customer control, or operator safety must be held, redesigned, or rejected.",
} as const;

export const CONTROLLED_CONTINUOUS_EVOLUTION_RUNBOOK = [
  "Detect update need from dependency, security, performance, accessibility, UX, customer, operator, or market signal.",
  "Create a small coherent branch from latest main.",
  "Apply only the minimum safe change for that update stream.",
  "Add or extend validation that prevents regression of the same class.",
  "Run build, validation, preview, and smoke gates.",
  "Open a PR with clear summary and validation evidence.",
  "Merge only after green checks and mergeability.",
  "Monitor post-merge signals and prepare rollback if needed.",
] as const;

export const CONTROLLED_CONTINUOUS_EVOLUTION_HARD_LOCKS = [
  "automatic update systems can propose changes but cannot bypass validation",
  "dependency updates must be reviewed as code changes, not trusted blindly",
  "security fixes must not weaken customer-visible truth, billing clarity, or legal-safe language",
  "interface updates must preserve the platform interface excellence contract",
  "report-methodology updates must preserve fact/inference/recommendation separation",
  "operator-console updates must preserve read/write separation and safe projections",
  "rollback must be possible before high-impact promotion",
  "all scheduled updates must remain coherent, bounded, and traceable",
] as const;

export const CONTROLLED_CONTINUOUS_EVOLUTION_BLOCKED_PATTERNS = [
  "autoMergeWithoutValidation",
  "skipVercelGate",
  "disableValidatorForUpdate",
  "unreviewedProductionMutation",
  "weakenGuardrailsForConvenience",
  "storeRawPayloadForDebugging",
  "exposeInternalNotesForSupport",
  "allowPromptOverride",
  "bypassCustomerOwnership",
  "bypassReauth",
  "deleteAuditRecordsToCleanUp",
] as const;
