export const CORE_INFORMATION_PROTECTION_CONTRACT = {
  id: "core-information-protection-v1",
  name: "Core information protection standard",
  purpose:
    "Reduce the risk of customer, company, support, billing, report, operator, and platform information exposure through least privilege, server-side ownership checks, data minimization, safe projections, validation, and containment-ready design.",
  operatingStandard:
    "Cendorq must never treat customer or company information as casual data. Every route, API, workflow, report, notification, support action, billing surface, operator tool, and background process must minimize, protect, validate, and safely project information by default.",
  appliesTo: [
    "public-forms",
    "free-scan-intake",
    "signup-and-verification",
    "customer-session-runtime",
    "customer-dashboard",
    "report-generation-and-vault",
    "billing-and-plan-state",
    "notification-center",
    "support-request-and-status",
    "support-lifecycle-communications",
    "operator-command-center",
    "admin-support-console",
    "file-backed-storage",
    "email-queue-contracts",
    "continuous-update-automation",
  ],
  dataMinimizationRules: [
    "collect only the fields needed for the stated customer workflow",
    "store safe summaries instead of raw sensitive submissions whenever possible",
    "never store raw rejected prompt-injection or credential-like content in customer-visible records",
    "avoid duplicating sensitive customer data across queues, logs, notifications, emails, analytics, and UI state",
    "use hashes or references for customer identity where practical",
    "never add sensitive fields to public JavaScript or static HTML",
  ],
  accessControlRules: [
    "customer-owned data must require server-side customer ownership checks",
    "verified-email checks are required for protected customer support and dashboard APIs",
    "operator access must require role, gate, fresh reauthentication where applicable, and safe projection",
    "admin/support reads and writes must remain separated from customer-facing projections",
    "state-changing APIs require guarded server-side validation, origin checks where appropriate, and safe failures",
    "authorization failures must avoid account-existence leakage",
  ],
  projectionRules: [
    "customer surfaces receive safe projections only",
    "operator history views remain bounded and projection-only",
    "support status cannot expose raw payloads, raw evidence, private notes, operator identities, attacker details, or risk internals",
    "notifications and emails use contract keys and safe copy rather than raw support content",
    "reports separate verified facts, assumptions, inferences, recommendations, and limitations",
  ],
  browserProtectionRules: [
    "no session tokens in localStorage, sessionStorage, URLs, analytics payloads, public JavaScript, HTML, emails, or customer copy",
    "no support context secrets, admin keys, CSRF tokens, reauth tokens, or protected headers in public browser code",
    "cookies carrying auth/session material must be secure, httpOnly where applicable, same-site scoped, and server-validated",
    "client state may hold presentation state but not protected authority",
    "concierge prompts and public UI hints may store dismissal preferences but not protected customer records",
  ],
  storageAndLoggingRules: [
    "no raw payload logging for customer submissions",
    "no payment data, credentials, secrets, prompt injections, or private evidence in logs",
    "audit records must preserve proof without exposing customer secrets or unnecessary sensitive data",
    "debug records must be bounded, sanitized, and safe to retain",
    "do not delete required audit records to hide failures or clean up evidence",
  ],
  lifecycleAndContainmentRules: [
    "validate every new information flow before merge",
    "prefer explicit allowlists over broad pass-through",
    "hold or suppress communications when ownership, verified session, safe projection, or channel guards are missing",
    "ship rollback-ready changes with clear deployment gates",
    "treat suspicious submissions as hostile input until sanitized and safely classified",
    "design for rapid containment, revocation, rotation, and customer-safe disclosure if a protected path fails",
  ],
  maintenanceRules: [
    "automated checks may detect and propose fixes but cannot weaken protection rules",
    "dependency and workflow updates must preserve validation, ownership, projection, and no-secret-browser rules",
    "near-zero routine maintenance must be achieved through validated automation, not blind auto-change",
    "high-impact production changes require green gates and reviewable diffs",
  ],
  truthBoundary:
    "No system can honestly promise impossible-to-steal or impossible-to-hack. Cendorq's standard is strong risk reduction, least exposure, rapid detection, safe containment, and validation-backed protection at every layer.",
} as const;

export const CORE_INFORMATION_PROTECTION_HARD_LOCKS = [
  "no browser authority for protected customer, support, billing, report, operator, or admin data",
  "no raw sensitive support content in customer projections",
  "no cross-customer data path without server-side ownership checks",
  "no protected route without safe failure behavior",
  "no queue, email, notification, or report record that stores unnecessary sensitive data",
  "no operator surface that exposes private internals to customer-facing views",
  "no maintenance automation that weakens validation or guardrails",
  "no claim that Cendorq is impossible to hack or impossible to breach",
] as const;

export const CORE_INFORMATION_PROTECTION_BLOCKED_PATTERNS = [
  "rawPayloadCustomerVisible",
  "rawEvidenceCustomerVisible",
  "rawSecurityPayloadCustomerVisible",
  "rawBillingDataCustomerVisible",
  "internalNotesCustomerVisible",
  "operatorIdentityCustomerVisible",
  "riskScoringInternalsCustomerVisible",
  "attackerDetailsCustomerVisible",
  "bypassCustomerOwnership",
  "skipVerifiedEmailForProtectedApi",
  "exposeSupportAdminKey",
  "exposeCustomerSupportContextKey",
  "deleteAuditRecordsToCleanUp",
  "impossible to hack",
  "impossible to steal",
  "never breached",
  "zero risk",
] as const;
