export const CUSTOMER_EMAIL_CONFIRMATION_HANDOFF_CONTRACT = {
  id: "customer-email-confirmation-handoff-contract",
  name: "Cendorq Customer Email Confirmation and Report Access Handoff Contract",
  senderIdentity: {
    fromName: "Cendorq Support",
    fromEmail: "support@cendorq.com",
    display: "Cendorq Support <support@cendorq.com>",
    checkInboxInstruction:
      "Check your inbox for an email from Cendorq Support <support@cendorq.com>. If you do not see it, check spam or promotions once, move Cendorq to your main inbox, and save support@cendorq.com as a trusted sender.",
  },
  recommendedSubjects: [
    {
      key: "free-scan-results",
      subject: "Confirm your email to open your Cendorq results",
      preheader: "Your private Free Scan results are ready after this one-time confirmation.",
      useWhen: "Free Scan intake has been submitted and report visibility is gated by email verification.",
    },
    {
      key: "dashboard-access",
      subject: "Confirm your email and enter your Cendorq command center",
      preheader: "One secure step opens your private dashboard and keeps future updates easier to find.",
      useWhen: "The customer needs account verification before accessing the dashboard, report vault, billing, support, or plan state.",
    },
    {
      key: "paid-plan-access",
      subject: "Confirm your email to continue your Cendorq plan",
      preheader: "Your plan workspace, status, and next actions are waiting in your private dashboard.",
      useWhen: "AI Readiness Review, Signal Repair, or Readiness Control intake or purchase requires verification before protected plan access.",
    },
  ],
  purpose:
    "Create the highest-converting verify-to-view flow for Free Scan and paid-plan customers: the customer confirms the signup email, strengthens future email engagement, and is routed back into the exact private dashboard, report result, report vault, billing document, or plan state they earned without showing protected results before verification.",
  operatingStandard: [
    "Use verification as a trust and access step, not as a dark pattern.",
    "After Free Scan or paid intake submission, show a calm check-your-inbox gate that names Cendorq Support <support@cendorq.com> instead of revealing protected report results before email verification.",
    "The primary confirmation CTA should combine the customer value and the security action: Confirm email and open your results.",
    "The confirmation click should verify the email server-side, consume the verification token once, mark inbox confirmation progress where appropriate, and route the customer to the correct protected dashboard destination.",
    "Free Scan customers should land on the dedicated Free Scan result page, not a generic report vault, when the result route is requested and safe.",
    "The confirmation flow should improve future email engagement through real customer interaction, but must never promise provider-level inbox placement or provider-level deliverability control.",
    "Report and billing PDF attachments may be sent after verification and release rules allow them, but the dashboard/report vault and billing center remain the canonical protected places to view current document state, next actions, and plan-fit guidance.",
  ],
  primaryCta: {
    label: "Confirm email and open your results",
    fallbackLabel: "Confirm email and open your dashboard",
    purpose:
      "Tie the customer's natural motivation to see scan or plan results to the required safety step of verifying the signup email.",
    allowedDestinations: ["/dashboard", "/dashboard/reports", "/dashboard/reports/free-scan", "/dashboard/notifications", "/dashboard/billing", "/free-check"],
  },
  journeyDestinations: [
    {
      key: "free-scan-submitted",
      customerMoment: "Customer submits Free Scan intake for the first time.",
      preVerificationScreen:
        "Check your inbox for Cendorq Support <support@cendorq.com>. Confirm your email to unlock your Free Scan result inside your Cendorq dashboard.",
      emailSubjectKey: "free-scan-results",
      emailCta: "Confirm email and open your Free Scan results",
      verifiedDestination: "/dashboard/reports/free-scan",
      dashboardModule: "Free Scan results plus action inbox",
      reportVisibilityRule:
        "Do not show Free Scan findings before email verification and safe release state. After verification, show the result on the dedicated Free Scan results page and send the report email or PDF only when release and document safety rules allow.",
    },
    {
      key: "ai-readiness-review-purchased-or-submitted",
      customerMoment: "Customer buys or submits AI Readiness Review intake.",
      preVerificationScreen:
        "Check your inbox for Cendorq Support <support@cendorq.com>. Confirm your email so Cendorq can protect your AI Readiness Review report, send status updates, and open your command center.",
      emailSubjectKey: "paid-plan-access",
      emailCta: "Confirm email and open your AI Readiness Review dashboard",
      verifiedDestination: "/dashboard/reports",
      dashboardModule: "report vault plus plan-scope guidance",
      reportVisibilityRule: "Show pending AI Readiness Review status until the report is released. Do not present pending analysis as final truth.",
    },
    {
      key: "signal-repair-purchased-or-submitted",
      customerMoment: "Customer buys or submits Signal Repair intake.",
      preVerificationScreen:
        "Check your inbox for Cendorq Support <support@cendorq.com>. Confirm your email so repair scope, approvals, and delivery notes stay connected to your command center.",
      emailSubjectKey: "paid-plan-access",
      emailCta: "Confirm email and open your Signal Repair workspace",
      verifiedDestination: "/dashboard",
      dashboardModule: "action inbox plus billing and support handoff",
      reportVisibilityRule:
        "Show Signal Repair scope, required approvals, and delivery status without exposing a standalone AI Readiness Review report unless AI Readiness Review entitlement exists.",
    },
    {
      key: "readiness-control-started",
      customerMoment: "Customer starts Readiness Control.",
      preVerificationScreen:
        "Check your inbox for Cendorq Support <support@cendorq.com>. Confirm your email so monthly command summaries, change alerts, and approval requests can reach you safely.",
      emailSubjectKey: "paid-plan-access",
      emailCta: "Confirm email and open your Readiness Control command center",
      verifiedDestination: "/dashboard/notifications",
      dashboardModule: "dashboard action inbox plus notification center",
      reportVisibilityRule: "Show monthly status and approved-scope summaries without delivering unpaid Signal Repair or standalone AI Readiness Review artifacts.",
    },
    {
      key: "support-or-billing-entry",
      customerMoment: "Customer enters through support, billing, invoice/receipt, or account recovery.",
      preVerificationScreen:
        "Check your inbox for Cendorq Support <support@cendorq.com>. Confirm your email so Cendorq can route you back to the right private account or billing area.",
      emailSubjectKey: "dashboard-access",
      emailCta: "Confirm email and return to your dashboard",
      verifiedDestination: "/dashboard",
      dashboardModule: "support, billing, document, or status recovery path",
      reportVisibilityRule: "Only show customer-owned safe projections. Do not reveal account existence, protected records, billing PDFs, or report PDFs before safe verification.",
    },
  ],
  dashboardDisplayRules: [
    "The customer command center is the canonical protected place to display current report state, report vault entries, next actions, plan scope, support status, document availability, and billing handoffs.",
    "Free Scan results should be available inside the dedicated dashboard Free Scan results route after verification and safe release state, with email used as a delivery and return channel.",
    "Full reports should have dedicated report-vault views for readability, evidence separation, visual sections, downloadable assets when allowed, and next-step conversion guidance.",
    "Billing documents should be available inside the billing center when provider state and customer ownership are verified, with email used as a receipt/invoice delivery and return channel.",
    "The dashboard should summarize the report and route into the dedicated report view rather than cramming every report detail into the dashboard home.",
    "Each report view should preserve the command-center feeling by showing the report, what it means, what is included, what is not included, confidence/limitations, and the next best plan when evidence supports it.",
  ],
  dashboardMessageMirrorRules: [
    "Every important customer email must create or update a matching dashboard message record so the customer can see the same safe communication inside the dashboard.",
    "Mirrored dashboard messages must include the email subject, safe summary, message category, sent status, related plan, related report or billing document, primary CTA, secondary safe path, and support route.",
    "Dashboard messages must never expose raw email provider payloads, raw report evidence, raw billing data, private prompts, exact scoring weights, secrets, tokens, or cross-customer data.",
    "When an email includes a safe PDF attachment, the mirrored dashboard message must show the same released document as a verified report-vault or billing-center document link.",
    "When an email cannot be delivered, bounces, is suppressed, or may be missed by the customer, the dashboard message remains visible after verified login and shows the safest next action.",
    "Email and dashboard message states must stay synchronized: queued, sent, delivered when known, opened when known, failed, suppressed, document ready, customer action needed, or archived.",
    "Dashboard messages supplement email and preserve access continuity; they do not replace transactional email, verification email, billing email, or lifecycle follow-up.",
  ],
  tokenAndSecurityRules: [
    "Verification tokens must be single-use, short-lived, server-validated, and never stored in localStorage or sessionStorage.",
    "Do not expose verification tokens, session tokens, CSRF tokens, admin keys, support context keys, or provider payloads in dashboard copy, report copy, analytics, attachments, PDF metadata, mirrored dashboard messages, or client-readable storage.",
    "After token consumption, issue the safe customer session through secure httpOnly cookies or the approved auth provider flow.",
    "If verification fails or expires, use a safe resend flow without revealing whether another account exists.",
    "Redirect only to allowlisted customer destinations and never to arbitrary URLs.",
  ],
  emailDeliverabilityRules: [
    "Cendorq email should be authenticated, aligned, and consistent: SPF, DKIM, and DMARC must be configured and monitored before live transactional sending.",
    "Use one recognizable sender identity for lifecycle trust: Cendorq Support <support@cendorq.com> unless a release-captain-approved billing sender is required by the provider.",
    "Verification, report, billing, and lifecycle emails should be transactional, useful, recognizable, low-link-density, mobile-readable, and connected to the dashboard or billing center.",
    "The check-your-inbox screen must name support@cendorq.com so the customer knows exactly which sender to find and trust.",
    "Ask the customer to move Cendorq to the main inbox or save the sender only as a helpful instruction, not as a guarantee.",
    "The verification click should count as engagement and help future Cendorq emails be easier to find, but copy must not claim promised placement.",
    "Lifecycle and follow-up emails to the signup address remain active after dashboard action inbox setup; dashboard inbox supplements email and does not replace it.",
    "If an email is routed to spam, the customer must still be able to access the same released report, billing document, or customer message from the verified dashboard/report vault/billing center after safe login.",
    "Deliverability monitoring must watch bounces, complaints, suppressions, unsubscribes where applicable, authentication errors, and attachment-related failures before scaling volume.",
  ],
  pdfAttachmentRules: [
    "Report PDFs and billing PDFs are allowed when they help the customer preserve the result, invoice, receipt, or payment confirmation, but they must never be the only access path.",
    "Attach report PDFs only after verified email, customer ownership, entitlement or permitted Free Scan access, release-captain approval, no-leak check, and document-safety checks pass.",
    "Attach billing PDFs only from provider-authoritative invoice, receipt, or payment confirmation records after verified customer ownership and safe billing projection checks pass.",
    "If attachment safety, deliverability risk, release state, or provider state is uncertain, send a dashboard/report-vault/billing-center link first and attach the PDF only after the gate passes.",
    "PDF attachments must be static PDF documents only; no executable content, macros, embedded scripts, hidden payloads, raw provider payloads, raw report evidence, private prompts, exact scoring weights, secrets, tokens, or cross-customer data.",
    "PDF filenames must be safe and recognizable, using Cendorq, document type, plan or billing event, date, and a non-sensitive customer or business reference.",
    "Attachment emails must explain why the PDF is attached, identify the plan/report/billing event, and include a dashboard or billing-center verification path.",
  ],
  blockedPatterns: [
    "showReportBeforeEmailVerification",
    "emailVerificationDarkPattern",
    "verificationWithoutSenderIdentity",
    "verificationWithoutReportDestination",
    "verificationWithoutDashboardReturn",
    "verificationTokenInLocalStorage",
    "verificationTokenInSessionStorage",
    "arbitraryRedirectAfterVerification",
    "accountExistenceLeakage",
    "reportAttachmentBeforeSafeRelease",
    "billingAttachmentBeforeProviderAuthority",
    "pdfAttachmentAsOnlyAccessPath",
    "pdfAttachmentWithoutVerifiedEmail",
    "pdfAttachmentWithoutNoLeakCheck",
    "dashboardMessageMirrorMissing",
    "dashboardMessageMirrorRawPayload",
    "dashboardMessageMirrorRawEvidence",
    "dashboardMessageMirrorRawBillingData",
    "dashboardMessageDriftFromEmail",
    "macroEnabledPdfAttachment",
    "executableAttachment",
    "embeddedScriptAttachment",
    "pendingReportPresentedAsFinal",
    "dashboardInboxReplacesEmailOrchestration",
    "promisedInboxPlacement",
    "promisedDeliverability",
    "rawPayloadBeforeVerification",
    "rawEvidenceBeforeVerification",
    "rawBillingDataBeforeVerification",
    "internalNotesBeforeVerification",
    "operatorIdentityBeforeVerification",
    "riskInternalsBeforeVerification",
    "secretBeforeVerification",
    "sessionTokenBeforeVerification",
    "csrfTokenBeforeVerification",
    "adminKeyBeforeVerification",
    "supportContextKeyBeforeVerification",
    "unsupportedOutcomePromise",
    "fakeUrgencyVerification",
  ],
  releaseRules: [
    "Every intake completion path must define a pre-verification screen, verification email CTA, sender identity, verified destination, dashboard module, and report visibility rule.",
    "Every report display path must keep dashboard summary, report-vault detail, email delivery, PDF delivery when enabled, dashboard message mirror, and plan next step synchronized.",
    "Every billing document path must keep billing center, provider-authoritative record, email delivery, PDF delivery when enabled, dashboard message mirror, and support recovery synchronized.",
    "Every important lifecycle email must have a mirrored dashboard message so the customer can access the same safe message after verified login.",
    "Every confirmation email must route to the customer-owned dashboard destination after verification, not to a generic dead end.",
    "Free Scan verification must route to the dedicated dashboard Free Scan results page when the intake requests that destination.",
    "Release-captain review must reject verification flows that reveal protected results before verification, omit support@cendorq.com from the check-your-inbox instruction, replace lifecycle email orchestration with dashboard-only messaging, promise inbox placement, attach unsafe PDFs, or fail to mirror important customer messages in the dashboard.",
  ],
} as const;

export function getCustomerEmailConfirmationHandoffContract() {
  return CUSTOMER_EMAIL_CONFIRMATION_HANDOFF_CONTRACT;
}
