export const LAUNCH_EVIDENCE_PERSISTENCE_CONTRACT = {
  id: "launch-evidence-persistence-contract",
  name: "Launch Evidence Persistence Contract",
  purpose:
    "Define append-only launch evidence records for owner configuration, production smoke, rollback, audit, and hard-lock clearance without exposing protected internals or creating public launch claims.",
  evidenceTypes: [
    {
      key: "owner-configuration-evidence",
      label: "Owner configuration evidence",
      purpose: "Records owner-approved auth, payment mapping, protected config, launch contact, and support identity evidence.",
      requiredSafeFields: ["evidenceId", "evidenceType", "ownerApprovalStatus", "configurationArea", "recordedAt", "recordedByRole", "safeSummary", "auditId"],
    },
    {
      key: "production-smoke-evidence",
      label: "Production smoke evidence",
      purpose: "Records production smoke target, public route checks, protected denial checks, command center closed posture, and no production mutation posture.",
      requiredSafeFields: ["evidenceId", "evidenceType", "smokeTargetStatus", "checkedRouteGroup", "recordedAt", "recordedByRole", "safeSummary", "auditId"],
    },
    {
      key: "rollback-evidence",
      label: "Rollback evidence",
      purpose: "Records rollback plan evidence for auth, billing, reports, support, public conversion, and maintenance.",
      requiredSafeFields: ["evidenceId", "evidenceType", "rollbackArea", "rollbackStatus", "recordedAt", "recordedByRole", "safeSummary", "auditId"],
    },
    {
      key: "audit-evidence",
      label: "Audit evidence",
      purpose: "Records audit path evidence for auth, billing, report release, support, operator actions, and maintenance.",
      requiredSafeFields: ["evidenceId", "evidenceType", "auditArea", "auditStatus", "recordedAt", "recordedByRole", "safeSummary", "auditId"],
    },
    {
      key: "hard-lock-clearance-evidence",
      label: "Hard-lock clearance evidence",
      purpose: "Records safe proof that launch hard locks are cleared or still blocked without revealing private internals.",
      requiredSafeFields: ["evidenceId", "evidenceType", "hardLockKey", "clearanceStatus", "recordedAt", "recordedByRole", "safeSummary", "auditId"],
    },
  ],
  persistenceRules: [
    "Launch evidence records must be append-only.",
    "Launch evidence records must preserve audit proof and must not claim required audit records are deleted.",
    "Launch evidence records must be operator-only and never customer-facing.",
    "Launch evidence records may unlock operator review state only through safe projection and must not mutate production state.",
    "Launch evidence records must be tied to a launch readiness blocker or checklist item.",
    "Launch evidence records must use generic safe failure when access, storage, or evidence validation fails.",
  ],
  safeProjectionFields: [
    "evidenceId",
    "evidenceType",
    "status",
    "safeSummary",
    "blockerKey",
    "checklistKey",
    "recordedAt",
    "recordedByRole",
    "auditId",
    "sourceRoute",
    "requestIdHash",
  ],
  blockedProjectionFields: [
    "rawSourceEvidence",
    "rawPayload",
    "rawEvidence",
    "rawSecurityPayload",
    "rawBillingData",
    "protectedProviderDetail",
    "operatorPrivateIdentity",
    "operatorEmail",
    "operatorIp",
    "privateCustomerData",
    "internalNotes",
    "internalRiskModel",
    "privilegedConfigValue",
    "privateCredentialMaterial",
    "privateAuditPayload",
    "systemPrompt",
    "developerPrompt",
    "sessionAuthority",
    "adminAuthority",
    "supportContextAuthority",
    "crossCustomerData",
  ],
  releaseRules: [
    "Do not treat missing evidence as launch-ready.",
    "Do not treat pending evidence as complete evidence.",
    "Do not allow public launch, paid launch, report launch, or security readiness claims from evidence records alone.",
    "Do not expose evidence persistence records through customer routes, customer emails, notifications, support pages, billing center, report vault, public pages, or crawlers.",
    "Do not allow evidence record deletion, rewrite, hidden overwrite, or production mutation from evidence persistence paths.",
  ],
} as const;

export const LAUNCH_EVIDENCE_PERSISTENCE_BLOCKED_PATTERNS = [
  "evidenceDeletion",
  "evidenceRewrite",
  "hiddenEvidenceOverwrite",
  "customerFacingEvidenceProjection",
  "publicEvidenceProjection",
  "missingEvidenceLaunchReady",
  "pendingEvidenceComplete",
  "evidenceOnlyPublicLaunchClaim",
  "evidenceOnlyPaidLaunchClaim",
  "evidenceOnlyReportLaunchClaim",
  "absoluteSecurityEvidenceClaim",
  "productionMutationFromEvidencePath",
  "rawSourceEvidenceProjection",
  "protectedProviderDetailProjection",
  "operatorPrivateIdentityProjection",
  "privateCustomerDataProjection",
  "internalRiskModelProjection",
  "privilegedConfigValueProjection",
  "privateCredentialMaterialProjection",
  "privateAuditPayloadProjection",
  "crossCustomerDataProjection",
] as const;

export function getLaunchEvidencePersistenceContract() {
  return LAUNCH_EVIDENCE_PERSISTENCE_CONTRACT;
}
