import {
  PLAN_VALUE_FULFILLMENT_BOUNDARIES,
  PLAN_VALUE_FULFILLMENT_RULES,
  projectPlanValueFulfillment,
} from "@/lib/plan-value-fulfillment-boundaries";

export const PLAN_DELIVERY_ORCHESTRATION_CONTRACT = {
  id: "plan-delivery-orchestration-contract",
  name: "Cendorq Plan Delivery Orchestration Contract",
  purpose:
    "Define the end-to-end delivery orchestration standard for every Cendorq plan so intake, evidence, report creation, email delivery, follow-up, agent ownership, customer handoffs, upgrade paths, and fulfillment boundaries stay truthful, synchronized, exceptional, and non-overlapping.",
  fulfillmentBoundaryStandard: PLAN_VALUE_FULFILLMENT_RULES,
  fulfillmentBoundaries: PLAN_VALUE_FULFILLMENT_BOUNDARIES,
  fulfillmentProjections: [
    projectPlanValueFulfillment("free-scan"),
    projectPlanValueFulfillment("deep-review"),
    projectPlanValueFulfillment("build-fix"),
    projectPlanValueFulfillment("ongoing-control"),
  ],
  operatingStandard: [
    "Every plan must define intake, evidence requirements, customer deliverables, operator deliverables, email lifecycle, notification lifecycle, follow-up lifecycle, agent ownership, handoff destinations, and release-captain approval gates.",
    "Every plan must define allowed deliverables, blocked overlaps, required-before-delivery checks, approval gate, customer-facing summary, and escalation rule.",
    "Every report and customer-facing deliverable must separate verified facts, customer-provided context, external evidence, assumptions, inferences, limitations, confidence, and next actions.",
    "Every plan must deliver value beyond generic advice by converting evidence into practical actions, clear priorities, safer decisions, and plan-appropriate implementation support.",
    "Every plan must avoid fake urgency, unsupported ROI claims, certain-revenue language, certain-accuracy language, absolute security, and liability-shield language.",
    "Every plan must preserve customer privacy, safe projection, no raw payload exposure, and no cross-customer data exposure.",
  ],
  planLifecycles: [
    {
      key: "free-scan",
      name: "Free Scan",
      fulfillmentBoundary: projectPlanValueFulfillment("free-scan"),
      customerPromise: "Provide a safe first read and useful direction without pretending the scan is a final complete diagnosis.",
      intake: ["guided free-check form", "business basics", "market context", "offer and buyer", "problem pressure"],
      requiredEvidence: ["customer-provided context", "owned business surface review", "safe public signals when available", "clear limitations when evidence is incomplete"],
      deliverables: ["protected dashboard Free Scan result", "first visible signal summary", "confidence posture", "evidence boundary", "visible limitations", "best next move guidance"],
      blockedOverlap: ["full diagnostic report", "implementation-ready work order", "monthly monitoring summary", "unlimited recommendations", "private investigation output"],
      emailLifecycle: ["scan received", "report ready", "safe next step", "non-pressure follow-up if no upgrade"],
      followUpLifecycle: ["report opened check", "helpful clarification prompt", "deep-review recommendation only when evidence supports deeper diagnosis", "support path if customer disputes context"],
      agentOwnership: ["chief-report-truth-agent", "report-truth-research-scout", "customer-journey-scout", "conversion-luxury-ui-scout"],
      approvalGate: "free-scan-safe-result-release",
    },
    {
      key: "deep-review",
      name: "Deep Review",
      fulfillmentBoundary: projectPlanValueFulfillment("deep-review"),
      customerPromise: "Deliver evidence-backed diagnosis, cause-level clarity, and prioritized decision guidance without representing implementation work as included.",
      intake: ["payment confirmation", "verified customer ownership", "free scan handoff", "expanded diagnostic questionnaire", "business goals", "current funnel", "customer objections", "available access details without secrets"],
      requiredEvidence: ["free scan evidence", "customer-provided expanded context", "website and owned-surface review", "safe public market signals", "competitor/comparison context", "evidence conflict review"],
      deliverables: ["diagnostic report", "evidence-backed cause analysis", "priority blocker map", "confidence-labeled findings", "fix direction and plan-fit recommendation"],
      blockedOverlap: ["done-for-you implementation", "unlimited revisions", "monthly monitoring loop", "ad spend management", "guaranteed revenue claim"],
      emailLifecycle: ["purchase received", "expanded intake request", "analysis in progress", "report ready", "follow-up clarification", "next-step recommendation"],
      followUpLifecycle: ["intake completion reminder", "report review guidance", "question/correction path", "build-fix or ongoing-control recommendation only with supporting evidence"],
      agentOwnership: ["chief-report-truth-agent", "evidence-conflict-scout", "industry-context-scout", "report-design-quality-scout"],
      approvalGate: "deep-review-report-release",
    },
    {
      key: "build-fix",
      name: "Build Fix",
      fulfillmentBoundary: projectPlanValueFulfillment("build-fix"),
      customerPromise: "Turn a clear weakness into scoped customer-facing improvement work while preserving evidence, approvals, scope clarity, and measurable but non-guaranteed outcome posture.",
      intake: ["payment confirmation", "scope confirmation", "asset/request checklist", "brand context", "page or funnel targets", "implementation constraints", "approval contact", "safe access instructions without secrets"],
      requiredEvidence: ["deep review or supported diagnosis", "owned-surface evidence", "customer goals", "implementation constraints", "before-change snapshot", "approval and rollback posture"],
      deliverables: ["scoped implementation intake", "fix target confirmation", "customer-facing improvement work", "before-after delivery summary", "approval checkpoint and support handoff"],
      blockedOverlap: ["full diagnostic report unless purchased separately", "unlimited site rebuild", "monthly monitoring loop", "unapproved production changes", "guaranteed revenue claim"],
      emailLifecycle: ["purchase received", "scope and asset request", "work started", "approval checkpoint", "delivery ready", "post-delivery follow-up"],
      followUpLifecycle: ["missing asset reminder", "approval reminder", "delivery review", "implementation support guidance", "ongoing-control recommendation when recurring monitoring is justified"],
      agentOwnership: ["chief-product-experience-agent", "conversion-luxury-ui-scout", "report-design-quality-scout", "chief-security-command-agent"],
      approvalGate: "build-fix-customer-output-approval",
    },
    {
      key: "ongoing-control",
      name: "Ongoing Control",
      fulfillmentBoundary: projectPlanValueFulfillment("ongoing-control"),
      customerPromise: "Provide recurring monitoring, monthly priorities, status awareness, and decision support without implying unlimited implementation or guaranteed placement.",
      intake: ["subscription confirmation", "monitoring scope", "business priorities", "report cadence", "safe notification preferences", "change approval contact", "risk threshold"],
      requiredEvidence: ["previous reports", "safe aggregate trend signals", "customer-approved monitoring scope", "market and platform change signals", "monthly review records", "change approval history"],
      deliverables: ["monthly priority selection", "recurring review cycle", "dashboard status and alerts", "trend-aware summaries", "monthly decision support"],
      blockedOverlap: ["unlimited Build Fix implementation", "standalone Deep Review every month unless scoped", "ad spend management", "guaranteed ranking", "guaranteed AI answer placement"],
      emailLifecycle: ["subscription active", "monthly review started", "monthly report ready", "urgent-but-non-fake alert when risk is evidence-backed", "renewal/value summary"],
      followUpLifecycle: ["monthly check-in", "change approval request", "implemented update summary", "risk forecast alert", "plan adjustment recommendation"],
      agentOwnership: ["chief-growth-forecast-agent", "business-change-forecasting-scout", "analytics-and-growth-scout", "chief-report-truth-agent"],
      approvalGate: "ongoing-control-monthly-review-gate",
    },
  ],
  crossPlanRules: [
    "Free Scan follow-up must be useful and calm, not pressure-based.",
    "Paid-plan recommendations must be evidence-supported and plan-fit labeled.",
    "Deep Review may ask additional questions after payment when more detail improves accuracy, but must not request passwords, tokens, private keys, card numbers, bank details, or raw security payloads.",
    "Build Fix must define concrete scope, required customer assets, approval checkpoints, and rollback/revision posture before delivery claims.",
    "Ongoing Control must use controlled monitoring and approval gates, not unapproved production changes, autonomous business changes, unlimited implementation, or guaranteed placement claims.",
    "All plan emails must preserve truthful status, privacy, safe next action, no fake urgency, and plan value boundaries.",
    "All plan follow-ups must connect to dashboard, report vault, notifications, support, billing, and plan paths without customer journey dead ends.",
    "All agent-produced plan work returns to release-captain review before becoming customer-facing output.",
  ],
  blockedPatterns: [
    "planWithoutIntake",
    "planWithoutEvidence",
    "planWithoutReportOrDeliverable",
    "planWithoutEmailLifecycle",
    "planWithoutFollowUp",
    "planWithoutAgentOwner",
    "planWithoutApprovalGate",
    "planWithoutFulfillmentBoundary",
    "freeScanPresentedAsFinalCompleteDiagnosis",
    "freeScanDeliveringImplementation",
    "freeScanDeliveringMonthlyMonitoring",
    "deepReviewDeliveringImplementationWithoutBuildFix",
    "buildFixDeliveringUnlimitedImplementation",
    "buildFixDeliveringRecurringMonitoring",
    "ongoingControlDeliveringUnlimitedBuildFix",
    "ongoingControlGuaranteedRankingOrPlacement",
    "customerClaimTreatedAsVerifiedFact",
    "paidRecommendationWithoutEvidence",
    "optimizationWithoutScopeApproval",
    "monthlyControlWithoutApprovalGate",
    "uncontrolledAgentPlanDelivery",
    "rawPayloadPlanDelivery",
    "rawEvidencePlanDelivery",
    "privateCredentialPlanDelivery",
    "paymentDataPlanDelivery",
    "crossCustomerPlanDelivery",
    "fakeUrgencyPlanFollowUp",
    "guaranteedOutcomePlanClaim",
    "guaranteedRevenuePlanClaim",
    "guaranteedAccuracyPlanClaim",
  ],
  releaseRules: [
    "No plan lifecycle can be considered complete until intake, evidence, delivery, email, follow-up, agent ownership, approval gates, and fulfillment boundaries are represented.",
    "No customer-facing plan output can bypass report evidence records, customer output approval, fulfillment boundary checks, or release-captain review where applicable.",
    "No implementation or optimization work can be represented as complete without scope clarity, customer approval posture, and safe delivery summary.",
    "No monthly or ongoing control action can mutate customer-facing production surfaces without approval gates and audit-safe records.",
  ],
} as const;

export function getPlanDeliveryOrchestrationContract() {
  return PLAN_DELIVERY_ORCHESTRATION_CONTRACT;
}
