import {
  PLAN_VALUE_FULFILLMENT_BOUNDARIES,
  PLAN_VALUE_FULFILLMENT_RULES,
  projectPlanValueFulfillment,
} from "@/lib/plan-value-fulfillment-boundaries";
import {
  PLAN_INTELLIGENCE_ACQUISITION_RULES,
  PLAN_INTELLIGENCE_ACQUISITION_SYSTEM,
  projectPlanIntelligenceAcquisition,
} from "@/lib/plan-intelligence-acquisition-system";

export const PLAN_DELIVERY_ORCHESTRATION_CONTRACT = {
  id: "plan-delivery-orchestration-contract",
  name: "Cendorq Plan Delivery Orchestration Contract",
  purpose:
    "Define the end-to-end delivery orchestration standard for every Cendorq plan so intelligence acquisition, checkout fulfillment, entitlement, intake, evidence, report creation, report release, email delivery, dashboard retargeting, follow-up, continuous nurturing, agent ownership, customer handoffs, upgrade paths, retention paths, future feature adoption, and fulfillment boundaries stay truthful, synchronized, category-defining, and non-overlapping.",
  businessOperatingPhilosophy: [
    "Every surface must think in stage, proof, psychology, next action, and long-term value.",
    "Every customer touch should answer: what happened, why it matters, what is next, what is known, what is unknown, and why this stage fits.",
    "Every page, dashboard card, email, report, support path, billing state, checkout state, backend trigger, and operator queue must feel like one command system, not disconnected tools.",
    "Every recommendation must protect reputation before revenue: sell strongly when the proof supports it, reduce confidence when evidence is thin, and never manufacture certainty.",
    "Every lifecycle action should move the customer forward only when it is useful, stage-fit, and safe; otherwise it should educate, clarify, or preserve trust.",
  ],
  intelligenceAcquisitionStandard: PLAN_INTELLIGENCE_ACQUISITION_RULES,
  intelligenceAcquisitionContracts: PLAN_INTELLIGENCE_ACQUISITION_SYSTEM,
  intelligenceAcquisitionProjections: [
    projectPlanIntelligenceAcquisition("free-scan"),
    projectPlanIntelligenceAcquisition("deep-review"),
    projectPlanIntelligenceAcquisition("build-fix"),
    projectPlanIntelligenceAcquisition("ongoing-control"),
  ],
  fulfillmentBoundaryStandard: PLAN_VALUE_FULFILLMENT_RULES,
  fulfillmentBoundaries: PLAN_VALUE_FULFILLMENT_BOUNDARIES,
  fulfillmentProjections: [
    projectPlanValueFulfillment("free-scan"),
    projectPlanValueFulfillment("deep-review"),
    projectPlanValueFulfillment("build-fix"),
    projectPlanValueFulfillment("ongoing-control"),
  ],
  reportPresentationStandard: [
    "Every customer-facing result must look like a Cendorq category-defining business document, not a generic generated report.",
    "Every report/result must include the Cendorq logo or wordmark, report type, plan name, business identity, generated date, methodology version, release status, confidence legend, and support/correction path.",
    "Every report/result must separate verified facts, customer-provided context, observed public evidence, assumptions, inferences, limitations, contradictions, forecast direction, recommendations, next actions, and refresh triggers.",
    "Every report/result must show one strongest next action and one secondary safe path, not a crowded CTA wall.",
    "Every paid report/result must include a plain-English executive command summary, evidence map, priority map, what Cendorq checked, what Cendorq could not verify, what changed or should be watched, and why the next plan stage may or may not fit.",
    "Forecast, movement, competitor, and recurring-control sections may appear only when evidence supports them and must include confidence, assumptions, time horizon, what would change the forecast, and what remains unknown.",
    "Report vault display and downloadable report/PDF parity must preserve the same structure, logo, status, evidence boundaries, confidence, limitations, next action, and support/correction path.",
  ],
  planReportStructures: [
    {
      planKey: "free-scan",
      reportName: "Protected Free Scan Result",
      requiredSections: ["Cendorq header", "business identity confidence", "first visible signal", "what was checked", "what is unknown", "confidence posture", "safe next action", "AI Readiness Review fit"],
      strongestNextAction: "Open AI Readiness Review only when the Free Scan result shows cause-level uncertainty or visible weakness worth proving.",
      blockedSections: ["full root-cause report", "implementation scope", "monthly control report", "guaranteed outcome claims"],
    },
    {
      planKey: "deep-review",
      reportName: "AI Readiness Review Report",
      requiredSections: ["Cendorq header", "executive command summary", "business and offer context", "evidence map", "visibility and AI-readiness findings", "trust and proof findings", "conversion friction", "competitor/category context", "priority severity map", "limitations", "Signal Repair or Readiness Control fit"],
      strongestNextAction: "Move to Signal Repair when a high-confidence repair target is identified; otherwise use watchlist or support clarification.",
      blockedSections: ["done-for-you implementation", "unlimited revisions", "unlabeled forecast", "guaranteed ROI"],
    },
    {
      planKey: "build-fix",
      reportName: "Signal Repair Delivery Record",
      requiredSections: ["Cendorq header", "approved scope", "before state", "repair target", "work completed or prepared", "customer approval checkpoint", "after/delivery summary", "remaining risk", "watchlist", "Readiness Control fit"],
      strongestNextAction: "Move to Readiness Control only when there is a real baseline, watchlist, freshness, competitor, or movement reason.",
      blockedSections: ["full AI Readiness Review unless purchased", "unlimited rebuild", "unapproved production changes", "guaranteed growth"],
    },
    {
      planKey: "ongoing-control",
      reportName: "Readiness Control Monthly Report",
      requiredSections: ["Cendorq header", "monthly command summary", "baseline comparison", "what changed", "what stayed stable", "what weakened", "watchlist", "forecast refresh when justified", "next-month priority", "satisfaction and renewal health"],
      strongestNextAction: "Continue, adjust, expand, or pause based on evidence-backed value and customer stage.",
      blockedSections: ["generic monthly newsletter", "unlimited implementation", "forecast as fact", "forced retention pressure"],
    },
  ],
  postPaymentServiceStandard: [
    "Payment confirmation must lead to idempotent fulfillment, entitlement activation, dashboard activation, report or work queue creation, plan-specific intake, kickoff email, safe support path, and a visible next action.",
    "Each plan must trigger the correct customer-facing report/result: Protected Free Scan result, AI Readiness Review report, Signal Repair delivery record, or Readiness Control monthly report and dashboard watchlist.",
    "Every customer-facing report/result must include Cendorq branding, report type, business identity, methodology version, evidence boundaries, confidence, limitations, priority, next action, and correction/support path.",
    "Every paid plan must show the customer what was purchased, what is active, what is pending, what Cendorq needs, what Cendorq is doing, where the result will appear, and how follow-up works.",
    "Checkout success pages, dashboard cards, report vault status, billing center, notifications, and support must all continue the same service sequence instead of creating disconnected experiences.",
  ],
  stageTargetingStandard: [
    "Retargeting must be based on customer stage, plan ownership, report state, behavior, evidence strength, and next-best-action readiness.",
    "The dashboard is the primary conversion command room after Free Scan; lifecycle email, notifications, report vault, billing, and support should all route back to the dashboard when it is the clearest next action.",
    "Timing windows are guidance, not pressure scripts: Cendorq may send earlier only for real access, fulfillment, intake, support, or evidence-backed urgency, and may suppress when the customer has already acted.",
    "Upgrade sequencing must stay clean: Free Scan moves toward AI Readiness Review, AI Readiness Review moves toward Signal Repair only when repair is justified, Signal Repair moves toward Readiness Control only when there is a baseline or watchlist reason, and Readiness Control moves toward renewal, expansion, or future feature adoption only when relevant.",
    "Every targeting message must have one customer reason, one next action, one clear destination, and one proof boundary.",
  ],
  continuousNurturingStandard: [
    "Continuous nurturing begins after first result release and continues through retention, renewal, expansion, future feature rollout, market movement, report freshness, customer milestones, and support closure.",
    "Nurturing must feel like Cendorq remembers the customer, understands the business, and knows what changed since the last interaction.",
    "Nurturing messages must be triggered by real value: new feature relevance, changed search or AI condition, competitor movement, report freshness, proof aging, milestone achieved, unresolved blocker, satisfaction signal, or a better next action.",
    "Nurturing must not become spam, generic newsletter pressure, fake urgency, or unsupported upsell repetition.",
    "Every nurture touch should give one useful reason to return: see a change, refresh a report, review a watchlist, approve a scope, ask support, compare a new feature, or choose the next safe depth.",
    "Future feature rollouts must connect to the customer's plan, report history, readiness state, and business need before being recommended.",
    "Recurring customers must receive value summaries that show what was watched, what changed, what stayed stable, what needs action, what is unknown, and why continued control may or may not matter.",
  ],
  stageTargetingMatrix: [
    {
      key: "free-scan-submitted-not-verified",
      currentStage: "Free Scan submitted, email not verified",
      nextTarget: "Verify inbox and open protected result",
      timingWindow: "Immediate, then 2 hours, 24 hours, and 72 hours if still unverified",
      trigger: "Scan submitted but verified email or protected result access is missing",
      primaryMessage: "Confirm your email so Cendorq can open your protected readiness result.",
      channelSequence: ["check-your-inbox page", "confirmation email", "dashboard pending state", "safe resend path"],
      suppressionRules: ["verified email", "result opened", "resend already requested recently", "support escalation active"],
      proofBoundary: "Do not reveal protected findings before verification and release state.",
    },
    {
      key: "free-scan-opened-no-review",
      currentStage: "Free Scan opened, no AI Readiness Review purchased",
      nextTarget: "AI Readiness Review",
      timingWindow: "Same-session dashboard CTA, then 24-48 hours, then day 3-5 when evidence supports deeper review",
      trigger: "Customer opened Free Scan and the result has uncertainty, visible weakness, or cause-level questions that Free Scan cannot verify",
      primaryMessage: "The first signal is visible; Review proves the cause before you spend on the wrong repair.",
      channelSequence: ["dashboard conversion inbox", "report vault next action", "email follow-up", "notification reminder"],
      suppressionRules: ["AI Readiness Review purchased", "no evidence-backed reason for deeper review", "customer dismissed recommendation", "support dispute unresolved"],
      proofBoundary: "Sell Review by explaining what Free Scan cannot prove, not by creating fear.",
    },
    {
      key: "review-purchased-intake-incomplete",
      currentStage: "AI Readiness Review purchased, intake incomplete",
      nextTarget: "Complete review intake",
      timingWindow: "Immediate after payment, then 12-24 hours, 48 hours, and 5 days if still incomplete",
      trigger: "Paid review entitlement exists but required business context is missing",
      primaryMessage: "Cendorq can start stronger once the business, offer, customer, and main concern are confirmed.",
      channelSequence: ["checkout success", "dashboard next action", "kickoff email", "notification reminder", "support nudge"],
      suppressionRules: ["intake completed", "support-assisted intake active", "customer requested pause", "refund/cancel/dispute state"],
      proofBoundary: "Ask only for useful context and never request secrets, tokens, passwords, card data, or unrelated private payloads.",
    },
    {
      key: "review-delivered-no-repair",
      currentStage: "AI Readiness Review delivered, Signal Repair not purchased",
      nextTarget: "Signal Repair",
      timingWindow: "Report-opened dashboard CTA, then 24-48 hours after report open, then day 5-7 when priority remains unresolved",
      trigger: "Review report identifies a high-confidence repair target and customer has not purchased Signal Repair",
      primaryMessage: "The cause is now visible; Repair turns the highest-confidence weakness into scoped improvement work.",
      channelSequence: ["report vault priority card", "dashboard conversion inbox", "email explanation", "support follow-up"],
      suppressionRules: ["Signal Repair purchased", "repair not evidence-supported", "customer marked no action", "correction request active"],
      proofBoundary: "Do not sell implementation if the review did not identify a clear repair target.",
    },
    {
      key: "repair-purchased-scope-incomplete",
      currentStage: "Signal Repair purchased, scope or assets incomplete",
      nextTarget: "Confirm repair scope",
      timingWindow: "Immediate after payment, then 24 hours, 72 hours, and 7 days if still blocked",
      trigger: "Signal Repair entitlement exists but approved page, offer, assets, constraints, or approval contact are missing",
      primaryMessage: "Confirm the repair target so Cendorq can improve the signal without guessing.",
      channelSequence: ["checkout success", "dashboard scope card", "kickoff email", "notification reminder", "support route"],
      suppressionRules: ["scope approved", "assets received", "support-assisted scope active", "customer pause requested"],
      proofBoundary: "Do not begin customer-facing repair work without scope clarity and approval posture.",
    },
    {
      key: "repair-delivered-no-control",
      currentStage: "Signal Repair delivered, Readiness Control not active",
      nextTarget: "Readiness Control",
      timingWindow: "Delivery summary CTA, then 3-7 days after delivery, then next freshness or watchlist trigger",
      trigger: "Repair has a before/after record, baseline, unresolved watchlist, competitor movement, or proof freshness reason",
      primaryMessage: "The repair is complete; Control keeps the improved signal from going stale or drifting unmonitored.",
      channelSequence: ["delivery summary", "dashboard watchlist", "email recap", "notification reminder"],
      suppressionRules: ["Readiness Control active", "no baseline or watchlist reason", "customer declined monitoring", "support dispute active"],
      proofBoundary: "Only recommend Control when there is a real baseline, watchlist, freshness, competitor, or movement reason.",
    },
    {
      key: "control-active-value-nurture",
      currentStage: "Readiness Control active",
      nextTarget: "Renewal confidence, expansion, or future feature adoption",
      timingWindow: "Monthly value summary, mid-cycle change alert when real, quarterly strategy refresh when useful",
      trigger: "Active subscription with monitored signals, stable signals, changed signals, report freshness, feature relevance, or support milestone",
      primaryMessage: "Here is what Cendorq watched, what changed, what stayed stable, and what should happen next.",
      channelSequence: ["monthly report", "dashboard watchlist", "email recap", "feature relevance note", "support check-in"],
      suppressionRules: ["no meaningful value update", "customer communication pause", "billing issue unresolved", "feature not relevant to plan or history"],
      proofBoundary: "Do not turn recurring value into generic newsletter pressure; every touch must show a real reason.",
    },
    {
      key: "paused-or-canceled-winback",
      currentStage: "Paused, canceled, or inactive customer with prior history",
      nextTarget: "Return to the safest relevant stage",
      timingWindow: "7 days after pause, 30 days after inactivity, then only when freshness, feature, or market trigger creates real value",
      trigger: "Customer has prior report history and a fresh reason to return exists",
      primaryMessage: "Your earlier readiness picture may be stale; Cendorq can refresh the safest next step if the business has changed.",
      channelSequence: ["dashboard re-entry", "email win-back", "support-safe return path"],
      suppressionRules: ["no fresh reason", "opt-out", "billing dispute", "customer requested no follow-up"],
      proofBoundary: "Win-back must be respectful, useful, and evidence-aware; do not use fear, fake scarcity, or guilt.",
    },
    {
      key: "future-feature-rollout",
      currentStage: "Any active or prior customer with relevant history",
      nextTarget: "Feature education, adoption, or stage-fit upgrade",
      timingWindow: "Feature announcement only when relevance is known; follow-up after 7-14 days only if useful and not acted on",
      trigger: "A new Cendorq feature, report module, dashboard capability, or monitoring lane matches the customer's plan, report history, or unresolved need",
      primaryMessage: "Cendorq added something that may help this specific readiness issue.",
      channelSequence: ["dashboard feature card", "targeted email", "report vault hint", "support-safe explanation"],
      suppressionRules: ["feature not relevant", "customer already adopted", "customer communication pause", "no plan-fit reason"],
      proofBoundary: "Do not blast all customers; future-feature nurture must connect to customer state, plan fit, and actual usefulness.",
    },
  ],
  operatingStandard: [
    "Every plan must define intelligence acquisition, checkout fulfillment, entitlement, intake, evidence requirements, customer deliverables, operator deliverables, email lifecycle, notification lifecycle, follow-up lifecycle, continuous nurturing lifecycle, stage-targeted retargeting, agent ownership, handoff destinations, and release-captain approval gates.",
    "Every plan must define minimum inputs, best inputs, evidence to collect, context to clarify, information to reject, analysis method, output structure, value maximizer, failure mode, escalation path, satisfaction loop, and retention/nurture path.",
    "Every plan must define allowed deliverables, blocked overlaps, required-before-delivery checks, approval gate, customer-facing summary, post-delivery explanation, and escalation rule.",
    "Every report and customer-facing deliverable must separate verified facts, customer-provided context, external evidence, assumptions, inferences, limitations, confidence, forecast direction, next actions, and refresh triggers.",
    "Every plan must deliver value beyond generic advice by converting evidence into practical actions, clear priorities, safer decisions, plan-appropriate implementation support, and retention-worthy continuity.",
    "Every plan must avoid fake urgency, unsupported ROI claims, certain-revenue language, certain-accuracy language, absolute security, liability-shield language, generic nurture spam, and unsupported feature-rollout pressure.",
    "Every plan must preserve customer privacy, safe projection, no raw payload exposure, no cross-customer data exposure, and no private report internals in nurturing copy.",
  ],
  planLifecycles: [
    {
      key: "free-scan",
      name: "Free Scan",
      intelligenceAcquisition: projectPlanIntelligenceAcquisition("free-scan"),
      fulfillmentBoundary: projectPlanValueFulfillment("free-scan"),
      customerPromise: "Provide a safe first read and useful direction without pretending the scan is a final complete review.",
      intake: ["guided free-check form", "business basics", "market context", "offer and buyer", "problem pressure"],
      requiredEvidence: ["customer-provided context", "owned business surface review", "safe public signals when available", "clear limitations when evidence is incomplete"],
      deliverables: ["protected dashboard Free Scan result", "first visible signal summary", "confidence posture", "evidence boundary", "visible limitations", "best next move guidance"],
      blockedOverlap: ["full AI Readiness Review report", "implementation-ready work order", "monthly monitoring summary", "unlimited recommendations", "private investigation output"],
      emailLifecycle: ["scan received", "result ready", "safe next step", "non-pressure follow-up if no upgrade"],
      followUpLifecycle: ["result opened check", "helpful clarification prompt", "AI Readiness Review recommendation only when evidence supports deeper review", "support path if customer disputes context"],
      nurtureLifecycle: ["unopened result reminder", "freshness reminder when the result ages", "market movement hint when relevant", "new feature relevance only when it helps the Free Scan customer", "return-to-dashboard prompt with one clear reason"],
      targetingPath: ["free-scan-submitted-not-verified", "free-scan-opened-no-review", "paused-or-canceled-winback", "future-feature-rollout"],
      agentOwnership: ["chief-report-truth-agent", "report-truth-research-scout", "customer-journey-scout", "conversion-luxury-ui-scout"],
      approvalGate: "free-scan-safe-result-release",
    },
    {
      key: "deep-review",
      name: "AI Readiness Review",
      intelligenceAcquisition: projectPlanIntelligenceAcquisition("deep-review"),
      fulfillmentBoundary: projectPlanValueFulfillment("deep-review"),
      customerPromise: "Deliver evidence-backed cause-level clarity and prioritized decision guidance without representing implementation work as included.",
      intake: ["payment confirmation", "verified customer ownership", "free scan handoff", "expanded review questionnaire", "business goals", "current funnel", "customer objections", "available access details without secrets"],
      requiredEvidence: ["free scan evidence", "customer-provided expanded context", "website and owned-surface review", "safe public market signals", "competitor/comparison context", "evidence conflict review"],
      deliverables: ["AI Readiness Review report", "evidence-backed cause analysis", "priority blocker map", "confidence-labeled findings", "Signal Repair or Readiness Control plan-fit recommendation"],
      blockedOverlap: ["done-for-you implementation", "unlimited revisions", "monthly monitoring loop", "ad spend management", "guaranteed revenue claim"],
      emailLifecycle: ["purchase received", "expanded intake request", "analysis in progress", "report ready", "follow-up clarification", "next-step recommendation"],
      followUpLifecycle: ["intake completion reminder", "report review guidance", "question/correction path", "Signal Repair or Readiness Control recommendation only with supporting evidence"],
      nurtureLifecycle: ["report-opened education", "unresolved-priority reminder", "forecast or watchlist refresh when justified", "new feature relevance tied to the report", "satisfaction check", "safe next-depth prompt when the evidence supports it"],
      targetingPath: ["review-purchased-intake-incomplete", "review-delivered-no-repair", "paused-or-canceled-winback", "future-feature-rollout"],
      agentOwnership: ["chief-report-truth-agent", "evidence-conflict-scout", "industry-context-scout", "report-design-quality-scout"],
      approvalGate: "ai-readiness-review-release-captain-gate",
    },
    {
      key: "build-fix",
      name: "Signal Repair",
      intelligenceAcquisition: projectPlanIntelligenceAcquisition("build-fix"),
      fulfillmentBoundary: projectPlanValueFulfillment("build-fix"),
      customerPromise: "Turn a clear weakness into scoped customer-facing improvement work while preserving evidence, approvals, scope clarity, and measurable but non-guaranteed outcome posture.",
      intake: ["payment confirmation", "scope confirmation", "asset/request checklist", "brand context", "page or funnel targets", "implementation constraints", "approval contact", "safe access instructions without secrets"],
      requiredEvidence: ["AI Readiness Review or supported review signal", "owned-surface evidence", "customer goals", "implementation constraints", "before-change snapshot", "approval and rollback posture"],
      deliverables: ["scoped implementation intake", "repair target confirmation", "customer-facing improvement work", "before-after delivery summary", "approval checkpoint and support handoff"],
      blockedOverlap: ["full AI Readiness Review report unless purchased separately", "unlimited site rebuild", "monthly monitoring loop", "unapproved production changes", "guaranteed revenue claim"],
      emailLifecycle: ["purchase received", "scope and asset request", "work started", "approval checkpoint", "delivery ready", "post-delivery follow-up"],
      followUpLifecycle: ["missing asset reminder", "approval reminder", "delivery review", "implementation support guidance", "Readiness Control recommendation when recurring monitoring is justified"],
      nurtureLifecycle: ["post-repair check-in", "before-after summary reminder", "watchlist trigger after repair", "new feature relevance tied to the repaired signal", "satisfaction check", "Readiness Control prompt only when a baseline or movement reason exists"],
      targetingPath: ["repair-purchased-scope-incomplete", "repair-delivered-no-control", "paused-or-canceled-winback", "future-feature-rollout"],
      agentOwnership: ["chief-product-experience-agent", "conversion-luxury-ui-scout", "report-design-quality-scout", "chief-security-command-agent"],
      approvalGate: "signal-repair-customer-output-approval",
    },
    {
      key: "ongoing-control",
      name: "Readiness Control",
      intelligenceAcquisition: projectPlanIntelligenceAcquisition("ongoing-control"),
      fulfillmentBoundary: projectPlanValueFulfillment("ongoing-control"),
      customerPromise: "Provide recurring monitoring, monthly priorities, status awareness, forecast refresh when justified, and decision support without implying unlimited implementation or guaranteed placement.",
      intake: ["subscription confirmation", "monitoring scope", "business priorities", "report cadence", "safe notification preferences", "change approval contact", "risk threshold"],
      requiredEvidence: ["previous reports", "safe trend signals", "customer-approved monitoring scope", "market and platform change signals", "monthly review records", "change approval history"],
      deliverables: ["monthly priority selection", "recurring review cycle", "dashboard status and alerts", "trend-aware summaries", "monthly decision support", "satisfaction and renewal health loop"],
      blockedOverlap: ["unlimited Signal Repair implementation", "standalone AI Readiness Review every month unless scoped", "ad spend management", "guaranteed ranking", "guaranteed AI answer placement"],
      emailLifecycle: ["subscription active", "monthly review started", "monthly report ready", "evidence-backed alert when risk is real", "renewal/value summary", "future-feature relevance note when useful"],
      followUpLifecycle: ["monthly check-in", "change approval request", "implemented update summary", "risk forecast alert", "plan adjustment recommendation", "satisfaction and renewal health check"],
      nurtureLifecycle: ["monthly value recap", "changed-signal alert", "stable-signal reassurance", "new feature eligibility", "expansion recommendation only when evidence supports it", "renewal confidence summary", "win-back path if subscription pauses"],
      targetingPath: ["control-active-value-nurture", "paused-or-canceled-winback", "future-feature-rollout"],
      agentOwnership: ["chief-growth-forecast-agent", "business-change-forecasting-scout", "analytics-and-growth-scout", "chief-report-truth-agent"],
      approvalGate: "readiness-control-monthly-review-gate",
    },
  ],
  crossPlanRules: [
    "Free Scan follow-up must be useful and calm, not pressure-based.",
    "Paid-plan recommendations must be evidence-supported and plan-fit labeled.",
    "AI Readiness Review may ask additional questions after payment when more detail improves accuracy, but must not request passwords, tokens, private keys, card numbers, bank details, or raw security payloads.",
    "Signal Repair must define concrete scope, required customer assets, approval checkpoints, and rollback/revision posture before delivery claims.",
    "Readiness Control must use controlled monitoring and approval gates, not unapproved production changes, autonomous business changes, unlimited implementation, or guaranteed placement claims.",
    "All plan emails must preserve truthful status, privacy, safe next action, no fake urgency, plan value boundaries, and one clear customer action.",
    "All plan follow-ups must connect to dashboard, report vault, notifications, support, billing, plan paths, and future feature relevance without customer journey dead ends.",
    "All continuous nurturing must be personalized by plan state, report history, evidence freshness, customer milestone, behavior, or real product update relevance.",
    "All lifecycle targeting must suppress when the customer already acted, opted out, asked for pause, opened support dispute, or no longer has a real next-step reason.",
    "All agent-produced plan work, nurture messages, and retargeting recommendations return to release-captain review before becoming customer-facing output.",
  ],
  blockedPatterns: [
    "planWithoutIntelligenceAcquisition",
    "planWithoutMinimumInputs",
    "planWithoutBestInputs",
    "planWithoutInformationRejection",
    "planWithoutAnalysisMethod",
    "planWithoutPlanSpecificOutputStructure",
    "planWithoutValueMaximizer",
    "planWithoutIntake",
    "planWithoutEvidence",
    "planWithoutReportOrDeliverable",
    "planWithoutEmailLifecycle",
    "planWithoutFollowUp",
    "planWithoutContinuousNurturing",
    "planWithoutStageTargeting",
    "planWithoutAgentOwner",
    "planWithoutApprovalGate",
    "planWithoutFulfillmentBoundary",
    "freeScanPresentedAsFinalCompleteReview",
    "freeScanDeliveringImplementation",
    "freeScanDeliveringMonthlyMonitoring",
    "aiReadinessReviewDeliveringImplementationWithoutSignalRepair",
    "signalRepairDeliveringUnlimitedImplementation",
    "signalRepairDeliveringRecurringMonitoring",
    "readinessControlDeliveringUnlimitedSignalRepair",
    "readinessControlGuaranteedRankingOrPlacement",
    "customerClaimTreatedAsVerifiedFact",
    "paidRecommendationWithoutEvidence",
    "repairWithoutScopeApproval",
    "readinessControlWithoutApprovalGate",
    "uncontrolledAgentPlanDelivery",
    "rawPayloadPlanDelivery",
    "rawEvidencePlanDelivery",
    "privateCredentialPlanDelivery",
    "paymentDataPlanDelivery",
    "crossCustomerPlanDelivery",
    "fakeUrgencyPlanFollowUp",
    "genericNurtureSpam",
    "unsupportedFeatureRolloutPressure",
    "retargetingWithoutStageReason",
    "retargetingWithoutSuppressionRules",
    "genericGeneratedReport",
    "unbrandedReport",
    "crowdedCtaWall",
    "forecastWithoutEvidence",
    "downloadableReportDrift",
    "guaranteedOutcomePlanClaim",
    "guaranteedRevenuePlanClaim",
    "guaranteedAccuracyPlanClaim",
  ],
  releaseRules: [
    "No plan lifecycle can be considered complete until intelligence acquisition, checkout fulfillment, entitlement, intake, evidence, delivery, email, follow-up, continuous nurturing, stage-targeted retargeting, agent ownership, approval gates, and fulfillment boundaries are represented.",
    "No customer-facing plan output can bypass report evidence records, customer output approval, fulfillment boundary checks, plan-specific acquisition checks, or release-captain review where applicable.",
    "No implementation or repair work can be represented as complete without scope clarity, customer approval posture, and safe delivery summary.",
    "No monthly or ongoing control action can mutate customer-facing production surfaces without approval gates and audit-safe records.",
    "No future feature, market-change alert, retention prompt, retargeting message, or expansion recommendation can be sent as customer-facing nurture unless it has a safe reason, plan fit, customer relevance, suppression review, and no-guarantee language.",
    "No report vault display, downloadable report, delivery summary, or monthly report can ship without Cendorq branding, plan-specific structure, evidence boundaries, confidence, limitations, next action, release status, and correction/support path.",
  ],
} as const;

export function getPlanDeliveryOrchestrationContract() {
  return PLAN_DELIVERY_ORCHESTRATION_CONTRACT;
}
