export const PLAN_DELIVERY_ORCHESTRATION_CONTRACT = {
  id: "plan-delivery-orchestration-contract",
  name: "Cendorq Plan Delivery Orchestration Contract",
  purpose:
    "Define the end-to-end delivery orchestration standard for every Cendorq plan so intake, evidence, report creation, email delivery, follow-up, agent ownership, customer handoffs, and upgrade paths stay truthful, premium, synchronized, automated where safe, and release-captain reviewed.",
  operatingStandard: [
    "Every plan must define intake, evidence requirements, customer deliverables, operator deliverables, email lifecycle, notification lifecycle, follow-up lifecycle, agent ownership, handoff destinations, and release-captain approval gates.",
    "Every report and customer-facing deliverable must separate verified facts, customer-provided context, external evidence, assumptions, inferences, limitations, confidence, and next actions.",
    "Every plan must deliver value beyond generic advice by converting evidence into practical actions, clear priorities, safer decisions, and plan-appropriate implementation support.",
    "Every plan must avoid fake urgency, unsupported ROI claims, certain-revenue language, certain-accuracy language, absolute security, and liability-shield language.",
    "Every plan must preserve customer privacy, safe projection, no raw payload exposure, and no cross-customer data exposure.",
  ],
  planLifecycles: [
    {
      key: "free-scan",
      name: "Free Scan",
      customerPromise: "Provide a safe first read and useful direction without pretending the scan is a final complete diagnosis.",
      intake: ["guided free-check form", "business basics", "market context", "offer and buyer", "problem pressure"],
      requiredEvidence: ["customer-provided context", "owned business surface review", "safe public signals when available", "clear limitations when evidence is incomplete"],
      deliverables: ["free scan report", "dashboard handoff", "notification handoff", "report vault handoff", "safe plan-fit suggestion when evidence supports it"],
      emailLifecycle: ["scan received", "report ready", "safe next step", "non-pressure follow-up if no upgrade"],
      followUpLifecycle: ["report opened check", "helpful clarification prompt", "deep-review/full-scan recommendation only when evidence supports deeper work", "support path if customer disputes context"],
      agentOwnership: ["chief-report-truth-agent", "report-truth-research-scout", "customer-journey-scout", "conversion-luxury-ui-scout"],
      approvalGate: "release-captain-review-required-before-public-report-language-expands-beyond-safe-free-scan-output",
    },
    {
      key: "deep-review",
      name: "Deep Review / Full Scan",
      customerPromise: "Deliver a fuller evidence-backed diagnosis with stronger research, clearer blockers, deeper recommendations, and a more complete plan-fit path.",
      intake: ["payment confirmation", "verified customer ownership", "free scan handoff", "expanded diagnostic questionnaire", "business goals", "current funnel", "customer objections", "available access details without secrets"],
      requiredEvidence: ["free scan evidence", "customer-provided expanded context", "website and owned-surface review", "safe public market signals", "competitor/comparison context", "evidence conflict review"],
      deliverables: ["full diagnostic report", "priority blocker map", "confidence-labeled evidence records", "recommended next actions", "safe plan-fit rationale", "customer dashboard and report vault update"],
      emailLifecycle: ["purchase received", "expanded intake request", "analysis in progress", "report ready", "follow-up clarification", "next-step recommendation"],
      followUpLifecycle: ["intake completion reminder", "report review guidance", "question/correction path", "build-fix or ongoing-control recommendation only with supporting evidence"],
      agentOwnership: ["chief-report-truth-agent", "evidence-conflict-scout", "industry-context-scout", "report-design-quality-scout"],
      approvalGate: "release-captain-report-release-review-required",
    },
    {
      key: "build-fix",
      name: "Build Fix / Optimization",
      customerPromise: "Turn diagnosis into plan-appropriate concrete improvements while preserving evidence, approvals, scope clarity, and measurable but non-guaranteed outcome posture.",
      intake: ["payment confirmation", "scope confirmation", "asset/request checklist", "brand context", "page or funnel targets", "implementation constraints", "approval contact", "safe access instructions without secrets"],
      requiredEvidence: ["deep review or supported diagnosis", "owned-surface evidence", "customer goals", "implementation constraints", "before-change snapshot", "approval and rollback posture"],
      deliverables: ["optimization plan", "copy/layout recommendations", "implementation-ready tasks", "before-after evidence record", "customer approval checkpoints", "handoff summary", "support and correction path"],
      emailLifecycle: ["purchase received", "scope and asset request", "work started", "approval checkpoint", "delivery ready", "post-delivery follow-up"],
      followUpLifecycle: ["missing asset reminder", "approval reminder", "delivery review", "implementation support guidance", "ongoing-control recommendation when recurring monitoring is justified"],
      agentOwnership: ["chief-product-experience-agent", "conversion-luxury-ui-scout", "report-design-quality-scout", "chief-security-command-agent"],
      approvalGate: "customer-output-and-release-captain-approval-required-before-customer-facing-delivery",
    },
    {
      key: "ongoing-control",
      name: "Ongoing Control / Monthly",
      customerPromise: "Provide recurring command, monitoring, recommendations, controlled updates, and business-change forecasting without uncontrolled automation or unsupported guarantees.",
      intake: ["subscription confirmation", "monitoring scope", "business priorities", "report cadence", "safe notification preferences", "change approval contact", "risk threshold"],
      requiredEvidence: ["previous reports", "safe aggregate trend signals", "customer-approved monitoring scope", "market and platform change signals", "monthly review records", "change approval history"],
      deliverables: ["monthly command summary", "priority update map", "change forecast", "approved optimization recommendations", "support path", "renewal/value proof summary"],
      emailLifecycle: ["subscription active", "monthly review started", "monthly report ready", "urgent-but-non-fake alert when risk is evidence-backed", "renewal/value summary"],
      followUpLifecycle: ["monthly check-in", "change approval request", "implemented update summary", "risk forecast alert", "plan adjustment recommendation"],
      agentOwnership: ["chief-growth-forecast-agent", "business-change-forecasting-scout", "analytics-and-growth-scout", "chief-report-truth-agent"],
      approvalGate: "controlled-maintenance-and-release-captain-review-required-before-production-impacting-change",
    },
  ],
  crossPlanRules: [
    "Free Scan follow-up must be useful and calm, not pressure-based.",
    "Paid-plan recommendations must be evidence-supported and plan-fit labeled.",
    "Deep Review may ask additional questions after payment when more detail improves accuracy, but must not request passwords, tokens, private keys, card numbers, bank details, or raw security payloads.",
    "Build Fix / Optimization must define concrete scope, required customer assets, approval checkpoints, and rollback/revision posture before delivery claims.",
    "Ongoing Control must use controlled monitoring and approval gates, not unapproved production changes or autonomous business changes.",
    "All plan emails must preserve truthful status, privacy, safe next action, and no fake urgency.",
    "All plan follow-ups must connect to dashboard, report vault, notifications, support, billing, and plan paths without customer journey dead ends.",
    "All agent-produced plan work returns to release-captain review before becoming customer-facing output.",
  ],
  blockedPatterns: [
    "planWithoutIntake",
    "planWithoutEvidence",
    "planWithoutReportOrDeliverable",
    "planWithoutEmailLifecycle",
    "planWithoutFollowUp",
    "planWithoutAgentOwner",
    "planWithoutApprovalGate",
    "freeScanPresentedAsFinalCompleteDiagnosis",
    "customerClaimTreatedAsVerifiedFact",
    "paidRecommendationWithoutEvidence",
    "optimizationWithoutScopeApproval",
    "monthlyControlWithoutApprovalGate",
    "uncontrolledAgentPlanDelivery",
    "rawPayloadPlanDelivery",
    "rawEvidencePlanDelivery",
    "privateCredentialPlanDelivery",
    "paymentDataPlanDelivery",
    "crossCustomerPlanDelivery",
    "fakeUrgencyPlanFollowUp",
    "guaranteedOutcomePlanClaim",
    "guaranteedRevenuePlanClaim",
    "guaranteedAccuracyPlanClaim",
  ],
  releaseRules: [
    "No plan lifecycle can be considered complete until intake, evidence, delivery, email, follow-up, agent ownership, and approval gates are represented.",
    "No customer-facing plan output can bypass report evidence records, customer output approval, or release-captain review where applicable.",
    "No implementation or optimization work can be represented as complete without scope clarity, customer approval posture, and safe delivery summary.",
    "No monthly or ongoing control action can mutate customer-facing production surfaces without approval gates and audit-safe records.",
  ],
} as const;

export function getPlanDeliveryOrchestrationContract() {
  return PLAN_DELIVERY_ORCHESTRATION_CONTRACT;
}
