export const PLATFORM_LAUNCH_READINESS_CONTRACT = {
  id: "platform-launch-readiness-contract",
  name: "Platform Launch Readiness Contract",
  purpose:
    "Tie every critical Cendorq launch surface into one release gate so public conversion, Free Scan, customer auth, dashboard handoffs, reports, billing, support, command center, owner configuration evidence/workflow, maintenance, and smoke coverage cannot drift before launch.",
  readinessGroups: [
    {
      key: "public-entry-and-free-scan",
      label: "Public entry and Free Scan",
      requiredEvidence: [
        "premium homepage entry is validated",
        "Free Scan dedicated route is validated",
        "popup is entry-only and not a full scan form",
        "no fake urgency or unsupported outcome promise",
      ],
      blocker: "Public launch blocks if homepage or Free Scan creates dark-pattern pressure, unsafe data collection, or disconnected handoff.",
    },
    {
      key: "auth-session-and-welcome",
      label: "Auth, session, and welcome email",
      requiredEvidence: [
        "production auth provider contracts validated",
        "server-side session boundary is defined",
        "verified-email gating is preserved",
        "one-time verified welcome email is validated",
        "browser-secret exclusions are validated",
      ],
      blocker: "Customer launch blocks if auth provider, verified welcome, session, CSRF, safe failure, or account-existence protections are incomplete.",
    },
    {
      key: "customer-platform-handoffs",
      label: "Customer platform handoffs",
      requiredEvidence: [
        "customer platform handoff contracts validated",
        "handoff runtime validated",
        "dashboard, notifications, report vault, billing, and plans integrations validated",
        "no customer journey dead end",
      ],
      blocker: "Customer platform launch blocks if any route lacks current state, one safe next action, recovery path, connected destination, or privacy posture.",
    },
    {
      key: "reports-and-vault",
      label: "Reports and vault",
      requiredEvidence: [
        "report truth engine validation",
        "report generation rendering contracts validation",
        "report vault handoff validation",
        "truth separation and branded HTML/PDF parity",
        "correction and support path visible",
      ],
      blocker: "Report launch blocks if pending reports can appear final, raw/internal data can render, PDF/HTML can drift, or unsupported guarantees can appear.",
    },
    {
      key: "billing-and-entitlements",
      label: "Billing and entitlements",
      requiredEvidence: [
        "billing center handoff validation",
        "billing checkout contracts validation",
        "payment links or provider checkout config are owner-provided before paid launch",
        "verified webhook or server-confirmed provider state required for entitlement",
      ],
      blocker: "Paid launch blocks if entitlement can activate from client-only redirect, unverified webhook, raw provider payload, support card collection, or unsupported billing promise.",
    },
    {
      key: "support-and-command-center",
      label: "Support and command center",
      requiredEvidence: [
        "support request/status/lifecycle validations",
        "operator approval/access/audit validations",
        "command center control interface validation",
        "closed command center route posture",
        "owner configuration evidence API validation",
        "owner configuration workflow API validation",
        "owner configuration workflow panel validation",
      ],
      blocker: "Operations launch blocks if internal notes, operator identity, owner evidence payloads, approval gates, audit records, or security-sensitive context can leak to customers.",
    },
    {
      key: "maintenance-and-smoke",
      label: "Controlled maintenance and smoke",
      requiredEvidence: [
        "controlled maintenance contracts validation",
        "production smoke coverage validation",
        "production smoke finalization validation",
        "owner evidence/workflow protected smoke coverage",
        "rollback, audit, approval, and no uncontrolled AI mutation posture",
      ],
      blocker: "Launch blocks if maintenance can mutate production without validation/approval/rollback/audit, if owner evidence/workflow routes can expose private payloads, or if smoke coverage requires live secrets by default.",
    },
  ],
  requiredReleaseEvidence: [
    "latest main commit is verified before release branch creation",
    "all validators are wired into validate:routes",
    "Vercel deployment is green for the release PR",
    "production smoke target is configured before production launch declaration",
    "owner-provided payment links or provider checkout config exist before paid checkout launch",
    "owner configuration evidence is recorded as safe summary only and does not approve launch by itself",
    "release-captain review of owner configuration workflow is tracked separately from launch approval",
    "server-only secrets are configured outside browser-accessible code",
    "rollback plan exists for auth, billing, reports, support, and public conversion changes",
    "audit plan exists for auth, support, billing, report release, operator actions, owner evidence workflow, and maintenance actions",
  ],
  hardLaunchLocks: [
    "No launch with browser-stored session tokens, CSRF tokens, provider tokens, admin keys, support context keys, or private keys.",
    "No launch with account-existence leakage in signup, login, verification, reset, support, or protected API failures.",
    "No launch with customer routes exposing raw payloads, raw evidence, raw security payloads, raw billing data, internal notes, operator identities, risk internals, attacker details, prompts, secrets, or cross-customer data.",
    "No launch with owner configuration evidence or workflow routes exposing raw provider payloads, protected config values, private credentials, private customer data, private audit payloads, or command-center preview keys.",
    "No launch with owner configuration evidence, owner approval posture, or release-captain workflow review treated as public launch, paid launch, report launch, provider configuration, payment mapping, or security readiness approval by itself.",
    "No launch with pending, draft, incomplete, or unapproved reports presented as final customer truth.",
    "No launch with paid report access without entitlement, customer ownership, verified access, and report release approval.",
    "No launch with billing entitlement activated from client-only success redirect or unverified webhook.",
    "No launch with support copy asking for card numbers, bank details, passwords, private keys, session tokens, CSRF tokens, admin keys, or support context keys.",
    "No launch with fake urgency, dark patterns, guaranteed ROI, guaranteed revenue, guaranteed legal outcome, guaranteed refund, guaranteed billing change, guaranteed security outcome, impossible-to-hack, never-liable, guaranteed-safe, or liability-free claims.",
    "No launch with uncontrolled AI or scheduled maintenance mutating production without validation, approval, rollback, and audit.",
  ],
  launchDecisionStates: ["blocked", "ready-for-owner-review", "ready-for-production-smoke", "ready-for-limited-launch", "ready-for-public-launch"],
  finalReleaseRules: [
    "Ready-for-owner-review requires every readiness group to have evidence or an explicit audited blocker.",
    "Ready-for-owner-review does not mean public launch, paid launch, report launch, provider configuration approval, payment mapping approval, or security readiness approval.",
    "Ready-for-production-smoke requires all route validators to be wired and passing in the release branch.",
    "Ready-for-limited-launch requires Vercel green, safe protected-route denial posture, owner evidence/workflow protected denial posture, and no critical launch locks active.",
    "Ready-for-public-launch requires production smoke completion, owner payment/auth configuration where applicable, rollback plan, audit plan, and no active hard launch locks.",
  ],
} as const;

export const PLATFORM_LAUNCH_READINESS_BLOCKED_PATTERNS = [
  "launchWithoutVerifiedMain",
  "launchWithoutValidateRoutes",
  "launchWithoutVercelGreen",
  "launchWithoutProductionSmoke",
  "launchWithoutAuthProvider",
  "launchWithoutVerifiedWelcomeEmail",
  "launchWithoutCustomerHandoffs",
  "launchWithoutReportApproval",
  "launchWithoutBillingWebhookVerification",
  "launchWithoutPaymentLinkMapping",
  "launchWithoutOwnerEvidenceProtectedPosture",
  "launchWithOwnerEvidenceAsApproval",
  "launchWithOwnerWorkflowAsApproval",
  "launchWithoutCommandCenterClosedPosture",
  "launchWithoutRollbackPlan",
  "launchWithoutAuditPlan",
  "browserStoredAuthorityLaunch",
  "accountExistenceLeakLaunch",
  "rawPayloadLaunchExposure",
  "rawEvidenceLaunchExposure",
  "rawOwnerEvidenceLaunchExposure",
  "rawBillingDataLaunchExposure",
  "internalNotesLaunchExposure",
  "operatorIdentityLaunchExposure",
  "riskInternalsLaunchExposure",
  "crossCustomerDataLaunchExposure",
  "pendingReportFinalLaunch",
  "clientBillingAuthorityLaunch",
  "unverifiedWebhookLaunch",
  "fakeUrgencyLaunch",
  "guaranteedOutcomeLaunch",
  "uncontrolledAiMutationLaunch",
] as const;

export function getPlatformLaunchReadinessContract() {
  return PLATFORM_LAUNCH_READINESS_CONTRACT;
}
