export const PLATFORM_LAUNCH_READINESS_AUDIT_API_CONTRACT = {
  id: "platform-launch-readiness-audit-api-contract",
  name: "Platform Launch Readiness Audit and API Contract",
  purpose:
    "Define how launch readiness decisions are recorded, audited, and exposed through operator-only APIs without customer exposure, raw/internal data leakage, or unsafe release claims.",
  apiSurfaces: [
    {
      route: "/api/command-center/launch-readiness",
      method: "GET",
      purpose: "Return the current safe launch readiness projection to authorized command-center operators only.",
      authorization: "command-center operator access required",
      mutation: "none",
      cache: "no-store",
    },
    {
      route: "/api/command-center/launch-readiness/audit",
      method: "POST",
      purpose: "Record an audited launch readiness decision or owner review note from an authorized operator only.",
      authorization: "command-center operator approval required",
      mutation: "append-only audit event",
      cache: "no-store",
    },
    {
      route: "/api/command-center/launch-readiness/history",
      method: "GET",
      purpose: "Return safe launch readiness audit history summaries to authorized command-center operators only.",
      authorization: "command-center operator access required",
      mutation: "none",
      cache: "no-store",
    },
  ],
  safeProjectionFields: [
    "decision",
    "safeSummary",
    "readyGroups",
    "blockedGroups",
    "evidenceGaps",
    "safeNextActions",
    "hardLaunchLocks",
    "blockedPatterns",
    "auditStatus",
    "lastReviewedAt",
    "reviewedByRole",
    "auditId",
  ],
  auditRecordFields: [
    "auditId",
    "decision",
    "safeSummaryHash",
    "readyGroupKeys",
    "blockedGroupKeys",
    "evidenceGapKeys",
    "safeNextActionKeys",
    "hardLaunchLockKeys",
    "blockedPatternKeys",
    "reviewedByRole",
    "reviewReason",
    "reviewedAt",
    "sourceRoute",
    "requestIdHash",
  ],
  requiredAuditEvents: [
    "launch-readiness-projection-viewed",
    "launch-readiness-owner-review-recorded",
    "launch-readiness-production-smoke-ready-recorded",
    "launch-readiness-limited-launch-ready-recorded",
    "launch-readiness-public-launch-ready-recorded",
    "launch-readiness-blocked-recorded",
    "launch-readiness-audit-history-viewed",
    "launch-readiness-access-denied",
  ],
  authorizationRules: [
    "All launch readiness APIs are command-center-only and must remain closed to customers, public visitors, unauthenticated users, crawlers, and support-message contexts.",
    "GET projection APIs may return only safe projection fields and no raw source evidence.",
    "POST audit APIs require operator approval posture, safe review reason, idempotency key, and append-only audit behavior.",
    "Audit APIs must not allow deleting, rewriting, or hiding launch readiness audit records.",
    "All responses must use no-store caching and generic safe failures.",
  ],
  safeFailureRules: [
    "Access denial must not disclose whether command center exists, whether launch readiness records exist, whether an operator exists, or which authorization condition failed.",
    "Audit write failure must not disclose storage internals, table names, provider payloads, secret names, lock internals, or record existence.",
    "History lookup failure must return a generic safe failure and no partial internal audit payload.",
  ],
  blockedProjectionFields: [
    "rawPayload",
    "rawEvidence",
    "rawBillingData",
    "rawSecurityPayload",
    "internalNotes",
    "operatorIdentity",
    "operatorEmail",
    "operatorIp",
    "riskScoringInternals",
    "attackerDetails",
    "promptMessages",
    "systemMessages",
    "developerMessages",
    "databaseUrl",
    "providerSecret",
    "webhookSecret",
    "paymentProviderSecret",
    "sessionToken",
    "csrfToken",
    "adminKey",
    "supportContextKey",
    "privateKey",
    "crossCustomerData",
  ],
  releaseRules: [
    "Do not expose launch readiness APIs outside command center access control.",
    "Do not allow customer-facing routes, emails, notifications, support pages, report vault, billing center, or public pages to read launch readiness audit internals.",
    "Do not record launch readiness decisions without an audit id, reviewed role, safe reason, timestamp, and source route.",
    "Do not convert launch readiness state into public launch claims unless production smoke, owner configuration, rollback, audit, and hard launch locks are cleared.",
    "Do not mutate production state from launch readiness APIs; only append audit records or return safe projections.",
  ],
} as const;

export const PLATFORM_LAUNCH_READINESS_AUDIT_API_BLOCKED_PATTERNS = [
  "customerLaunchReadinessApiAccess",
  "publicLaunchReadinessApiAccess",
  "unauthenticatedLaunchReadinessApiAccess",
  "launchReadinessRecordDeletion",
  "launchReadinessAuditRewrite",
  "rawPayloadAuditProjection",
  "rawEvidenceAuditProjection",
  "rawBillingDataAuditProjection",
  "internalNotesAuditProjection",
  "operatorIdentityAuditProjection",
  "operatorEmailAuditProjection",
  "operatorIpAuditProjection",
  "riskInternalsAuditProjection",
  "promptAuditProjection",
  "databaseUrlAuditProjection",
  "providerSecretAuditProjection",
  "webhookSecretAuditProjection",
  "paymentProviderSecretAuditProjection",
  "sessionTokenAuditProjection",
  "csrfTokenAuditProjection",
  "adminKeyAuditProjection",
  "supportContextKeyAuditProjection",
  "privateKeyAuditProjection",
  "crossCustomerDataAuditProjection",
  "accountExistenceLeakAuditApi",
  "recordExistenceLeakAuditApi",
  "publicLaunchClaimWithoutSmoke",
  "launchReadinessProductionMutation",
] as const;

export function getPlatformLaunchReadinessAuditApiContract() {
  return PLATFORM_LAUNCH_READINESS_AUDIT_API_CONTRACT;
}
