export const PLATFORM_INTERFACE_EXCELLENCE_CONTRACT = {
  id: "platform-interface-excellence-lock-v1",
  name: "Cendorq platform interface excellence lock",
  purpose:
    "Hard-lock customer dashboard, public website, command center, and support/operator surfaces to a premium, truthful, accessible, scalable, and conversion-safe standard with no quality drift.",
  appliesTo: [
    "customer-dashboard",
    "public-frontend-website",
    "free-scan-experience",
    "plans-and-conversion-paths",
    "report-vault",
    "notification-center",
    "support-center",
    "support-status",
    "operator-command-center",
    "admin-support-console",
    "report-rendering-surfaces",
    "billing-and-plan-surfaces",
  ],
  nonNegotiableStandard:
    "Every customer-facing and operator-facing interface must feel premium, clear, useful, fast, protected, truthful, and carefully guided. No casual placeholder, dark pattern, fake urgency, inaccessible interaction, or unsupported promise is allowed.",
  globalUXPrinciples: [
    "clear visual hierarchy before decoration",
    "fast first understanding within one viewport",
    "summary-to-detail layout for complex decisions",
    "action paths with visible next step and safe fallback",
    "consistent navigation, help, and recovery paths",
    "luxury polish without hiding practical business value",
    "mobile-responsive layouts before store-app expansion",
    "keyboard-visible focus and accessible interactive targets",
    "plain-language explanations for business owners",
    "high-trust microcopy that avoids fake urgency",
  ],
  dashboardStandard: [
    "show business status, next best action, and proof context immediately",
    "surface Free Scan, reports, billing, notifications, support, and plans as connected stages",
    "use stage-aware cards rather than generic tiles",
    "explain what changed, what matters, and what to do next",
    "provide safe support and status follow-through without exposing internals",
    "make conversion paths useful even when the customer does not buy",
    "adapt copy for business size, revenue stage, category, and channel mix",
    "reserve space for social, creator, marketplace, local, digital, and service revenue streams",
  ],
  publicWebsiteStandard: [
    "lead with truthful business value and practical outcomes",
    "show clear Free Scan entry and paid-plan path without deceptive pressure",
    "explain proof, methodology, safety boundaries, and customer control",
    "include accessible navigation and consistent support routes",
    "avoid unsupported guarantees, vague superlatives without proof, and fake scarcity",
    "make pricing/payment-link integration explicit once finalized",
  ],
  commandCenterStandard: [
    "operator/admin surfaces must separate read-only review from guarded mutation",
    "every mutation must pass role, gate, reauth, safe summary, and record checks",
    "safe history must render projections only and never raw data or secrets",
    "section maps and checklists must explain exactly which path operators are using",
    "command center density must be controlled with sections, maps, filters, and summaries",
  ],
  analysisAndReportStandard: [
    "reports must separate verified facts, assumptions, inferences, and recommendations",
    "reports must be branded, visual, explanatory, and business-specific",
    "claims must be bounded and avoid unsupported ROI, legal, billing, security, or outcome promises",
    "small-print risk and liability language must reduce exposure without weakening trust",
    "reports must adapt for revenue level, operating model, location, language, and channels",
  ],
  accessibilityAndResponsiveness: [
    "no keyboard traps",
    "visible focus required for interactive elements",
    "forms need labels, errors, recovery copy, and safe submission states",
    "tap/click targets must be large enough for mobile use",
    "layouts must remain useful on mobile, tablet, desktop, and wide screens",
    "motion and visual effects must not be required to understand the product",
  ],
  conversionAndTrustRules: [
    "no fake urgency",
    "no dark-pattern pressure",
    "no unsupported guarantees",
    "conversion copy must be truthful, useful, and explain the customer benefit",
    "paid paths must preserve support, billing, and cancellation clarity",
    "free paths must still deliver practical value and lead to safe next steps",
  ],
  securityAndPrivacyRules: [
    "no browser-exposed secrets, protected context keys, session tokens, or admin keys",
    "no localStorage or sessionStorage for auth/session/protected customer data",
    "no raw payload, raw evidence, internal notes, operator identity, or risk internals in customer surfaces",
    "no cross-customer access or account-existence leakage",
    "state-changing APIs require guarded server-side checks and safe failures",
  ],
  scalabilityRules: [
    "server responses for protected data must be no-store where appropriate",
    "customer and operator lists must be bounded, filterable, or paginated",
    "interfaces should favor progressive disclosure over large unbounded dumps",
    "validation must reject drift before merge",
  ],
} as const;

export const PLATFORM_INTERFACE_EXCELLENCE_HARD_LOCKS = [
  "customer dashboard cannot degrade into generic tiles",
  "public website cannot use fake urgency or unsupported outcome claims",
  "command center cannot mix read-only review with guarded mutation without clear separation",
  "support/operator surfaces cannot expose raw/internal/protected fields",
  "reports cannot present guesses as verified facts",
  "payment links cannot be added without explicit plan mapping and safe fallback",
  "mobile/app expansion cannot duplicate secrets or protected logic client-side",
  "all new interface layers require validation before merge",
] as const;

export const PLATFORM_INTERFACE_EXCELLENCE_BLOCKED_PATTERNS = [
  "guaranteed ROI",
  "guaranteed refund",
  "guaranteed legal outcome",
  "guaranteed security outcome",
  "impossible to hack",
  "never liable",
  "liability-free",
  "rawPayload",
  "rawEvidence",
  "rawSecurityPayload",
  "rawBillingData",
  "rawPaymentData",
  "internalNotes",
  "operatorIdentity",
  "riskScoringInternals",
  "attackerDetails",
  "sessionToken",
  "csrfToken",
  "x-support-admin-key",
  "x-cendorq-customer-context",
  "CUSTOMER_SUPPORT_CONTEXT_KEY",
  "SUPPORT_CONSOLE_READ_KEY",
  "localStorage",
  "sessionStorage",
] as const;
