export const PRODUCTION_SMOKE_TARGET_CONTRACT = {
  id: "production-smoke-target-contract",
  name: "Production Smoke Target Contract",
  purpose:
    "Define safe production smoke target setup, route groups, expected outcomes, and release evidence without production mutation or unsafe public claims.",
  targetRequirements: [
    "Production smoke target must be owner-approved before public launch review.",
    "Default smoke must be read-only and non-mutating.",
    "Default smoke must not require privileged live configuration to pass.",
    "Protected route denial is a valid pass when the denial is generic, no-store, and does not reveal private state.",
    "Command center routes must remain closed by default without the approved operator access posture.",
    "Smoke output must record safe route group status, expected posture, checked time, and evidence reference only.",
  ],
  routeGroups: [
    {
      key: "public-conversion-routes",
      label: "Public conversion routes",
      routes: ["/", "/free-check", "/plans"],
      expectedPosture: "reachable-public-safe",
      requiredChecks: ["premium entry renders", "free scan entry renders", "plans copy renders", "no fake urgency", "no unsupported outcome claim"],
    },
    {
      key: "customer-platform-routes",
      label: "Customer platform routes",
      routes: ["/dashboard", "/dashboard/reports", "/dashboard/billing", "/dashboard/notifications", "/dashboard/support", "/dashboard/support/status"],
      expectedPosture: "safe-auth-boundary-or-safe-render",
      requiredChecks: ["no customer data leak", "safe handoff posture", "no pending-as-final state", "no raw/internal projection"],
    },
    {
      key: "protected-api-routes",
      label: "Protected API routes",
      routes: ["/api/customer/support/request", "/api/customer/support/status", "/api/customer/notifications"],
      expectedPosture: "generic-safe-denial-without-session",
      requiredChecks: ["no-store response", "generic denial", "no account existence leak", "no internal field leak"],
    },
    {
      key: "command-center-routes",
      label: "Command center routes",
      routes: ["/command-center", "/api/command-center/launch-readiness", "/api/command-center/launch-readiness/evidence"],
      expectedPosture: "closed-by-default",
      requiredChecks: ["closed without operator posture", "no indexed response", "no private operating detail", "no customer-facing projection"],
    },
    {
      key: "launch-evidence-routes",
      label: "Launch evidence routes",
      routes: ["/api/command-center/launch-readiness/evidence", "/api/command-center/launch-readiness/evidence/record"],
      expectedPosture: "operator-only-safe-projection",
      requiredChecks: ["append-only evidence shape", "safe projection fields", "no production mutation", "no public launch claim from evidence alone"],
    },
  ],
  safeSmokeRecordFields: [
    "smokeRunId",
    "targetName",
    "routeGroupKey",
    "route",
    "expectedPosture",
    "observedPosture",
    "result",
    "checkedAt",
    "safeSummary",
    "evidenceId",
    "requestIdHash",
  ],
  blockedSmokeRecordFields: [
    "rawResponseBody",
    "rawRequestBody",
    "rawHeaderDump",
    "privateCustomerData",
    "internalNotes",
    "operatorPrivateIdentity",
    "protectedProviderDetail",
    "privilegedConfigValue",
    "privateCredentialMaterial",
    "privateAuditPayload",
    "crossCustomerData",
  ],
  releaseRules: [
    "Do not treat smoke target configuration as production smoke completion.",
    "Do not treat a failed protected-route access attempt as failure when the expected safe denial posture is returned.",
    "Do not treat public route render success as public launch approval.",
    "Do not record raw response bodies or private route payloads in smoke records.",
    "Do not allow smoke checks to mutate production state by default.",
    "Do not state public launch readiness until smoke target, evidence, rollback, audit, owner configuration, and hard-lock clearance are complete.",
  ],
} as const;

export const PRODUCTION_SMOKE_TARGET_BLOCKED_PATTERNS = [
  "smokeTargetEqualsSmokeComplete",
  "publicRenderEqualsLaunchApproval",
  "protectedSafeDenialMarkedFailure",
  "commandCenterOpenByDefault",
  "productionMutationByDefaultSmoke",
  "rawResponseBodySmokeRecord",
  "rawRequestBodySmokeRecord",
  "rawHeaderDumpSmokeRecord",
  "privateCustomerDataSmokeRecord",
  "internalNotesSmokeRecord",
  "operatorPrivateIdentitySmokeRecord",
  "protectedProviderDetailSmokeRecord",
  "privilegedConfigValueSmokeRecord",
  "privateCredentialMaterialSmokeRecord",
  "privateAuditPayloadSmokeRecord",
  "crossCustomerDataSmokeRecord",
  "smokeOnlyPublicLaunchClaim",
] as const;

export function getProductionSmokeTargetContract() {
  return PRODUCTION_SMOKE_TARGET_CONTRACT;
}
