export const REPORT_GENERATION_RENDERING_CONTRACT = {
  id: "report-generation-rendering-contract",
  name: "Report Generation and Branded Rendering Contract",
  purpose:
    "Define how Cendorq generates, approves, brands, renders, and releases customer reports as safe HTML/PDF outputs without raw/internal leakage or unsupported outcome promises.",
  reportTypes: [
    "free-scan-result",
    "deep-review-report",
    "build-fix-summary",
    "ongoing-control-monthly-report",
    "correction-review-addendum",
  ],
  requiredSections: [
    "executive summary",
    "verified facts",
    "assumptions",
    "inferences",
    "confidence labels",
    "limitations",
    "recommendations",
    "next actions",
    "support and correction path",
    "liability and protection footer",
  ],
  truthSeparationRules: [
    "Verified facts must be separated from assumptions, inferences, recommendations, and limitations.",
    "Pending, draft, incomplete, or unapproved reports must never be presented as final customer truth.",
    "Confidence labels must be visible when the report includes inference, recommendation, or prioritized next action.",
    "Recommendations must name the supporting basis and avoid outcome guarantees covering ROI, revenue, security outcomes, legal outcomes, or business results.",
  ],
  brandedRenderingRules: [
    "HTML and PDF reports must carry Cendorq branding, report title, report type, report version, generated timestamp, customer-safe business name, and release status.",
    "Customer business logo may be rendered only when provided by the customer, approved for report use, safely stored, and passed through a safe asset projection.",
    "If a customer logo is missing, unsafe, unavailable, or unapproved, the report must fall back to a Cendorq-branded neutral placeholder without blocking release.",
    "Report visuals must be explanatory, accessible, and customer-safe; charts must not expose raw evidence, raw payloads, private report internals, or cross-customer data.",
    "PDF and HTML outputs must use the same approved report content source so customer-facing artifacts do not drift.",
  ],
  approvalGates: [
    "report generation source is customer-owned",
    "safe report projection exists",
    "truth separation checks pass",
    "blocked claim scan passes",
    "raw/internal leakage scan passes",
    "correction and support path is visible",
    "release approver or release automation policy is recorded",
    "report version and audit event are recorded",
  ],
  outputProjectionFields: [
    "reportId",
    "reportType",
    "reportVersion",
    "businessName",
    "businessLogoStatus",
    "releaseStatus",
    "generatedAt",
    "summary",
    "verifiedFacts",
    "assumptions",
    "inferences",
    "confidenceLabels",
    "limitations",
    "recommendations",
    "nextActions",
    "supportPath",
    "correctionPath",
    "liabilityFooter",
  ],
  blockedOutputFields: [
    "rawPayload",
    "rawEvidence",
    "rawSecurityPayload",
    "rawBillingData",
    "internalNotes",
    "operatorIdentity",
    "riskScoringInternals",
    "attackerDetails",
    "promptMessages",
    "systemMessages",
    "developerMessages",
    "secrets",
    "passwords",
    "apiKeys",
    "privateKeys",
    "sessionTokens",
    "csrfTokens",
    "adminKeys",
    "supportContextKeys",
    "crossCustomerData",
  ],
  liabilityFooterRules: [
    "Footer must be calm and trust-preserving, not fear-based.",
    "Footer must state that analysis is based on available provided and observed information at generation time.",
    "Footer must preserve auditability and correction path without claiming audit records are deleted when preservation is required.",
    "Footer must not claim Cendorq is breach-proof, risk-free, free from all responsibility, or certain to produce results.",
  ],
  releaseRules: [
    "Do not release a report unless approval gates pass or an approved audited exception exists.",
    "Do not notify the customer that a report is ready until releaseStatus is approved or customer-safe-ready.",
    "Do not expose report output to a customer without customer ownership, verified access, and report release approval.",
    "Do not let PDF, HTML, dashboard card, notification, or email report summaries drift from the approved report version.",
  ],
} as const;

export const REPORT_GENERATION_RENDERING_BLOCKED_PATTERNS = [
  "pendingReportPresentedAsFinal",
  "draftReportReleased",
  "rawPayloadRendered",
  "rawEvidenceRendered",
  "rawSecurityPayloadRendered",
  "rawBillingDataRendered",
  "internalNotesRendered",
  "operatorIdentityRendered",
  "riskInternalsRendered",
  "attackerDetailsRendered",
  "promptRendered",
  "secretRendered",
  "sessionTokenRendered",
  "csrfTokenRendered",
  "adminKeyRendered",
  "supportContextKeyRendered",
  "crossCustomerDataRendered",
  "guaranteedRoiReportClaim",
  "guaranteedRevenueReportClaim",
  "guaranteedSecurityOutcomeClaim",
  "guaranteedLegalOutcomeClaim",
  "liabilityFreeReportClaim",
  "auditDeletionClaim",
  "pdfHtmlVersionDrift",
  "unapprovedBusinessLogoRendered",
] as const;

export function getReportGenerationRenderingContract() {
  return REPORT_GENERATION_RENDERING_CONTRACT;
}
