export const REPORT_GENERATION_RENDERING_CONTRACT = {
  id: "report-generation-rendering-contract",
  name: "Report Generation and Branded Rendering Contract",
  purpose:
    "Define how Cendorq generates, approves, brands, renders, and releases premium customer reports as safe HTML/PDF/dashboard outputs with plan-specific structure, plain customer wording, helpful visuals, evidence separation, and no raw/internal leakage or unsupported outcome promises.",
  reportTypes: [
    "free-scan-result",
    "deep-review-report",
    "build-fix-summary",
    "ongoing-control-monthly-report",
    "correction-review-addendum",
  ],
  planReportRules: [
    {
      plan: "Free Scan",
      reportType: "free-scan-result",
      title: "Free Scan Signal Report",
      maximumCustomerFacingLength: "two pages",
      purpose: "Create a useful first signal and make the customer understand why a deeper review may be worth it without giving away the full diagnosis.",
      requiredInputs: ["business name", "website or main public profile", "customer name", "email", "main location", "business type", "main offer", "best customer", "what feels weak right now"],
      requiredVisuals: ["simple signal meter or readiness bar", "small issue-priority visual"],
      nextPlanMotion: "Deep Review when deeper cause-level diagnosis is needed",
      blockedContent: ["full competitor table", "full forecast model", "full fix roadmap", "private access request", "paid-plan onboarding questionnaire"],
    },
    {
      plan: "Deep Review",
      reportType: "deep-review-report",
      title: "Deep Review Diagnostic Report",
      purpose: "Deliver the full scan, full diagnosis, cause-level visibility/readiness review, competitor comparison when evidence allows, and prioritized next action.",
      requiredInputs: ["active Deep Review entitlement", "verified customer ownership or authorized requester", "website", "business type", "target customer", "main offer", "main customer action", "location or service area", "social/profile links when relevant", "known competitors when available", "current channels when relevant", "what the customer has already tried", "biggest concern"],
      requiredVisuals: ["visibility/readiness scorecard", "priority heat map", "competitor comparison chart when evidence allows", "forecast or risk outlook visual", "opportunity map when useful", "clear severity labels"],
      nextPlanMotion: "Build Fix when an approved weakness can be improved",
      blockedContent: ["private competitor data claims", "unsupported certainty", "hidden limitations"],
    },
    {
      plan: "Build Fix",
      reportType: "build-fix-summary",
      title: "Build Fix Delivery Report",
      purpose: "Turn an approved weakness into a scoped implementation plan, delivery summary, and realistic progress expectation.",
      requiredInputs: ["active Build Fix entitlement", "verified customer ownership or authorized requester", "approved fix target", "approved scope", "primary call to action", "brand tone or style preference", "logo/assets when needed", "safe access handoff when required", "what must not change", "approval contact"],
      requiredVisuals: ["before/after summary visual", "scoped work checklist", "expected timeline visual", "remaining-risk map", "next-control path visual"],
      nextPlanMotion: "Ongoing Control when the customer needs to keep visibility and readiness from drifting",
      blockedContent: ["exact result date promise", "unapproved scope expansion", "implementation without needed access or approval"],
    },
    {
      plan: "Ongoing Control",
      reportType: "ongoing-control-monthly-report",
      title: "Ongoing Control Report",
      purpose: "Keep the customer current as search, AI engines, platforms, customers, and competitors keep changing.",
      requiredInputs: ["active Ongoing Control subscription", "verified customer ownership or authorized requester", "monitoring scope", "review cadence", "current priority", "business changes", "new offers or service updates", "competitors to watch when relevant", "platforms or channels to watch when relevant"],
      requiredVisuals: ["trend line or month-over-month signal visual", "change summary cards", "risk watchlist", "priority meter", "next-action path visual"],
      nextPlanMotion: "another Build Fix when a new scoped weakness appears",
      blockedContent: ["noise without clear action", "unbounded monitoring claims", "cross-customer private comparison"],
    },
  ],
  requiredSections: [
    "Cendorq letterhead",
    "customer-safe business identity",
    "report title and report type",
    "report version and generated date",
    "executive summary",
    "verified facts",
    "assumptions",
    "inferences",
    "confidence labels",
    "limitations",
    "visual explanation",
    "recommendations",
    "next actions",
    "support and correction path",
    "liability and protection footer",
  ],
  customerWordingRules: [
    "Reports must be educational while selling and informational while selling.",
    "Use customer-understandable words such as visibility, readiness, trust, clarity, proof, weak point, strongest next step, what this means, what to fix first, and what may take time.",
    "Every technical point must answer what we saw, why it matters, how confident we are, and what should happen next.",
    "Report language must sound premium, clear, calm, direct, and useful instead of generic, robotic, overly technical, or filler-heavy.",
  ],
  visualDesignRules: [
    "Every customer report must look pristine, structured, and premium across dashboard, HTML, and PDF outputs.",
    "Visuals must teach; do not add decorative charts that do not make the customer decision clearer.",
    "Use scorecards when scores help the customer understand priority, bar charts for simple comparison, line charts for trends, heat maps for severity, simple tables for comparisons, timelines for Build Fix expectations, and progress visuals for Ongoing Control.",
    "Charts and tables must be readable, accessible, high-contrast, and safe for a non-technical business owner.",
  ],
  truthSeparationRules: [
    "Verified facts must be separated from assumptions, inferences, recommendations, and limitations.",
    "Pending, draft, incomplete, or unapproved reports must never be presented as final customer truth.",
    "Confidence labels must be visible when the report includes inference, recommendation, or prioritized next action.",
    "Recommendations must name the supporting basis and avoid outcome guarantees covering ROI, revenue, security outcomes, legal outcomes, or business results.",
    "Competitor and forecast sections must describe the public evidence basis and avoid fake precision or private-data assumptions.",
  ],
  brandedRenderingRules: [
    "HTML and PDF reports must carry Cendorq branding, report title, report type, report version, generated timestamp, customer-safe business name, and release status.",
    "Customer business logo may be rendered only when provided by the customer, approved for report use, safely stored, and passed through a safe asset projection.",
    "If a customer logo is missing, unsafe, unavailable, or unapproved, the report must fall back to a Cendorq-branded neutral placeholder without blocking release.",
    "Report visuals must be explanatory, accessible, and customer-safe; charts must not expose raw evidence, raw payloads, private report internals, or cross-customer data.",
    "PDF and HTML outputs must use the same approved report content source so customer-facing artifacts do not drift.",
  ],
  dashboardStorageRules: [
    "Every report or report-related output must create or update a customer dashboard report record when customer-safe storage is available.",
    "Dashboard report records must show report ID, report type, plan type, business name, generated date, release status, report version, short summary, next recommended action, missing customer inputs when blocked, support and correction path, and approved view/download link when available.",
    "Dashboard records must not expose draft, unapproved, raw, internal, cross-customer, or unsafe report data.",
  ],
  approvalGates: [
    "report generation source is customer-owned",
    "safe report projection exists",
    "plan-specific required sections exist",
    "customer wording review passes",
    "visual explanation review passes",
    "truth separation checks pass",
    "blocked claim scan passes",
    "raw/internal leakage scan passes",
    "correction and support path is visible",
    "release approver or release automation policy is recorded",
    "report version and audit event are recorded",
  ],
  outputProjectionFields: [
    "reportId",
    "reportType",
    "planType",
    "reportVersion",
    "businessName",
    "businessLogoStatus",
    "releaseStatus",
    "generatedAt",
    "summary",
    "verifiedFacts",
    "assumptions",
    "inferences",
    "confidenceLabels",
    "limitations",
    "visuals",
    "recommendations",
    "nextActions",
    "missingCustomerInputs",
    "supportPath",
    "correctionPath",
    "liabilityFooter",
  ],
  blockedOutputFields: [
    "rawPayload",
    "rawEvidence",
    "rawSecurityPayload",
    "rawBillingData",
    "internalNotes",
    "operatorIdentity",
    "riskScoringInternals",
    "attackerDetails",
    "promptMessages",
    "systemMessages",
    "developerMessages",
    "secrets",
    "passwords",
    "apiKeys",
    "privateKeys",
    "sessionTokens",
    "csrfTokens",
    "adminKeys",
    "supportContextKeys",
    "crossCustomerData",
  ],
  liabilityFooterRules: [
    "Footer must be calm and trust-preserving, not fear-based.",
    "Footer must state that analysis is based on available provided and observed information at generation time.",
    "Footer must preserve auditability and correction path without claiming audit records are deleted when preservation is required.",
    "Footer must not claim Cendorq is breach-proof, risk-free, free from all responsibility, or certain to produce results.",
  ],
  releaseRules: [
    "Do not release a report unless approval gates pass or an approved audited exception exists.",
    "Do not notify the customer that a report is ready until releaseStatus is approved or customer-safe-ready.",
    "Do not expose report output to a customer without customer ownership, verified access, and report release approval.",
    "Do not let PDF, HTML, dashboard card, notification, or email report summaries drift from the approved report version.",
    "Do not push a next plan unless the recommendation fits the evidence and customer situation.",
  ],
} as const;

export const REPORT_GENERATION_RENDERING_BLOCKED_PATTERNS = [
  "pendingReportPresentedAsFinal",
  "draftReportReleased",
  "rawPayloadRendered",
  "rawEvidenceRendered",
  "rawSecurityPayloadRendered",
  "rawBillingDataRendered",
  "internalNotesRendered",
  "operatorIdentityRendered",
  "riskInternalsRendered",
  "attackerDetailsRendered",
  "promptRendered",
  "secretRendered",
  "sessionTokenRendered",
  "csrfTokenRendered",
  "adminKeyRendered",
  "supportContextKeyRendered",
  "crossCustomerDataRendered",
  "genericAiFillerReport",
  "technicalClutterReport",
  "decorativeChartWithoutDecisionValue",
  "fullCompetitorAnalysisInFreeScan",
  "fakePrecisionForecast",
  "unsupportedCompetitorClaim",
  "unsupportedOutcomePromise",
  "guaranteedRoiReportClaim",
  "guaranteedRevenueReportClaim",
  "guaranteedSecurityOutcomeClaim",
  "guaranteedLegalOutcomeClaim",
  "liabilityFreeReportClaim",
  "auditDeletionClaim",
  "pdfHtmlVersionDrift",
  "unapprovedBusinessLogoRendered",
] as const;

export function getReportGenerationRenderingContract() {
  return REPORT_GENERATION_RENDERING_CONTRACT;
}
