export const SEAMLESS_RESPONSIVE_SYNC_CONTRACT = {
  id: "seamless-responsive-sync-v1",
  name: "Seamless responsive synchronization standard",
  purpose:
    "Keep every Cendorq surface fast, coherent, synchronized, responsive, and protected across public pages, customer dashboard, APIs, notifications, support lifecycle, reports, billing, and operator command surfaces.",
  operatingStandard:
    "Every surface must feel instant, connected, and dependable. The customer should never feel like Cendorq is a set of disconnected pages, stale states, hidden failures, or delayed handoffs.",
  appliesTo: [
    "homepage",
    "free-scan-room",
    "plans-path",
    "signup-and-verification",
    "customer-dashboard",
    "report-vault",
    "notification-center",
    "support-center",
    "support-request",
    "support-status",
    "billing-center",
    "operator-command-center",
    "admin-support-console",
    "report-rendering",
    "email-and-notification-queues",
  ],
  userExperienceRules: [
    "every route needs a clear next step and safe fallback",
    "every protected customer surface needs loading, empty, success, and recoverable error states",
    "every form needs visible progress, validation, safe submission states, and recovery copy",
    "navigation must preserve customer context without exposing protected data",
    "customer-facing terminology must stay consistent across dashboard, notifications, support, billing, reports, and emails",
    "no page should feel like a dead end",
    "mobile and desktop layouts must preserve hierarchy and action clarity",
  ],
  synchronizationRules: [
    "Free Scan completion must connect to dashboard next action",
    "support request submission must connect to support status and notifications",
    "support lifecycle status must connect to notification records and communication plans",
    "billing and plan state must connect to dashboard, report entitlements, and plan comparison",
    "report readiness must connect to vault, dashboard, and notification center",
    "operator actions must create safe history that customer surfaces can project without leaking internals",
    "public plan messaging must match dashboard plan paths and billing entitlements",
  ],
  performanceRules: [
    "critical public and dashboard pages must avoid unnecessary client-only rendering",
    "client components must be small, purposeful, and isolated",
    "lists must be bounded, paginated, filtered, or progressively disclosed",
    "protected API responses should use no-store when data is customer-specific or operator-specific",
    "loading states should be immediate and useful",
    "expensive analysis should be queued, cached safely, or separated from request/response paths",
    "image, animation, and decorative effects must not block understanding or core action",
  ],
  dataFreshnessRules: [
    "customer-owned state must not be shown as current unless sourced from protected APIs or explicit safe projections",
    "stale data needs clear copy or refresh affordance",
    "support status and notification views must use matching status keys and paths",
    "report and billing state must not be guessed on the client",
    "operator history must remain projection-only and bounded",
  ],
  protectionRules: [
    "no browser-exposed protected context keys, session tokens, admin keys, or support secrets",
    "no localStorage or sessionStorage for protected customer state",
    "no raw payloads, raw evidence, raw billing data, raw security data, internal notes, operator identities, or risk internals in customer surfaces",
    "cross-customer state must be blocked by server-side ownership checks",
    "state-changing APIs require guarded server-side validation and safe failures",
  ],
  commandCenterRules: [
    "operator surfaces must show which section, gate, role, and projection is active",
    "read-only review must remain visually and functionally separate from guarded mutation",
    "history views must be filtered, bounded, and projection-only",
    "operator result states must show whether a safe record exists without exposing private internals",
  ],
  releaseRules: [
    "every sync or responsiveness layer requires validation before merge",
    "Vercel/deployment checks must pass before merge",
    "failed checks must be patched directly, not bypassed",
    "new state handoffs must include a validation rule for the handoff",
    "any new surface must inherit the platform interface excellence and most-pristine standards",
  ],
} as const;

export const SEAMLESS_RESPONSIVE_SYNC_HARD_LOCKS = [
  "no disconnected customer journey",
  "no stale protected customer state presented as live truth",
  "no unbounded customer or operator lists",
  "no form without recoverable validation states",
  "no protected API without safe failure behavior",
  "no command-center mutation without clear section, gate, role, projection, and record posture",
  "no public conversion copy that contradicts dashboard, billing, support, or report paths",
  "no new page without mobile-responsive hierarchy and accessible focus states",
] as const;

export const SEAMLESS_RESPONSIVE_SYNC_BLOCKED_PATTERNS = [
  "localStorage",
  "sessionStorage",
  "rawPayload",
  "rawEvidence",
  "rawSecurityPayload",
  "rawBillingData",
  "internalNotes",
  "operatorIdentity",
  "riskScoringInternals",
  "sessionToken",
  "csrfToken",
  "x-support-admin-key",
  "x-cendorq-customer-context",
  "CUSTOMER_SUPPORT_CONTEXT_KEY",
  "SUPPORT_CONSOLE_READ_KEY",
  "unboundedList",
  "skipLoadingState",
  "skipErrorState",
  "bypassOwnershipCheck",
  "disableNoStore",
] as const;
