export const VERIFIED_WELCOME_EMAIL_CONTRACT = {
  id: "verified-welcome-email-contract",
  templateKey: "welcome-verified",
  sender: "Cendorq Support <support@cendorq.com>",
  purpose:
    "Send exactly one welcome and inbox-confirmation email after verified account creation so every free or paid customer can receive Cendorq in their main inbox path and reach the dashboard, Free Scan, notifications, report vault, billing, plans, and support without unsafe promises or duplicate noise.",
  planCoverage:
    "Applies once to every customer identity across Free Scan, Deep Review, Build Fix, Ongoing Control, direct purchase, linear purchase, late add-on, and support-only entry paths. Do not require a second inbox confirmation when the customer later buys another plan.",
  inboxPlacementStandard: [
    "Treat first verified welcome as the one-time inbox confirmation handshake for every customer, free or paid.",
    "Optimize for primary inbox delivery with authenticated sender identity, plain trustworthy copy, clear customer-recognized purpose, low-link density, no hype, no fake urgency, and no promotional overload.",
    "Ask the customer once to confirm they can receive Cendorq messages and, if needed, move the email to the main inbox or save Cendorq Support as a trusted sender.",
    "Never promise guaranteed inbox placement because mailbox providers and customer settings are outside Cendorq's absolute control.",
    "Use in-app dashboard reminders if the first inbox confirmation is not completed, but do not create repeated email confirmation loops.",
  ],
  sendWhen: [
    "customer account exists server-side",
    "email verified flag is true",
    "welcome sent flag is false",
    "inbox confirmation sent flag is false",
    "account is not locked or disabled",
    "safe customer projection is ready",
    "dashboard route is available",
  ],
  suppressWhen: [
    "welcome sent flag is true",
    "inbox confirmation sent flag is true",
    "email verified flag is false",
    "verification token is pending, expired, invalid, consumed, or mismatched",
    "account is locked or disabled",
    "customer id mapping is missing",
    "dashboard route is unavailable",
    "suppression key blocks transactional welcome",
  ],
  requiredPersonalization: [
    "customer first name when available",
    "business name when available",
    "dashboard path",
    "Free Scan path",
    "support contact",
    "plan selected when available",
  ],
  requiredCtas: [
    { label: "Open dashboard", path: "/dashboard" },
    { label: "Confirm this inbox", path: "/dashboard/notifications" },
    { label: "Start Free Scan", path: "/free-check" },
  ],
  requiredTrustElements: [
    "dashboard is private",
    "Free Scan is the first guided step when no paid plan has been selected",
    "notifications and report vault will show status",
    "support center is available for safe questions",
    "billing and plans remain separate from support-message payment collection",
    "Cendorq sends important report, billing, support, and plan-status messages from the approved sender identity",
  ],
  requiredAuditEvents: [
    "welcome-email-evaluated",
    "welcome-email-sent",
    "welcome-email-suppressed",
    "welcome-email-delivery-failed",
    "inbox-confirmation-evaluated",
    "inbox-confirmation-sent",
    "inbox-confirmation-completed",
    "inbox-confirmation-suppressed",
  ],
  postSendState: [
    "set welcome sent flag true only after accepted provider send result",
    "set inbox confirmation sent flag true only after accepted provider send result",
    "set inbox confirmation completed flag true only after customer confirmation signal or dashboard confirmation action",
    "store provider message id hash when available",
    "store sent timestamp",
    "store template version",
    "store audit reason",
    "store plan at first confirmation without exposing raw plan provider payload",
  ],
  safeCopyRules: [
    "Use calm luxury onboarding language, not fake urgency.",
    "Explain that dashboard, notifications, and report vault keep the customer journey connected.",
    "Explain that confirming this inbox helps future report, billing, support, and plan-status messages arrive where the customer can see them.",
    "If needed, ask the customer to move the message to the main inbox or save Cendorq Support as a trusted sender, without claiming provider-level inbox placement control.",
    "Do not imply the Free Scan is final analysis before submission and release state exist.",
    "Do not promise ROI, revenue, legal outcomes, refund outcomes, billing changes, security outcomes, report changes, inbox placement, or deliverability outcomes.",
    "Do not include raw provider payloads, raw customer payloads, raw evidence, raw security payloads, raw billing data, internal notes, operator identities, risk-scoring internals, attacker details, prompts, secrets, passwords, API keys, private keys, session tokens, CSRF tokens, admin keys, or support context keys.",
  ],
} as const;

export const VERIFIED_WELCOME_EMAIL_BLOCKED_PATTERNS = [
  "welcomeEmailDuplicate",
  "welcomeEmailBeforeVerification",
  "welcomeEmailWithoutDashboardPath",
  "welcomeEmailWithoutFreeScanPath",
  "welcomeEmailWithoutAuditEvent",
  "welcomeSentFlagBeforeProviderAcceptance",
  "inboxConfirmationDuplicate",
  "inboxConfirmationRequiredPerPlan",
  "inboxConfirmationBeforeVerification",
  "inboxConfirmationWithoutDashboardPath",
  "inboxConfirmationWithoutAuditEvent",
  "inboxConfirmationSentFlagBeforeProviderAcceptance",
  "guaranteedInboxPlacement",
  "primaryInboxGuarantee",
  "rawProviderPayloadInEmail",
  "rawCustomerPayloadInEmail",
  "rawEvidenceInEmail",
  "rawBillingDataInEmail",
  "internalNotesInEmail",
  "operatorIdentityInEmail",
  "riskInternalsInEmail",
  "attackerDetailsInEmail",
  "promptInEmail",
  "secretInEmail",
  "sessionTokenInEmail",
  "csrfTokenInEmail",
  "adminKeyInEmail",
  "supportContextKeyInEmail",
  "guaranteedOutcomeEmail",
  "guaranteedRoiEmail",
  "fakeUrgencyEmail",
] as const;

export function getVerifiedWelcomeEmailContract() {
  return VERIFIED_WELCOME_EMAIL_CONTRACT;
}
