import Link from "next/link";

const SCORES = [
  ["Understand", "91", "cyan"],
  ["Trust", "58", "red"],
  ["Compare", "84", "cyan"],
  ["Act", "52", "red"],
] as const;
const SOURCES = ["Website", "Reviews", "Listings", "FAQs", "Schema", "Offers"] as const;
const REPAIRS = ["Fix request path", "Move proof near CTA", "Clarify offers"] as const;

export function CendorqProductMotionCinema() {
  return (
    <section data-cendorq-motion-cinema="dashboard-demo-clear" className="relative isolate overflow-hidden bg-[#eef8ff] px-4 py-14 text-slate-950 sm:px-6 lg:px-8 lg:py-20" aria-label="Cendorq guided dashboard demo">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_12%,rgba(186,230,253,.94),transparent_30%),radial-gradient(circle_at_82%_16%,rgba(219,234,254,.9),transparent_36%),linear-gradient(180deg,#fbfeff_0%,#eaf8ff_54%,#f7fbff_100%)]" />
      <div className="mx-auto grid max-w-[104rem] gap-10 lg:grid-cols-[0.74fr_1.26fr] lg:items-center">
        <div className="max-w-2xl">
          <p className="inline-flex rounded-full border border-cyan-100 bg-white/80 px-4 py-2 text-xs font-black uppercase tracking-[0.22em] text-sky-700 shadow-[0_12px_34px_rgba(14,165,233,.1)]">Guided product demo</p>
          <h2 className="mt-5 text-[clamp(2.45rem,8vw,5.25rem)] font-black leading-[.94] tracking-[-.078em] text-slate-950">Show the owner what Cendorq found.</h2>
          <p className="mt-5 max-w-xl text-base font-semibold leading-7 text-slate-600 sm:text-lg sm:leading-8">A better demo should feel like a real walkthrough: run the scan, score the signals, enter the customer dashboard, then show the repair queue.</p>
          <div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/free-check" className="inline-flex min-h-[3.25rem] items-center justify-center rounded-2xl border border-cyan-100 bg-[linear-gradient(135deg,#67e8f9,#60a5fa_55%,#a78bfa)] px-7 py-3 text-sm font-black text-slate-950 shadow-[0_18px_54px_rgba(14,165,233,.22),inset_0_1px_0_rgba(255,255,255,.86)]">Run Free Scan</Link><Link href="/plans" className="inline-flex min-h-[3.25rem] items-center justify-center rounded-2xl border border-cyan-100 bg-white/74 px-7 py-3 text-sm font-black text-slate-950 shadow-[0_14px_38px_rgba(15,23,42,.08),inset_0_1px_0_rgba(255,255,255,.9)]">View Plans</Link></div>
        </div>

        <div className="relative overflow-hidden rounded-[2.15rem] border border-white/80 bg-white/76 p-2 shadow-[0_30px_90px_rgba(15,23,42,.18),inset_0_1px_0_rgba(255,255,255,.9)] backdrop-blur-xl sm:p-3">
          <div className="overflow-hidden rounded-[1.85rem] border border-slate-200/80 bg-[#f8fdff] shadow-[inset_0_1px_0_rgba(255,255,255,.92)]">
            <div className="flex items-center justify-between gap-3 border-b border-slate-200/80 bg-white/90 px-4 py-3"><div className="flex items-center gap-2"><span className="h-3 w-3 rounded-full bg-rose-300" /><span className="h-3 w-3 rounded-full bg-amber-300" /><span className="h-3 w-3 rounded-full bg-emerald-300" /></div><div className="hidden rounded-full border border-slate-200 bg-slate-50 px-5 py-2 text-xs font-bold text-slate-500 sm:block">cendorq.com/customer-dashboard</div><div className="rounded-full border border-cyan-100 bg-cyan-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-sky-700">demo</div></div>
            <div className="grid grid-cols-4 border-b border-slate-200/80 bg-white/82 px-3 py-3 text-[10px] font-black uppercase tracking-[.14em] text-slate-500"><Stage label="1 Scan" /><Stage label="2 Score" /><Stage label="3 Dashboard" /><Stage label="4 Repair" /></div>
            <div className="relative min-h-[39rem] overflow-hidden bg-[radial-gradient(circle_at_80%_16%,rgba(186,230,253,.58),transparent_34%),linear-gradient(180deg,#ffffff_0%,#eef8ff_100%)] p-4 sm:p-5 lg:min-h-[36rem]">
              <Cursor />
              <div className="scene-a absolute inset-4 grid gap-4 lg:grid-cols-[.86fr_1.14fr] sm:inset-5"><Panel title="Free scan intake" heading="Start with what customers see."><div className="mt-6 grid gap-3">{['Business name','Website','Service area','Main service'].map(x=><div key={x} className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-500">{x}</div>)}</div><div className="mt-5 rounded-2xl bg-slate-950 px-5 py-4 text-center text-sm font-black text-white shadow-[0_18px_42px_rgba(15,23,42,.18)]">Run Free Scan</div></Panel><Panel title="Sources collected" heading="7 public signals scanned"><div className="mt-5 grid gap-3 sm:grid-cols-2">{SOURCES.map((x,i)=><Metric key={x} label={x} value={i===1?'58%':i===5?'55%':i===3?'64%':'82%'} red={i===1||i===5}/>)}</div></Panel></div>
              <div className="scene-b absolute inset-4 grid gap-4 lg:grid-cols-[1fr_.9fr] sm:inset-5"><Panel title="Readiness scoring" heading="Four signals decide the first repair."><div className="mt-5 grid gap-3 sm:grid-cols-2">{SCORES.map(([l,v,t])=><Score key={l} label={l} value={v} red={t==='red'} />)}</div></Panel><Panel title="Meaning" heading="Trust and action are blocking the buyer."><div className="mt-5 rounded-2xl border border-rose-100 bg-rose-50 p-4"><p className="text-[10px] font-black uppercase tracking-[.18em] text-rose-700">Choice gap</p><p className="mt-2 text-3xl font-black text-slate-950">2 blockers</p><p className="mt-1 text-xs font-bold text-slate-600">Trust and request path need repair first.</p></div></Panel></div>
              <div className="scene-c absolute inset-4 grid gap-4 lg:grid-cols-[13rem_1fr] sm:inset-5"><aside className="rounded-[1.55rem] border border-slate-200 bg-white/94 p-4 shadow-[0_18px_54px_rgba(15,23,42,.09)]"><p className="text-sm font-black text-slate-950">Cendorq</p><div className="mt-6 grid gap-2 text-xs font-black text-slate-500"><span className="rounded-xl bg-slate-950 px-3 py-2 text-white">Dashboard</span><span className="rounded-xl px-3 py-2">Reports</span><span className="rounded-xl bg-cyan-50 px-3 py-2 text-sky-700">Repair Queue</span><span className="rounded-xl px-3 py-2">Billing</span></div></aside><main className="rounded-[1.55rem] border border-slate-200 bg-white/94 p-5 shadow-[0_18px_54px_rgba(15,23,42,.09)]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-sky-700">Customer dashboard</p><h3 className="mt-2 text-4xl font-black leading-[.95] tracking-[-.06em] text-slate-950">Repair queue is ready.</h3></div><div className="rounded-2xl bg-cyan-50 px-5 py-4 text-center"><p className="text-[10px] font-black uppercase tracking-[.18em] text-sky-700">Readiness</p><p className="text-4xl font-black text-slate-950">68</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-4">{SCORES.map(([l,v,t])=><Score key={l} label={l} value={v} red={t==='red'} compact />)}</div><div className="mt-5 grid gap-3">{REPAIRS.map((x,i)=><div key={x} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-slate-950 text-sm font-black text-white">{i+1}</span><div><p className="text-base font-black tracking-[-.03em] text-slate-950">{x}</p><p className="mt-1 text-xs font-bold leading-5 text-slate-600">Recommended next action for the owner.</p></div></div></div>)}</div></main></div>
            </div>
          </div>
        </div>
      </div>
      <style>{`@keyframes a{0%,25%{opacity:1;transform:translateY(0) scale(1)}31%,100%{opacity:0;transform:translateY(-18px) scale(.985)}}@keyframes b{0%,28%{opacity:0;transform:translateY(22px) scale(.985)}34%,60%{opacity:1;transform:translateY(0) scale(1)}66%,100%{opacity:0;transform:translateY(-18px) scale(.985)}}@keyframes c{0%,62%{opacity:0;transform:translateY(24px) scale(.985)}69%,100%{opacity:1;transform:translateY(0) scale(1)}}@keyframes cur{0%,16%{left:17%;top:76%;transform:rotate(-8deg)}33%,50%{left:66%;top:41%;transform:rotate(-3deg)}72%,100%{left:56%;top:20%;transform:rotate(-5deg)}}@keyframes fill{0%{transform:scaleX(.18)}45%,100%{transform:scaleX(1)}}.scene-a{animation:a 15s ease-in-out infinite}.scene-b{animation:b 15s ease-in-out infinite}.scene-c{animation:c 15s ease-in-out infinite}.demo-cursor{animation:cur 15s ease-in-out infinite}.demo-fill{transform-origin:left;animation:fill 4s ease-in-out infinite}@media (prefers-reduced-motion:reduce){.scene-a,.scene-b,.scene-c,.demo-cursor,.demo-fill{animation:none}.scene-b,.scene-c{opacity:1;position:relative!important;transform:none!important}.scene-a{position:relative!important}}`}</style>
    </section>
  );
}

function Stage({label}:{label:string}){return <div className="text-center"><span className="inline-flex rounded-full bg-slate-50 px-3 py-1.5 shadow-[inset_0_1px_0_rgba(255,255,255,.9)]">{label}</span></div>}
function Cursor(){return <svg className="demo-cursor absolute z-30 h-10 w-10 drop-shadow-[0_18px_28px_rgba(15,23,42,.26)]" viewBox="0 0 34 34" fill="none" aria-hidden="true"><path d="M5 3.8 29.2 17 18.4 19.1 14.1 29.4 5 3.8Z" fill="#020617" stroke="white" strokeWidth="2"/><path d="M17.8 19.2 23.6 29.1" stroke="white" strokeWidth="1.5" strokeLinecap="round"/></svg>}
function Panel({title,heading,children}:{title:string;heading:string;children:React.ReactNode}){return <div className="rounded-[1.55rem] border border-slate-200 bg-white/94 p-5 shadow-[0_18px_54px_rgba(15,23,42,.1)]"><p className="text-[10px] font-black uppercase tracking-[.22em] text-sky-700">{title}</p><h3 className="mt-3 text-4xl font-black leading-[.95] tracking-[-.06em] text-slate-950">{heading}</h3>{children}</div>}
function Metric({label,value,red}:{label:string;value:string;red?:boolean}){return <div className="rounded-2xl border border-white/80 bg-white/88 p-4 text-sm font-black text-slate-800"><div className="flex items-center justify-between"><span>{label}</span><span className="text-slate-500">{value}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><span className={`demo-fill block h-full rounded-full ${red?'w-[55%] bg-rose-400':'w-[82%] bg-cyan-400'}`}/></div></div>}
function Score({label,value,red,compact=false}:{label:string;value:string;red?:boolean;compact?:boolean}){return <div className={`rounded-2xl border p-4 ${red?'border-rose-100 bg-rose-50':'border-cyan-100 bg-cyan-50'}`}><div className="flex items-start justify-between gap-3"><div><p className={`text-[10px] font-black uppercase tracking-[.18em] ${red?'text-rose-700':'text-sky-700'}`}>{label}</p>{!compact?<p className="mt-1 text-xs font-bold leading-5 text-slate-600">{red?'Needs repair':'Strong signal'}</p>:null}</div><span className="text-4xl font-black tracking-[-.06em] text-slate-950">{value}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><span className={`block h-full rounded-full ${red?'w-[58%] bg-rose-400':'w-[88%] bg-cyan-400'}`}/></div></div>}
