export type CommandCenterPanelRegistryItem = {
  key: string;
  label: string;
  order: number;
  layer: "overview" | "security" | "control" | "truth" | "intelligence" | "operations";
  visibility: "private-gated";
  dataExposure: "metadata-only";
  operatorPurpose: string;
  protectionNote: string;
};

export const COMMAND_CENTER_PANEL_REGISTRY = [
  {
    key: "hero-readiness-summary",
    label: "Command Center readiness summary",
    order: 10,
    layer: "overview",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show high-level readiness counts for protected operating areas.",
    protectionNote: "Shows counts only; no secrets, records, or customer data.",
  },
  {
    key: "operating-map",
    label: "Operating map",
    order: 20,
    layer: "overview",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Keep the cockpit organized into Control, Truth, Intelligence, and Operations layers.",
    protectionNote: "Shows roadmap direction only; no live operational data.",
  },
  {
    key: "security-posture",
    label: "Security posture",
    order: 30,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Expose required controls, forbidden claims, and core protection policies.",
    protectionNote: "Shows policy names only; blocks absolute security claims.",
  },
  {
    key: "operator-readiness-matrix",
    label: "Operator readiness matrix",
    order: 40,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Summarize readiness posture by protected operating area.",
    protectionNote: "Shows config counts and blocked paths only; no secret values.",
  },
  {
    key: "module-roadmap",
    label: "Module roadmap",
    order: 50,
    layer: "operations",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show private module build order and required permissions.",
    protectionNote: "Shows module metadata only; planned modules remain non-operational shells.",
  },
  {
    key: "plan-control",
    label: "Plan control",
    order: 60,
    layer: "control",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show how plans can be edited, previewed, tested, approved, and supported.",
    protectionNote: "No customer-facing output without approval.",
  },
  {
    key: "optimization-library",
    label: "Optimization library",
    order: 70,
    layer: "control",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show evidence-backed optimization method controls.",
    protectionNote: "Recommendations must stay evidence-backed and plan-scoped.",
  },
  {
    key: "customer-output-approval",
    label: "Customer output approval",
    order: 80,
    layer: "control",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show review, preview, approval, and audit requirements for customer-facing output.",
    protectionNote: "Blocks customer output until approval gates pass.",
  },
  {
    key: "benchmark-intelligence",
    label: "Benchmark intelligence",
    order: 90,
    layer: "intelligence",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show benchmark comparison and self-evolution controls.",
    protectionNote: "Benchmark intelligence must be source-backed and reviewed.",
  },
  {
    key: "benchmark-evidence",
    label: "Benchmark evidence",
    order: 100,
    layer: "truth",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show source evidence readiness rules for benchmark use.",
    protectionNote: "No benchmark is proof by itself.",
  },
  {
    key: "report-truth-methodology",
    label: "Report truth methodology",
    order: 110,
    layer: "truth",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show how report claims, recommendations, and monthly controls stay evidence-backed.",
    protectionNote: "Unsupported claims are blocked.",
  },
  {
    key: "ai-manager-version-registry",
    label: "AI manager version registry",
    order: 120,
    layer: "intelligence",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show model, prompt, evaluation, scoring, and report policy version controls.",
    protectionNote: "No unapproved AI manager version can produce customer-facing output.",
  },
  {
    key: "test-record-classes",
    label: "Test record classes",
    order: 130,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Separate benchmark, synthetic, regression, live customer, and archived records.",
    protectionNote: "Test records cannot count as revenue, progress, or delivery unless explicitly live-customer class.",
  },
  {
    key: "ai-manager-command-queue",
    label: "AI manager command queue",
    order: 140,
    layer: "intelligence",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show future AI manager command controls and blocked actions.",
    protectionNote: "AI cannot send customer output or change live records without review.",
  },
  {
    key: "ai-history",
    label: "AI command audit trail",
    order: 150,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show required AI command audit history fields and event classes.",
    protectionNote: "Audit metadata excludes secrets and private source values.",
  },
  {
    key: "readiness-checklist",
    label: "Private configuration checklist",
    order: 160,
    layer: "operations",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show protected readiness areas, capability counts, and pending checks.",
    protectionNote: "Shows server-side config names and counts only, never values.",
  },
] as const satisfies readonly CommandCenterPanelRegistryItem[];

export function getCommandCenterPanelRegistry() {
  return COMMAND_CENTER_PANEL_REGISTRY;
}
