export type CommandCenterPanelRegistryItem = {
  key: string;
  label: string;
  order: number;
  layer: "overview" | "security" | "control" | "truth" | "intelligence" | "operations";
  visibility: "private-gated";
  dataExposure: "metadata-only";
  operatorPurpose: string;
  protectionNote: string;
};

export const COMMAND_CENTER_PANEL_REGISTRY = [
  { key: "hero-readiness-summary", label: "Command Center readiness summary", order: 10, layer: "overview", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show high-level readiness counts for protected operating areas.", protectionNote: "Shows counts only; no secrets, records, customer data, or raw intelligence." },
  { key: "operating-map", label: "Operating map", order: 20, layer: "overview", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Keep the cockpit organized into Control, Truth, Intelligence, and Operations layers.", protectionNote: "Shows roadmap direction only; no live operational data." },
  { key: "security-posture", label: "Security posture", order: 30, layer: "security", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Expose required controls, forbidden claims, and core protection policies.", protectionNote: "Shows policy names only; blocks absolute security claims and raw intelligence exposure." },
  { key: "operator-control-interface", label: "Operator control interface", order: 40, layer: "control", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show operator control boundaries and blocked production shortcuts.", protectionNote: "Controls are metadata-only and cannot bypass production authorization." },
  { key: "admin-command-center-control", label: "Admin Command Center control", order: 45, layer: "control", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show safe admin command-center projection routes, shared access posture, no-store responses, and read-only review surfaces.", protectionNote: "Admin command-center projections stay preview-gated, safe-summary-only, no-store, and cannot mutate production or expose raw/private payloads." },
  { key: "platform-launch-readiness", label: "Platform launch readiness", order: 50, layer: "operations", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show launch readiness categories and blocked launch posture.", protectionNote: "Launch status is posture metadata only and does not approve launch." },
  { key: "production-launch-checklist", label: "Production launch checklist", order: 60, layer: "operations", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Track launch checklist readiness without exposing protected configuration values.", protectionNote: "Checklist entries remain safe summaries, never live secrets or customer data." },
  { key: "production-launch-final-blocker", label: "Production launch final blocker", order: 70, layer: "operations", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show final blocked launch posture until all required review gates pass.", protectionNote: "Final blocker cannot be bypassed by panel display or owner evidence alone." },
  { key: "launch-evidence", label: "Launch evidence", order: 80, layer: "truth", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show safe launch evidence summaries and missing evidence classes.", protectionNote: "Evidence remains summarized and does not expose raw audit or provider payloads." },
  { key: "production-smoke-target", label: "Production smoke target", order: 90, layer: "operations", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show safe smoke target expectations for public, protected, and command-center paths.", protectionNote: "Smoke targets are safe projections only and cannot mutate production." },
  { key: "agent-operating-system", label: "Agent operating system", order: 100, layer: "control", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show controlled agent authority lanes and release-captain validation requirements.", protectionNote: "Agents cannot merge, launch, approve reports, or approve customer-facing claims." },
  { key: "cendorq-agent-intelligence-playbooks", label: "Cendorq agent intelligence playbooks", order: 101, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show agent playbook coverage, plan-specific intelligence lanes, and blocked approval boundaries.", protectionNote: "Playbooks remain metadata-only and cannot expose prompts, raw research, internal notes, customer data, or approve customer-facing output." },
  { key: "agent-mission-operating-engine", label: "Agent mission operating engine", order: 105, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show plan-triggered agent missions, required report output, required report visuals, structured findings, chief-agent review, release-captain approval gates, next-plan motion, and blocked customer claims.", protectionNote: "Agent missions remain metadata-only until persistence, source refs, chief review, report visual standards, customer wording review, and release-captain approval are configured; agents cannot approve customer-facing output or mutate production." },
  { key: "agent-mission-records-runtime", label: "Agent mission records runtime", order: 106, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show plan-triggered mission records with intake links, missing inputs, assigned chief agents, finding posture, chief review state, captain review state, blocked claims, and append-only audit events.", protectionNote: "Agent mission records stay safe-summary-only and cannot expose raw customer payloads, credentials, payment data, provider payloads, prompts, internal notes, or cross-customer records." },
  { key: "agent-mission-review-gates-runtime", label: "Agent mission review gates runtime", order: 107, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show finding submission acceptance, chief-agent consolidation, release-captain approval posture, reason codes, blocked claims, and gated customer-safe output state.", protectionNote: "Review gates stay metadata-only; chief agents cannot approve customer output, and release-captain approval cannot bypass delivery, billing, report, or production gates." },
  { key: "agent-mission-live-execution-runtime", label: "Agent mission live execution runtime", order: 108, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show live mission execution posture, blocked mutation states, evidence requirements, and review-gated customer output readiness.", protectionNote: "Live execution remains safe-summary-only and cannot mutate production, contact providers, approve reports, send customer output, or expose raw operational payloads." },
  { key: "agent-mission-finding-submission-runtime", label: "Agent mission finding submission runtime", order: 109, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show assigned-agent finding submission posture, accepted finding recomputation, quality score movement, queue-state movement, output assembly posture, and blocked reason codes.", protectionNote: "Finding submission stays safe-summary-only and cannot approve customer output, report release, production mutation, delivery email, billing action, or provider action." },
  { key: "agent-mission-chief-review-runtime", label: "Agent mission chief review runtime", order: 110, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show chief-agent review posture, consolidated finding state, unresolved blockers, captain review readiness, and blocked customer claims.", protectionNote: "Chief review remains metadata-only and cannot bypass release-captain approval, billing, delivery, report, provider, or production gates." },
  { key: "owner-configuration-evidence", label: "Owner configuration evidence", order: 120, layer: "security", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show safe owner configuration evidence posture for auth, payments, protected runtime, launch contact, and support identity.", protectionNote: "Owner evidence is safe-summary-only and never creates launch or security approval by itself." },
  { key: "owner-configuration-workflow", label: "Owner configuration workflow", order: 130, layer: "security", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show evidence recorded state, owner approval posture, release-captain review posture, and workflow blockers.", protectionNote: "Release-captain review remains required and still does not create launch approval by itself." },
  { key: "operator-readiness-matrix", label: "Operator readiness matrix", order: 140, layer: "security", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Summarize readiness posture by protected operating area.", protectionNote: "Shows config counts and blocked paths only; no secret values." },
  { key: "panel-index", label: "Panel index", order: 150, layer: "overview", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show the private cockpit panel registry and ordering metadata.", protectionNote: "Panel metadata only; no live records, secrets, or private evidence." },
  { key: "validation-registry", label: "Validation registry", order: 160, layer: "security", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show which validation scripts protect each private cockpit boundary.", protectionNote: "Shows guardrail metadata only; no logs, secrets, or live validation output." },
  { key: "module-roadmap", label: "Module roadmap", order: 170, layer: "operations", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show private module build order and required permissions.", protectionNote: "Shows module metadata only; planned modules remain non-operational shells." },
  { key: "plan-control", label: "Plan control", order: 180, layer: "control", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show how plans can be edited, previewed, tested, approved, and supported.", protectionNote: "No customer-facing output without approval." },
  { key: "plan-delivery-orchestration", label: "Plan delivery orchestration", order: 185, layer: "control", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show plan delivery proof gates, owner/release-captain review posture, and blocked unsafe delivery patterns.", protectionNote: "Plan delivery orchestration stays metadata-only and cannot send customer output or approve paid recommendations by itself." },
  { key: "plan-routing-runtime", label: "Plan routing runtime", order: 186, layer: "control", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show safe plan routing runtime posture and handoff boundaries between Free Scan, Deep Review, Build Fix, and Ongoing Control.", protectionNote: "Plan routing stays safe-summary-only and cannot create entitlement, billing, or customer-facing approval drift." },
  { key: "paid-report-delivery-ops", label: "Paid report delivery ops", order: 187, layer: "operations", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show paid report production status, attachment generation, release approval, email delivery, resend controls, and delivery audit posture.", protectionNote: "Paid report delivery ops stay metadata-only and cannot expose raw evidence, customer secrets, provider payloads, prompts, internal notes, payment data, or cross-customer records." },
  { key: "optimization-library", label: "Optimization library", order: 190, layer: "control", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show evidence-backed optimization method controls.", protectionNote: "Recommendations must stay evidence-backed and plan-scoped." },
  { key: "customer-output-approval", label: "Customer output approval", order: 200, layer: "control", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show review, preview, approval, and audit requirements for customer-facing output.", protectionNote: "Blocks customer output until approval gates pass." },
  { key: "benchmark-intelligence", label: "Benchmark intelligence", order: 210, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show benchmark comparison and self-evolution controls.", protectionNote: "Benchmark intelligence must be source-backed and reviewed; raw intelligence stays closed." },
  { key: "benchmark-evidence", label: "Benchmark evidence", order: 220, layer: "truth", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show source evidence readiness rules for benchmark use.", protectionNote: "No benchmark is proof by itself." },
  { key: "report-truth-methodology", label: "Report truth methodology", order: 230, layer: "truth", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show how report claims, recommendations, and monthly controls stay evidence-backed.", protectionNote: "Unsupported claims are blocked." },
  { key: "report-evidence-orchestration", label: "Report evidence orchestration", order: 240, layer: "truth", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show evidence source tiers, confidence posture, conflict handling, plan-fit gates, and runtime review state.", protectionNote: "Evidence stays summarized; raw private evidence and customer-facing claims remain blocked until review gates pass." },
  { key: "report-evidence-records", label: "Report evidence records", order: 245, layer: "truth", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show report evidence record projection, append-only persistence posture, records API posture, safe hashes, and approval boundaries.", protectionNote: "Report evidence records remain safe-summary-only and cannot expose raw/private payloads or approve customer-facing output, public report release, paid recommendations, launch, or security readiness." },
  { key: "ai-manager-version-registry", label: "AI manager version registry", order: 250, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show model, prompt, evaluation, scoring, and report policy version controls.", protectionNote: "No unapproved AI manager version can produce customer-facing output." },
  { key: "test-record-classes", label: "Test record classes", order: 260, layer: "security", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Separate benchmark, synthetic, regression, live customer, and archived records.", protectionNote: "Test records cannot count as revenue, progress, or delivery unless explicitly live-customer class." },
  { key: "ai-manager-command-queue", label: "AI manager command queue", order: 270, layer: "intelligence", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show future AI manager command controls and blocked actions.", protectionNote: "AI cannot send customer output or change live records without review." },
  { key: "ai-history", label: "AI command audit trail", order: 280, layer: "security", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show required AI command audit history fields and event classes.", protectionNote: "Audit metadata excludes secrets and private source values." },
  { key: "readiness-checklist", label: "Private configuration checklist", order: 290, layer: "operations", visibility: "private-gated", dataExposure: "metadata-only", operatorPurpose: "Show protected readiness areas, capability counts, and pending checks.", protectionNote: "Shows server-side config names and counts only, never values." },
] as const satisfies readonly CommandCenterPanelRegistryItem[];

export function getCommandCenterPanelRegistry() {
  return COMMAND_CENTER_PANEL_REGISTRY;
}
