export type CommandCenterPanelRegistryItem = {
  key: string;
  label: string;
  order: number;
  layer: "overview" | "security" | "control" | "truth" | "intelligence" | "operations";
  visibility: "private-gated";
  dataExposure: "metadata-only";
  operatorPurpose: string;
  protectionNote: string;
};

export const COMMAND_CENTER_PANEL_REGISTRY = [
  {
    key: "hero-readiness-summary",
    label: "Command Center readiness summary",
    order: 10,
    layer: "overview",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show high-level readiness counts for protected operating areas.",
    protectionNote: "Shows counts only; no secrets, records, or customer data.",
  },
  {
    key: "operating-map",
    label: "Operating map",
    order: 20,
    layer: "overview",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Keep the cockpit organized into Control, Truth, Intelligence, and Operations layers.",
    protectionNote: "Shows roadmap direction only; no live operational data.",
  },
  {
    key: "security-posture",
    label: "Security posture",
    order: 30,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Expose required controls, forbidden claims, and core protection policies.",
    protectionNote: "Shows policy names only; blocks absolute security claims.",
  },
  {
    key: "operator-control-interface",
    label: "Operator control interface",
    order: 40,
    layer: "control",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show operator control boundaries and blocked production shortcuts.",
    protectionNote: "Controls are metadata-only and cannot bypass production authorization.",
  },
  {
    key: "platform-launch-readiness",
    label: "Platform launch readiness",
    order: 50,
    layer: "operations",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show launch readiness categories and blocked launch posture.",
    protectionNote: "Launch status is posture metadata only and does not approve launch.",
  },
  {
    key: "production-launch-checklist",
    label: "Production launch checklist",
    order: 60,
    layer: "operations",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Track launch checklist readiness without exposing protected configuration values.",
    protectionNote: "Checklist entries remain safe summaries, never live secrets or customer data.",
  },
  {
    key: "production-launch-final-blocker",
    label: "Production launch final blocker",
    order: 70,
    layer: "operations",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show final blocked launch posture until all required review gates pass.",
    protectionNote: "Final blocker cannot be bypassed by panel display or owner evidence alone.",
  },
  {
    key: "launch-evidence",
    label: "Launch evidence",
    order: 80,
    layer: "truth",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show safe launch evidence summaries and missing evidence classes.",
    protectionNote: "Evidence remains summarized and does not expose raw audit or provider payloads.",
  },
  {
    key: "production-smoke-target",
    label: "Production smoke target",
    order: 90,
    layer: "operations",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show safe smoke target expectations for public, protected, and command-center paths.",
    protectionNote: "Smoke targets are safe projections only and cannot mutate production.",
  },
  {
    key: "agent-operating-system",
    label: "Agent operating system",
    order: 100,
    layer: "control",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show controlled agent authority lanes and release-captain validation requirements.",
    protectionNote: "Agents cannot merge, launch, approve reports, or approve customer-facing claims.",
  },
  {
    key: "owner-configuration-evidence",
    label: "Owner configuration evidence",
    order: 110,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show safe owner configuration evidence posture for auth, payments, protected runtime, launch contact, and support identity.",
    protectionNote: "Owner evidence is safe-summary-only and never creates launch or security approval by itself.",
  },
  {
    key: "owner-configuration-workflow",
    label: "Owner configuration workflow",
    order: 120,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show evidence recorded state, owner approval posture, release-captain review posture, and workflow blockers.",
    protectionNote: "Release-captain review remains required and still does not create launch approval by itself.",
  },
  {
    key: "operator-readiness-matrix",
    label: "Operator readiness matrix",
    order: 130,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Summarize readiness posture by protected operating area.",
    protectionNote: "Shows config counts and blocked paths only; no secret values.",
  },
  {
    key: "panel-index",
    label: "Panel index",
    order: 140,
    layer: "overview",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show the private cockpit panel registry and ordering metadata.",
    protectionNote: "Panel metadata only; no live records, secrets, or private evidence.",
  },
  {
    key: "validation-registry",
    label: "Validation registry",
    order: 150,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show which validation scripts protect each private cockpit boundary.",
    protectionNote: "Shows guardrail metadata only; no logs, secrets, or live validation output.",
  },
  {
    key: "module-roadmap",
    label: "Module roadmap",
    order: 160,
    layer: "operations",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show private module build order and required permissions.",
    protectionNote: "Shows module metadata only; planned modules remain non-operational shells.",
  },
  {
    key: "plan-control",
    label: "Plan control",
    order: 170,
    layer: "control",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show how plans can be edited, previewed, tested, approved, and supported.",
    protectionNote: "No customer-facing output without approval.",
  },
  {
    key: "optimization-library",
    label: "Optimization library",
    order: 180,
    layer: "control",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show evidence-backed optimization method controls.",
    protectionNote: "Recommendations must stay evidence-backed and plan-scoped.",
  },
  {
    key: "customer-output-approval",
    label: "Customer output approval",
    order: 190,
    layer: "control",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show review, preview, approval, and audit requirements for customer-facing output.",
    protectionNote: "Blocks customer output until approval gates pass.",
  },
  {
    key: "benchmark-intelligence",
    label: "Benchmark intelligence",
    order: 200,
    layer: "intelligence",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show benchmark comparison and self-evolution controls.",
    protectionNote: "Benchmark intelligence must be source-backed and reviewed.",
  },
  {
    key: "benchmark-evidence",
    label: "Benchmark evidence",
    order: 210,
    layer: "truth",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show source evidence readiness rules for benchmark use.",
    protectionNote: "No benchmark is proof by itself.",
  },
  {
    key: "report-truth-methodology",
    label: "Report truth methodology",
    order: 220,
    layer: "truth",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show how report claims, recommendations, and monthly controls stay evidence-backed.",
    protectionNote: "Unsupported claims are blocked.",
  },
  {
    key: "ai-manager-version-registry",
    label: "AI manager version registry",
    order: 230,
    layer: "intelligence",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show model, prompt, evaluation, scoring, and report policy version controls.",
    protectionNote: "No unapproved AI manager version can produce customer-facing output.",
  },
  {
    key: "test-record-classes",
    label: "Test record classes",
    order: 240,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Separate benchmark, synthetic, regression, live customer, and archived records.",
    protectionNote: "Test records cannot count as revenue, progress, or delivery unless explicitly live-customer class.",
  },
  {
    key: "ai-manager-command-queue",
    label: "AI manager command queue",
    order: 250,
    layer: "intelligence",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show future AI manager command controls and blocked actions.",
    protectionNote: "AI cannot send customer output or change live records without review.",
  },
  {
    key: "ai-history",
    label: "AI command audit trail",
    order: 260,
    layer: "security",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show required AI command audit history fields and event classes.",
    protectionNote: "Audit metadata excludes secrets and private source values.",
  },
  {
    key: "readiness-checklist",
    label: "Private configuration checklist",
    order: 270,
    layer: "operations",
    visibility: "private-gated",
    dataExposure: "metadata-only",
    operatorPurpose: "Show protected readiness areas, capability counts, and pending checks.",
    protectionNote: "Shows server-side config names and counts only, never values.",
  },
] as const satisfies readonly CommandCenterPanelRegistryItem[];

export function getCommandCenterPanelRegistry() {
  return COMMAND_CENTER_PANEL_REGISTRY;
}
