export type CommandCenterValidationRegistryItem = {
  key: string;
  label: string;
  scriptPath: string;
  category: "route" | "security" | "schema" | "cockpit" | "ai" | "smoke" | "docs";
  requiredInValidateRoutes: true;
  protectedBoundary: string;
  failureMeaning: string;
};

export const COMMAND_CENTER_VALIDATION_REGISTRY = [
  {
    key: "command-center-migrations",
    label: "Command Center migrations",
    scriptPath: "src/scripts/validate-command-center-migrations.mjs",
    category: "schema",
    requiredInValidateRoutes: true,
    protectedBoundary: "migration files and database bootstrap shape",
    failureMeaning: "Schema or migration boundaries drifted from the expected Command Center foundation.",
  },
  {
    key: "command-center-schema",
    label: "Command Center schema",
    scriptPath: "src/scripts/validate-command-center-schema.mjs",
    category: "schema",
    requiredInValidateRoutes: true,
    protectedBoundary: "protected tables, relationships, and audit anchors",
    failureMeaning: "The durable data model no longer matches the private operating system contract.",
  },
  {
    key: "command-center-readiness",
    label: "Command Center readiness",
    scriptPath: "src/scripts/validate-command-center-readiness.mjs",
    category: "route",
    requiredInValidateRoutes: true,
    protectedBoundary: "required server-side configuration and protected data areas",
    failureMeaning: "A required readiness area, protected scope, or server configuration guard is missing.",
  },
  {
    key: "security-posture",
    label: "Security posture",
    scriptPath: "src/scripts/validate-command-center-security-posture.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "defense-in-depth, denied public exposure, and route composition shell",
    failureMeaning: "A security posture or route-composition guard has regressed.",
  },
  {
    key: "panel-registry",
    label: "Panel registry coverage",
    scriptPath: "src/scripts/validate-command-center-panel-registry.mjs",
    category: "cockpit",
    requiredInValidateRoutes: true,
    protectedBoundary: "visible cockpit panel to registry-key mapping",
    failureMeaning: "A visible panel is missing from the private metadata-only registry or ordering changed unsafely.",
  },
  {
    key: "panel-safety",
    label: "Panel safety",
    scriptPath: "src/scripts/validate-command-center-panel-safety.mjs",
    category: "cockpit",
    requiredInValidateRoutes: true,
    protectedBoundary: "full current command-center cockpit panel set, including admin projections, launch readiness, owner workflow, plan delivery/routing, and report evidence records, stays server-rendered, metadata-only, private-gated, and free of browser storage, browser-only APIs, direct environment access, raw/private payload fields, token patterns, unsafe guarantees, and public exposure drift",
    failureMeaning: "A command-center panel may have drifted into client-only behavior, browser storage, browser-only APIs, direct env access, raw/private payload exposure, secret/token leakage, unsafe guarantee language, missing registry alignment, or public exposure regression.",
  },
  {
    key: "validation-registry",
    label: "Validation registry",
    scriptPath: "src/scripts/validate-command-center-validation-registry.mjs",
    category: "cockpit",
    requiredInValidateRoutes: true,
    protectedBoundary: "guardrail script existence, validate:routes wiring, and validation-registry metadata",
    failureMeaning: "A required validator is missing, unwired, or no longer represented in the validation registry.",
  },
  {
    key: "maximum-protection-standard",
    label: "Maximum protection standard",
    scriptPath: "src/scripts/validate-maximum-protection-standard.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "maximum-protection doctrine for data classification, deny-by-default access, secret handling, exfiltration prevention, AI-agent containment, supply-chain risk, auditability, emergency controls, and public/private doctrine boundaries",
    failureMeaning: "The maximum-protection doctrine may no longer be enforced, discoverable, or wired into the central validation chain.",
  },
  {
    key: "owner-maximum-protection-posture",
    label: "Owner maximum protection posture",
    scriptPath: "src/scripts/validate-owner-maximum-protection-posture.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "owner-facing maximum-protection doctrine, owner operating locks, protected launch posture, validation registry visibility, docs-index coverage, and validate:routes wiring",
    failureMeaning: "Owner maximum-protection posture may no longer be enforced, discoverable, documented, or visible to production smoke coverage.",
  },
  {
    key: "codeql-workflow-integrity",
    label: "CodeQL workflow integrity",
    scriptPath: "src/scripts/validate-codeql-workflow-integrity.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "CodeQL workflow triggers, minimal permissions, checkout v6, CodeQL v4, JavaScript/TypeScript analysis, security-and-quality query posture, and no broad write permission or continue-on-error drift",
    failureMeaning: "The CodeQL workflow may have drifted into stale action versions, weakened permissions, missing security query posture, missing main/PR/schedule coverage, or non-failing security analysis.",
  },
  {
    key: "dependency-lockfile-integrity",
    label: "Dependency lockfile integrity",
    scriptPath: "src/scripts/validate-dependency-lockfile-integrity.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "package manager, Node engine, validate route-chain script, key package ranges, lockfile resolved versions, and dependency integrity documentation stay aligned",
    failureMeaning: "Package or lockfile posture may have drifted from the approved dependency anchors or the dependency integrity documentation.",
  },
  {
    key: "repo-update-scanning-automation",
    label: "Repo update scanning automation",
    scriptPath: "src/scripts/validate-repo-update-scanning-automation.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "Dependabot groups, CodeQL workflow, dependency integrity, most-pristine coverage, repo update scanning documentation, route-chain indirect coverage, and release-captain review posture stay aligned",
    failureMeaning: "Automated update scanning may have drifted from approved Dependabot grouping, CodeQL v4 and checkout v6 posture, dependency integrity, documentation, or guarded release-captain review.",
  },
  {
    key: "controlled-continuous-evolution",
    label: "Controlled continuous evolution",
    scriptPath: "src/scripts/validate-controlled-continuous-evolution.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "monitored, validated, reviewable, rollback-ready updates, small coherent batches, Vercel gate posture, and no uncontrolled production mutation or quality drift",
    failureMeaning: "Continuous update posture may have drifted toward unreviewed production mutation, skipped validation, skipped Vercel gates, hidden failures, or weakened safeguards.",
  },
  {
    key: "controlled-maintenance",
    label: "Controlled maintenance",
    scriptPath: "src/scripts/validate-controlled-maintenance-contracts.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "safe update queues, review streams, validation gates, rollback planning, audit records, and no uncontrolled AI changes or automatic production mutation",
    failureMeaning: "Controlled maintenance may have drifted toward validation bypass, approval bypass, missing rollback plans, audit deletion, raw/private exposure, uncontrolled production mutation, or unsupported outcome claims.",
  },
  {
    key: "report-truth-engine",
    label: "Report truth engine",
    scriptPath: "src/scripts/validate-report-truth-engine.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "evidence-first reports, minimum-input enrichment, traceable calculations, confidence labels, plan conversion rules, and report growth standards",
    failureMeaning: "Report generation can no longer be proven evidence-backed, calculation-traceable, uncertainty-labeled, visually official, social-platform-aware, and truthful about plan recommendations.",
  },
  {
    key: "report-evidence-orchestration",
    label: "Report evidence orchestration",
    scriptPath: "src/scripts/validate-report-evidence-orchestration.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "evidence source tiers, trust levels, conflict handling, confidence language, plan-fit thresholds, release-captain review, and blocked report patterns",
    failureMeaning: "Report evidence handling may no longer separate source classes, confidence levels, conflicts, plan-fit recommendations, or unsafe customer-facing claims.",
  },
  {
    key: "report-evidence-orchestration-runtime",
    label: "Report evidence orchestration runtime",
    scriptPath: "src/scripts/validate-report-evidence-orchestration-runtime.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "safe evidence projections, blocked-pattern surfacing, release-captain review posture, customer-output eligibility, and redacted report evidence summaries",
    failureMeaning: "Report evidence inputs may no longer project into safe summaries, blocked-pattern flags, review posture, or customer-output eligibility before report use.",
  },
  {
    key: "report-evidence-orchestration-api",
    label: "Report evidence orchestration API",
    scriptPath: "src/scripts/validate-command-center-report-evidence-orchestration-api.mjs",
    category: "route",
    requiredInValidateRoutes: true,
    protectedBoundary: "command-center-only report evidence projection route, safe-summary-only input, no-store/noindex response headers, raw/private payload rejection, and no customer-facing report approval",
    failureMeaning: "Report evidence API behavior may no longer be command-center gated, safe-summary-only, runtime-backed, raw/private rejecting, or blocked from approving customer-facing report output.",
  },
  {
    key: "report-evidence-records-api",
    label: "Report evidence records API",
    scriptPath: "src/scripts/validate-command-center-report-evidence-records-api.mjs",
    category: "route",
    requiredInValidateRoutes: true,
    protectedBoundary: "command-center-only report evidence records route, safe-summary-only input, append-only safe projection persistence, no-store/noindex response headers, raw/private payload rejection, and no customer-facing output, paid recommendation, launch, security, or public report approval",
    failureMeaning: "Report evidence records API behavior may no longer be command-center gated, safe-summary-only, persistence-backed, raw/private rejecting, append-only, no-store/noindex, or blocked from customer-facing output and launch approval drift.",
  },
  {
    key: "report-evidence-record-contracts",
    label: "Report evidence record contracts",
    scriptPath: "src/scripts/validate-report-evidence-record-contracts.mjs",
    category: "schema",
    requiredInValidateRoutes: true,
    protectedBoundary: "safe report evidence source, confidence, conflict, plan-fit, blocked-pattern, and release-review records without raw/private payload exposure or customer-facing approval drift",
    failureMeaning: "Report evidence records may no longer preserve orchestration metadata safely, or may allow raw evidence, provider payloads, private credentials, hidden conflicts, unsupported plan recommendations, or approval drift.",
  },
  {
    key: "report-evidence-record-runtime",
    label: "Report evidence record runtime",
    scriptPath: "src/scripts/validate-report-evidence-record-runtime.mjs",
    category: "schema",
    requiredInValidateRoutes: true,
    protectedBoundary: "safe generation of report evidence source, confidence, conflict, plan-fit, blocked-pattern, and release-review records from runtime projections without raw/private payload exposure or approval drift",
    failureMeaning: "Report evidence runtime records may no longer generate safe summaries, preserve release-captain review posture, or block raw evidence, provider payloads, credentials, customer data, and approval drift.",
  },
  {
    key: "report-evidence-record-persistence-runtime",
    label: "Report evidence record persistence runtime",
    scriptPath: "src/scripts/validate-report-evidence-record-persistence-runtime.mjs",
    category: "schema",
    requiredInValidateRoutes: true,
    protectedBoundary: "command-center-gated, append-only, no-store report evidence persistence projections with safe hashes and no raw/private payload exposure or approval drift",
    failureMeaning: "Report evidence persistence may no longer stay append-only, no-store, safe-summary/hash based, command-center gated, centrally covered, or blocked from raw evidence, provider payloads, credentials, customer data, private audit payloads, and approval drift.",
  },
  {
    key: "controlled-market-learning",
    label: "Controlled market learning",
    scriptPath: "src/scripts/validate-controlled-market-learning.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "market trend learning, Cendorq leverage discovery, privacy-safe aggregation, review-gated self-evolution, and strict agent boundaries",
    failureMeaning: "Market learning or self-evolution may have become unsupported, privacy-unsafe, unreviewed, unversioned, or vulnerable to agent drift.",
  },
  {
    key: "enterprise-operating-standard",
    label: "Enterprise operating standard",
    scriptPath: "src/scripts/validate-enterprise-operating-standard.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "strict-but-not-paralyzing governance across security, AI, data protection, report integrity, market learning, commercial leverage, audit defense, brand trust, and resilience",
    failureMeaning: "The system may be under-protected, over-blocked, commercially misaligned, legally careless, or missing enterprise audit expectations.",
  },
  {
    key: "audit-defense-system",
    label: "Audit defense system",
    scriptPath: "src/scripts/validate-audit-defense-system.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "claim substantiation, consent and scope records, terms alignment, release approvals, evidence retention, legal-review triggers, correction paths, and dispute-readiness metadata",
    failureMeaning: "Cendorq may be missing audit-ready proof, claim substantiation, consent, terms alignment, correction history, or release gating needed to reduce liability risk.",
  },
  {
    key: "most-pristine-system-standard",
    label: "Most-pristine system standard",
    scriptPath: "src/scripts/validate-most-pristine-system-standard.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "no-weak-link quality across frontend, backend, APIs, data, AI, reports, security, privacy, audit defense, brand, performance, operations, integrations, documentation, deployment, and customer experience",
    failureMeaning: "One or more visible or invisible system layers may have fallen below the Cendorq most-pristine quality bar.",
  },
  {
    key: "report-record-contracts",
    label: "Report record contracts",
    scriptPath: "src/scripts/validate-report-record-contracts.mjs",
    category: "schema",
    requiredInValidateRoutes: true,
    protectedBoundary: "business identity, evidence, calculation, claim, consent, approval, correction, and dispute-readiness record contracts",
    failureMeaning: "Report and audit-defense records may no longer preserve required proof, privacy, release, correction, or dispute metadata.",
  },
  {
    key: "scale-resilience-standard",
    label: "Scale resilience standard",
    scriptPath: "src/scripts/validate-scale-resilience-standard.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "large-customer volume, Free Scan spikes, queue-backed work, bounded data access, safe caching, observability, and no quality downgrade under load",
    failureMeaning: "The system may not be ready to handle large customer volume or traffic spikes while preserving quality, consistency, and safeguards.",
  },
  {
    key: "customer-platform-standard",
    label: "Customer platform standard",
    scriptPath: "src/scripts/validate-customer-platform-standard.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "signup-first Free Scan, mandatory email confirmation, provider and password auth, email deliverability, dashboard ownership, billing entitlements, lifecycle sequences, and truthful plan conversion",
    failureMeaning: "Customer signup, dashboard, billing, email, lifecycle, or conversion flows may no longer preserve verified identity, deliverability, platform ownership, plan truth, or secure access.",
  },
  {
    key: "customer-experience-standard",
    label: "Customer experience standard",
    scriptPath: "src/scripts/validate-customer-experience-standard.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "exceptional luxury dashboard experience, command-room UX, proof-centered trust, complete navigation, momentum, accessibility, performance, and brand moat",
    failureMeaning: "The customer dashboard may no longer meet the exceptional luxury, proof-centered, conversion-aware, accessible, fast, and brand-owned experience standard.",
  },
  {
    key: "conversion-moat-standard",
    label: "Conversion moat standard",
    scriptPath: "src/scripts/validate-conversion-moat-standard.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "highest truthful conversion through proof, stage-aware CTAs, frictionless billing, lifecycle emails, retention, ethical experiments, and privacy-safe analytics",
    failureMeaning: "Conversion may have drifted toward weak, generic, dark-pattern, unmeasured, or unsupported plan progression.",
  },
  {
    key: "insights-conversation-standard",
    label: "Insights conversation standard",
    scriptPath: "src/scripts/validate-insights-conversation-standard.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "strategic insights and dashboard conversation that stay evidence-grounded, plan-aware, privacy-safe, branded, escalation-ready, and conversion-useful",
    failureMeaning: "Dashboard conversation may have become unsupported, unsafe, off-brand, privacy-risky, or disconnected from report evidence and plan logic.",
  },
  {
    key: "operator-runbook",
    label: "Operator runbook and owner workflow chain",
    scriptPath: "src/scripts/validate-command-center-operator-runbook.mjs",
    category: "docs",
    requiredInValidateRoutes: true,
    protectedBoundary: "documented operator maintenance standard plus owner configuration evidence API, workflow API, workflow panel, approval workflow runtime, and workflow smoke-validator coverage",
    failureMeaning: "The runbook or owner configuration workflow validator chain no longer documents or enforces the closed-by-default metadata-only operating rules.",
  },
  {
    key: "docs-index",
    label: "Docs index",
    scriptPath: "src/scripts/validate-command-center-docs-index.mjs",
    category: "docs",
    requiredInValidateRoutes: true,
    protectedBoundary: "discoverable standards, source-of-truth files, and guardrail validators",
    failureMeaning: "The private documentation index no longer points operators to required standards and guards.",
  },
  {
    key: "owner-operating-manual",
    label: "Owner operating manual",
    scriptPath: "src/scripts/validate-owner-operating-manual.mjs",
    category: "docs",
    requiredInValidateRoutes: true,
    protectedBoundary: "owner-level evidence accuracy, tailored plan fit, conversion moat, market learning, launch review, and post-build operating cadence",
    failureMeaning: "The owner operating manual no longer preserves the highest-level evidence-backed operating direction or has drifted toward unsafe guarantees.",
  },
  {
    key: "optimization-method-library",
    label: "Optimization method library",
    scriptPath: "src/scripts/validate-optimization-method-library.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "evidence-backed method controls and customer-safe rules",
    failureMeaning: "Approved optimization methods drifted away from evidence-backed, plan-scoped guardrails.",
  },
  {
    key: "customer-output-approval",
    label: "Customer output approval",
    scriptPath: "src/scripts/validate-customer-output-approval.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "review, preview, block-condition, and audit requirements before customer send",
    failureMeaning: "Customer-facing output can no longer be proven review-gated and approval-controlled.",
  },
  {
    key: "ai-manager-command-queue",
    label: "AI manager command queue",
    scriptPath: "src/scripts/validate-ai-manager-command-queue.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "AI command context, guard, and blocked-action policy",
    failureMeaning: "AI manager commands drifted toward unsafe actions or missing review gates.",
  },
  {
    key: "ai-manager-command-history",
    label: "AI manager command history",
    scriptPath: "src/scripts/validate-ai-manager-command-history.mjs",
    category: "ai",
    requiredInValidateRoutes: true,
    protectedBoundary: "AI command audit trail and retention-state metadata",
    failureMeaning: "AI command history no longer captures required review, block, audit, or retention metadata.",
  },
  {
    key: "production-smoke-coverage",
    label: "Production smoke coverage",
    scriptPath: "src/scripts/validate-production-smoke-coverage.mjs",
    category: "smoke",
    requiredInValidateRoutes: true,
    protectedBoundary: "production smoke checks, closed routes, owner-maximum-protection-posture, Owner maximum protection posture, validate-owner-maximum-protection-posture.mjs, and guardrail synchronization",
    failureMeaning: "Production smoke coverage no longer verifies required public, protected, owner maximum-protection posture, and documentation guards.",
  },
  {
    key: "closed-intelligence",
    label: "Closed intelligence",
    scriptPath: "src/scripts/validate-closed-intelligence.mjs",
    category: "security",
    requiredInValidateRoutes: true,
    protectedBoundary: "private intelligence, raw evidence, and gated AI surfaces",
    failureMeaning: "Private intelligence or raw evidence boundaries may have become publicly exposed.",
  },
] as const satisfies readonly CommandCenterValidationRegistryItem[];

export function getCommandCenterValidationRegistry() {
  return COMMAND_CENTER_VALIDATION_REGISTRY;
}
