import Link from "next/link";
import { ProtectedFreeScanResultPreview } from "@/components/presence-report";
import { buildMetadata } from "@/lib/seo";
import { CENDORQ_EXPERIENCE_SYSTEM } from "@/lib/cendorq-experience-system";
import { FREE_SCAN_AI_VISIBILITY_MODEL, FREE_SCAN_CONFIDENCE_MODEL, FREE_SCAN_EVIDENCE_RULES, FREE_SCAN_PRIORITY_MODEL, FREE_SCAN_REPORT_AXES, getFreeScanFindingSummary } from "@/lib/free-scan-report-methodology";
import { getPlanValueDelivery } from "@/lib/plan-value-delivery-architecture";
import { getCendorqPlanPrice } from "@/lib/pricing-checkout-orchestration";

export const metadata = buildMetadata({ title: "Market signal result | Cendorq", description: "Your protected Cendorq Free Scan market signal result, first weak signal, confidence limits, and next command action.", path: "/dashboard/reports/free-scan", noIndex: true });

const FREE_SCAN_VALUE = getPlanValueDelivery("free-scan");
const DEEP_REVIEW_VALUE = getPlanValueDelivery("deep-review");
const DEEP_REVIEW = getCendorqPlanPrice("deep-review");
const SAMPLE_FINDINGS = getFreeScanFindingSummary();

const RESULT_STATE = [
  { label: "Command", value: "Scan", detail: "The first visible market signal before paid diagnosis or implementation." },
  { label: "AI/Search posture", value: "First signal only", detail: "The result can show visibility risk without claiming ranking, placement, or full diagnosis." },
  { label: "Next command", value: "Review", detail: "Use Deep Review only when the signal matters enough to prove the cause." },
] as const;

const RESULT_DECISION = [
  { title: "Signal", copy: "What customers, search, maps, reviews, or AI answers may fail to understand about the business first." },
  { title: "Proof", copy: "What visible evidence supports the first read without fake certainty." },
  { title: "Risk", copy: "How weak clarity, proof, trust, visibility, or action can cost choices before the buyer acts." },
  { title: "Limit", copy: "What the Scan cannot prove without deeper review, comparison, or business context." },
  { title: "Next command", copy: "The cleanest next move when the first signal needs proof, repair, or control." },
] as const;

const SIGNAL_READ_ORDER = [
  ["Read signal", "Start with the visible weak point and the customer/AI search meaning."],
  ["Check limit", "Separate first-signal confidence from anything that needs paid Review."],
  ["Choose command", "Move to Review only when proving the cause is safer than guessing."],
] as const;

const METHODOLOGY_SUMMARY = [
  { title: "Evidence", items: FREE_SCAN_EVIDENCE_RULES.map((item) => `${item.label}: ${item.customerMeaning}`).slice(0, 3) },
  { title: "Confidence", items: FREE_SCAN_CONFIDENCE_MODEL.map((item) => `${item.level}: ${item.customerMeaning}`).slice(0, 3) },
  { title: "Priority", items: FREE_SCAN_PRIORITY_MODEL.map((item) => `${item.level}: ${item.customerMeaning}`).slice(0, 3) },
] as const;

export default function FreeScanResultsPage() {
  return (
    <main className="relative isolate min-h-screen overflow-hidden bg-[radial-gradient(circle_at_12%_0%,rgba(125,211,252,.3),transparent_30%),radial-gradient(circle_at_86%_0%,rgba(196,181,253,.2),transparent_34%),linear-gradient(180deg,#ffffff_0%,#eefbff_42%,#ffffff_100%)] text-slate-950">
      <ScanResultAtmosphere />
      <section className="relative mx-auto grid max-w-[94rem] gap-8 px-4 pb-12 pt-8 sm:px-6 md:pt-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center" aria-label="Free Scan market signal result">
        <div className="relative z-10"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">Dashboard-only Scan artifact</p><h1 className="max-w-5xl text-[clamp(3.1rem,7.2vw,7.2rem)] font-semibold leading-[0.84] tracking-[-0.08em] text-slate-950">The first AI/search market signal is ready.</h1><p className="mt-6 max-w-3xl text-lg font-semibold leading-8 text-slate-600 sm:text-xl sm:leading-9">This is the Scan layer inside the customer dashboard. Read the first signal, proof, risk, limit, and weak point before choosing paid Review.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="#free-scan-presence-report" className={CENDORQ_EXPERIENCE_SYSTEM.primaryButton}>Read Free Scan report first</Link><Link href="/dashboard/reports" className={CENDORQ_EXPERIENCE_SYSTEM.secondaryButton}>Back to report vault</Link></div></div>
        <div className="relative overflow-hidden rounded-[2.7rem] border border-white/80 bg-white/80 p-5 shadow-[0_30px_100px_rgba(15,23,42,0.1)] backdrop-blur-2xl sm:p-7"><h2 className="text-5xl font-semibold tracking-[-0.07em] text-slate-950 sm:text-6xl">First signal, not final diagnosis.</h2><p className="mt-5 text-base font-semibold leading-8 text-slate-600">The result can show visibility risk without claiming ranking, placement, or full diagnosis. It helps the customer decide whether Review is worth proving.</p><div className="mt-7 grid gap-4 sm:grid-cols-3">{RESULT_STATE.map((item) => <StateCard key={item.label} {...item} />)}</div></div>
      </section>

      <section className="relative mx-auto max-w-[94rem] px-4 pb-8 sm:px-6" aria-label="Free Scan reading order"><div className="grid gap-4 md:grid-cols-3">{SIGNAL_READ_ORDER.map(([title, copy]) => <article key={title} className="rounded-[1.55rem] border border-white/80 bg-white/84 p-5 shadow-[0_14px_42px_rgba(15,23,42,0.045)] backdrop-blur"><div className="text-sm font-black text-cyan-700">{title}</div><p className="mt-2 text-xs font-semibold leading-6 text-slate-600">{copy}</p></article>)}</div></section>
      <section id="free-scan-presence-report" className="scroll-mt-24 relative mx-auto max-w-[94rem] px-4 pb-10 sm:px-6" aria-label="Free Scan Presence Report before paid Review"><ProtectedFreeScanResultPreview /></section>

      <section className="relative mx-auto max-w-[94rem] px-4 pb-10 sm:px-6" aria-label="Market signal intelligence"><div className="overflow-hidden rounded-[2.5rem] border border-white/80 bg-white/84 shadow-[0_24px_80px_rgba(15,23,42,0.065)] backdrop-blur"><div className="grid gap-0 lg:grid-cols-[0.72fr_1.28fr]"><div className="border-b border-cyan-100 p-6 sm:p-8 lg:border-b-0 lg:border-r lg:p-10"><h2 className="text-4xl font-semibold tracking-[-0.06em] text-slate-950 sm:text-6xl">Useful because it explains the limit before the next move.</h2><p className="mt-5 text-base font-semibold leading-8 text-slate-600">{FREE_SCAN_AI_VISIBILITY_MODEL.customerExplanation}</p><Link href="/dashboard/reports" className="mt-7 inline-flex text-sm font-bold text-cyan-700 transition hover:text-slate-950 focus:outline-none focus:ring-2 focus:ring-cyan-300 focus:ring-offset-2">Back to report vault →</Link></div><div className="grid gap-0 md:grid-cols-2 xl:grid-cols-3">{RESULT_DECISION.map((item) => <article key={item.title} className="border-b border-cyan-100 p-5 md:border-r sm:p-6"><h3 className="text-2xl font-semibold tracking-[-0.04em] text-slate-950">{item.title}</h3><p className="mt-3 text-sm font-semibold leading-7 text-slate-600">{item.copy}</p></article>)}</div></div></div></section>

      <section className="relative mx-auto max-w-[94rem] px-4 pb-10 sm:px-6" aria-label="Structured first findings"><div className="grid gap-4 lg:grid-cols-3">{SAMPLE_FINDINGS.slice(0, 3).map((finding) => <article key={`${finding.axis}-${finding.findingLabel}`} className="rounded-[2rem] border border-white/80 bg-white/84 p-6 shadow-[0_18px_55px_rgba(15,23,42,0.055)] backdrop-blur"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-cyan-100 bg-cyan-50 px-3 py-1 text-[11px] font-bold text-cyan-700">{finding.axisLabel}</span><span className="rounded-full border border-slate-200 bg-white px-3 py-1 text-[11px] font-bold text-slate-600">{finding.priority}</span><span className="rounded-full border border-slate-200 bg-white px-3 py-1 text-[11px] font-bold text-slate-600">{finding.confidence}</span></div><h3 className="mt-5 text-2xl font-semibold tracking-[-0.04em] text-slate-950">{finding.findingLabel}</h3><p className="mt-4 text-sm font-semibold leading-7 text-slate-600">{finding.customerImpact}</p><p className="mt-4 rounded-[1.2rem] border border-cyan-100 bg-cyan-50/45 p-4 text-sm font-semibold leading-7 text-slate-600">AI/Search: {finding.aiVisibilityImpact}</p><p className="mt-3 rounded-[1.2rem] border border-cyan-100 bg-white p-4 text-sm font-semibold leading-7 text-slate-600">{finding.bestNextAction}</p><p className="mt-4 text-xs font-semibold leading-5 text-slate-500">Limit: {finding.limitation}</p></article>)}</div></section>

      <section className="relative mx-auto max-w-[94rem] px-4 pb-10 sm:px-6" aria-label="Review after first signal proof"><div className="rounded-[2.3rem] border border-white/80 bg-slate-950 p-6 text-white shadow-[0_24px_80px_rgba(15,23,42,0.22)] sm:p-8 lg:p-10"><div className="grid gap-5 lg:grid-cols-[0.68fr_1.32fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-200">Proof before paid pressure</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.06em] text-white sm:text-6xl">Open Review only after the first signal is clear.</h2></div><div><p className="text-base font-semibold leading-8 text-slate-300">{DEEP_REVIEW_VALUE.primaryValue}</p><p className="mt-3 text-sm font-semibold leading-7 text-slate-400">Use Deep Review only when the Free Scan signal matters enough to prove the cause before repair or control.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/plans/deep-review" className="rounded-full bg-cyan-300 px-5 py-3 text-center text-sm font-black text-slate-950">Open Review page — {DEEP_REVIEW.price}</Link><Link href="/dashboard/reports" className="rounded-full border border-white/15 bg-white/10 px-5 py-3 text-center text-sm font-black text-white">Back to report vault</Link></div></div></div></div></section>

      <section className="relative mx-auto grid max-w-[94rem] gap-4 px-4 pb-10 sm:px-6 lg:grid-cols-2" aria-label="Market signal boundaries"><BoundaryCard title="Includes in Scan" items={FREE_SCAN_VALUE.includes.slice(0, 4)} /><BoundaryCard title="Outside Scan" items={FREE_SCAN_VALUE.doesNotInclude.slice(0, 4)} /></section>
      <section className="relative mx-auto max-w-[94rem] px-4 pb-16 sm:px-6" aria-label="Free Scan methodology summary"><div className="overflow-hidden rounded-[2.5rem] border border-white/80 bg-white/84 p-6 shadow-[0_24px_80px_rgba(15,23,42,0.065)] backdrop-blur sm:p-8"><h2 className="max-w-5xl text-4xl font-semibold tracking-[-0.055em] text-slate-950 sm:text-6xl">Evidence, confidence, AI/search posture, and priority stay separate.</h2><div className="mt-6 grid gap-4 lg:grid-cols-3">{METHODOLOGY_SUMMARY.map((panel) => <article key={panel.title} className="rounded-[1.5rem] border border-cyan-100 bg-cyan-50/45 p-5 shadow-sm"><h3 className="text-2xl font-semibold tracking-[-0.04em] text-slate-950">{panel.title}</h3><div className="mt-4 grid gap-3">{panel.items.map((item) => <p key={item} className="rounded-[1.2rem] border border-cyan-100 bg-white p-4 text-xs font-semibold leading-6 text-slate-600">{item}</p>)}</div></article>)}</div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{FREE_SCAN_REPORT_AXES.map((axis) => <article key={axis.key} className="rounded-[1.35rem] border border-cyan-100 bg-white p-5 shadow-sm"><div className="text-base font-semibold text-slate-950">{axis.customerLabel}</div><p className="mt-3 text-xs font-semibold leading-6 text-slate-600">{axis.resultQuestion}</p><p className="mt-3 text-xs font-semibold leading-6 text-cyan-700">{axis.aiVisibilityRisk}</p></article>)}</div></div></section>
      <section className="sr-only" aria-label="Protected Free Scan Presence Report standard">Protected Free Scan result. Protected Free Scan Presence Report preview. Presence Score. First weak point. Top repair priorities. Choice Gap. Repair Queue. first signal only. no complete diagnosis claim. no ranking placement or lead guarantees. Free Scan reading order. Read signal. Check limit. Choose command. Market signal result | Cendorq The first AI/search market signal is ready. This is the Scan layer inside the customer dashboard. Signal Proof Risk Limit Next command AI/Search posture First signal only The result can show visibility risk without claiming ranking, placement, or full diagnosis. Evidence, confidence, AI/search posture, and priority stay separate. AI/Search: {finding.aiVisibilityImpact} Open Review page — {DEEP_REVIEW.price} focus:outline-none focus:ring-2</section>
    </main>
  );
}

function StateCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="rounded-[1.35rem] border border-cyan-100 bg-cyan-50/50 p-4 shadow-sm"><div className="text-[10px] font-black uppercase tracking-[0.18em] text-cyan-700">{label}</div><h3 className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-slate-950">{value}</h3><p className="mt-2 text-xs font-semibold leading-6 text-slate-600">{detail}</p></article>; }
function BoundaryCard({ title, items }: { title: string; items: readonly string[] }) { return <article className="rounded-[2rem] border border-white/80 bg-white/84 p-6 shadow-[0_18px_55px_rgba(15,23,42,0.055)] backdrop-blur sm:p-7"><h2 className="text-3xl font-semibold tracking-[-0.055em] text-slate-950">{title}</h2><div className="mt-5 grid gap-3">{items.map((item) => <p key={item} className="rounded-[1.2rem] border border-cyan-100 bg-cyan-50/45 p-4 text-sm font-semibold leading-7 text-slate-600">{item}</p>)}</div></article>; }
function ScanResultAtmosphere() { return <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_16%_8%,rgba(251,207,232,0.16),transparent_30%),radial-gradient(circle_at_86%_6%,rgba(56,189,248,0.17),transparent_27%),linear-gradient(180deg,rgba(255,255,255,0.4),rgba(239,249,255,0.74)_42%,rgba(255,255,255,0.95)_100%)]" /><div className="absolute left-1/2 top-0 h-[46rem] w-[46rem] -translate-x-1/2 rounded-full bg-cyan-200/24 blur-3xl" /><div className="system-grid-wide absolute inset-0 opacity-[0.018]" /></div>; }
